// src/modules/features/jobs/presentation/ui/job-details/JobNodeLogs.tsx
import { useState, type ReactNode } from 'react';
import { Trans, useLingui } from '@lingui/react/macro';
import { ChevronDown, ChevronRight, Radio, Terminal, X } from 'lucide-react';
import { Badge, Button } from '@shadcn';
import { Permission, useCan } from '@platform/authz';
import { cn } from '@shared/presentation/utils';
import { useMeasuredHeight } from '@shared/presentation/hooks/use-measured-height.ts';
import { getStatusConfig } from '@shared/utils/status-config.ts';
import { calculateExecutionDuration, formatDuration } from '@shared/utils/date-utils.ts';
import type { JobEntity } from '@/modules/features/jobs/domain/entities/job.entity.ts';
import { JobLogDisplay } from '@/modules/features/jobs/presentation/ui/jobs-log/JobLogDisplay.tsx';

/** The whole job's `h-9` header, the only one whose height the column has to allow for. */
const PANEL_HEADER_HEIGHT = 36;
/** The panel's own `border` (1px top + 1px bottom), on top of the header. */
const PANEL_BORDER_HEIGHT = 2;
/** Below this a log is a peephole; the column scrolls rather than shrink past it. */
const MIN_LOG_HEIGHT = 192;
/** What a node's log stands at, however many are open — the column takes the overflow. */
const NODE_LOG_HEIGHT = 448;

/** The whole job is only ever shown alone, so its log gets the column entire. */
const wholeJobLogHeight = (columnHeight: number | null): number | undefined =>
  columnHeight === null
    ? undefined
    : Math.max(MIN_LOG_HEIGHT, columnHeight - PANEL_HEADER_HEIGHT - PANEL_BORDER_HEIGHT);

interface JobNodeLogsProps {
  job: JobEntity;
  /** From the URL, in execution order. Ids no node matches are already dropped. */
  openNodeIds: readonly string[];
  isWholeJobOpen: boolean;
  /** Adds or removes one node's panel, leaving the other open ones alone. */
  onToggleNode: (nodeId: string) => void;
  /** Drops every node panel, which is what brings the whole job back. */
  onShowWholeJob: () => void;
}

interface LogPanelProps {
  ariaLabel: string;
  header: ReactNode;
  collapsed?: boolean;
  children: ReactNode;
}

const LogPanel = ({ ariaLabel, header, collapsed = false, children }: LogPanelProps) => (
  <section
    aria-label={ariaLabel}
    className='flex min-w-0 shrink-0 flex-col overflow-hidden rounded-xl border border-border shadow-sm'
  >
    {header}
    {/* Collapsing only hides the log, so its stream stays open — no
        reconnect when the reader expands it again. */}
    <div className={cn(collapsed && 'hidden')}>{children}</div>
  </section>
);

interface NodeLogHeaderProps {
  nodeId: string;
  state: JobEntity['nodeExecutions'][number]['state'];
  collapsed: boolean;
  collapseLabel: string;
  expandLabel: string;
  closeLabel: string;
  onToggleCollapse: () => void;
  onClose: () => void;
}

/**
 * The whole line collapses the panel, the way the node list this page replaced
 * read: a chevron leading, then the status, the node and what it ended as. Only
 * the close button is left out of it — a button inside a button is no HTML, and
 * closing is not collapsing.
 */
const NodeLogHeader = ({
  nodeId,
  state,
  collapsed,
  collapseLabel,
  expandLabel,
  closeLabel,
  onToggleCollapse,
  onClose,
}: NodeLogHeaderProps) => {
  const { i18n } = useLingui();
  const config = getStatusConfig(state);
  const Icon = config.icon;
  const Chevron = collapsed ? ChevronRight : ChevronDown;

  return (
    <header className='flex shrink-0 items-center border-b border-border bg-muted/40 pr-2'>
      <Button
        variant='ghost'
        type='button'
        onClick={onToggleCollapse}
        aria-expanded={!collapsed}
        aria-label={collapsed ? expandLabel : collapseLabel}
        className='h-auto min-w-0 flex-1 justify-start gap-3 rounded-none p-3 hover:scale-100'
      >
        <Chevron className='size-4 text-muted-foreground' />
        <Icon className={cn('size-5', config.iconClassName)} />
        <p className='min-w-0 truncate text-sm font-medium text-foreground'>{nodeId}</p>
        <Badge variant='outline' className={config.badgeClassName}>
          {i18n._(config.label)}
        </Badge>
      </Button>
      <button
        type='button'
        onClick={onClose}
        aria-label={closeLabel}
        className='shrink-0 rounded-md p-1 text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground'
      >
        <X className='size-4' />
      </button>
    </header>
  );
};

/**
 * The job's logs: the job as a whole, or the nodes the reader picked out of it.
 *
 * Comparing what two nodes printed is the point, so the nav adds and removes
 * node panels rather than switching between them, and each keeps the same
 * readable height whether it is alone or one of five — past the room the page
 * has, the column scrolls. The whole job is what shows when no node is picked,
 * never a panel alongside them, which is why it has no close button: closing
 * the last node is what comes back to it.
 *
 * Every open panel keeps its own live stream, and closing one unmounts it,
 * which is what cancels that stream.
 */
export const JobNodeLogs = ({
  job,
  openNodeIds,
  isWholeJobOpen,
  onToggleNode,
  onShowWholeJob,
}: JobNodeLogsProps) => {
  const { t } = useLingui();
  const canViewLogs = useCan(Permission.READ_JOB_LOGS);
  const { height, containerRef } = useMeasuredHeight();
  const [collapsedIds, setCollapsedIds] = useState<ReadonlySet<string>>(() => new Set());

  const toggleCollapse = (nodeId: string) =>
    setCollapsedIds(current => {
      const next = new Set(current);
      if (next.has(nodeId)) next.delete(nodeId);
      else next.add(nodeId);
      return next;
    });

  if (!canViewLogs) {
    return (
      <p className='text-sm italic text-muted-foreground'>
        <Trans>You don't have permission to view this job's logs</Trans>
      </p>
    );
  }

  const nodes = job.nodeExecutions.map((node, index) => ({ node, id: node.id || String(index) }));
  const openNodes = nodes.filter(({ id }) => openNodeIds.includes(id));
  const wholeJobLabel = t`Whole job`;
  const closeLabelFor = (label: string) => t`Close the logs for ${label}`;
  const collapseLabelFor = (label: string) => t`Collapse the logs for ${label}`;
  const expandLabelFor = (label: string) => t`Expand the logs for ${label}`;

  const buttonClassName = (isOpen: boolean) =>
    cn(
      'shrink-0 rounded-lg border border-border px-3 py-2 text-left text-sm transition-colors hover:bg-accent hover:text-accent-foreground',
      isOpen && 'border-primary bg-primary/10 text-primary',
    );

  return (
    <div className='flex min-h-0 flex-1 flex-col gap-3'>
      <div className='flex items-center gap-2'>
        <div className='flex size-8 items-center justify-center rounded-lg bg-primary/10'>
          <Terminal className='size-4 text-primary' />
        </div>
        <h2 className='text-lg font-semibold text-foreground'>
          <Trans>Logs</Trans>
        </h2>
        <span className='flex items-center gap-1.5 text-sm text-muted-foreground'>
          <Radio className='size-4 animate-pulse text-green-500' />
          <Trans>Streaming live output</Trans>
        </span>
      </div>

      <div className='flex min-h-0 flex-1 flex-col gap-3 lg:flex-row'>
        <nav
          aria-label={t`Node executions`}
          className='flex shrink-0 gap-1.5 overflow-x-auto lg:w-60 lg:flex-col lg:overflow-x-visible lg:overflow-y-auto'
        >
          <button
            type='button'
            onClick={onShowWholeJob}
            aria-pressed={isWholeJobOpen}
            className={buttonClassName(isWholeJobOpen)}
          >
            <Trans>Whole job</Trans>
          </button>

          <span aria-hidden className='w-px shrink-0 self-stretch bg-border lg:h-px lg:w-auto' />

          {nodes.map(({ node, id }) => {
            const config = getStatusConfig(node.state);
            const Icon = config.icon;
            const duration = calculateExecutionDuration(node.startedAt, node.finishedAt);
            const isOpen = openNodeIds.includes(id);

            return (
              <button
                key={id}
                type='button'
                onClick={() => onToggleNode(id)}
                aria-pressed={isOpen}
                className={cn('flex items-center gap-2', buttonClassName(isOpen))}
              >
                <Icon className={cn('size-4 shrink-0', config.iconClassName)} />
                <span className='min-w-0 flex-1 truncate text-sm font-medium'>{id}</span>
                <span className='shrink-0 text-xs text-muted-foreground'>
                  {duration === null ? '-' : formatDuration(duration)}
                </span>
              </button>
            );
          })}
        </nav>

        {/* The column's height comes from the layout and never from the panels
            inside it, or measuring it would resize what it measures. */}
        <div
          ref={containerRef}
          className='flex min-h-0 min-w-0 flex-1 flex-col gap-3 overflow-y-auto'
        >
          {isWholeJobOpen ? (
            <LogPanel
              ariaLabel={wholeJobLabel}
              header={
                <header className='flex h-9 shrink-0 items-center border-b border-border bg-muted/40 px-3'>
                  <p className='truncate text-sm font-medium text-foreground'>{wholeJobLabel}</p>
                </header>
              }
            >
              <JobLogDisplay jobId={job.id} maxHeight={wholeJobLogHeight(height)} />
            </LogPanel>
          ) : (
            openNodes.map(({ node, id }) => (
              <LogPanel
                key={id}
                ariaLabel={id}
                collapsed={collapsedIds.has(id)}
                header={
                  <NodeLogHeader
                    nodeId={id}
                    state={node.state}
                    collapsed={collapsedIds.has(id)}
                    collapseLabel={collapseLabelFor(id)}
                    expandLabel={expandLabelFor(id)}
                    closeLabel={closeLabelFor(id)}
                    onToggleCollapse={() => toggleCollapse(id)}
                    onClose={() => onToggleNode(id)}
                  />
                }
              >
                <JobLogDisplay jobId={job.id} nodeId={id} maxHeight={NODE_LOG_HEIGHT} />
              </LogPanel>
            ))
          )}
        </div>
      </div>
    </div>
  );
};

// extensions/scylla-base/src/features/jobs/presentation/ui/job-details/JobNodeLogs.svelte
<script lang="ts">
  import { SvelteSet } from 'svelte/reactivity';
  import ChevronDownIcon from '@lucide/svelte/icons/chevron-down';
  import ChevronRightIcon from '@lucide/svelte/icons/chevron-right';
  import RadioIcon from '@lucide/svelte/icons/radio';
  import TerminalIcon from '@lucide/svelte/icons/terminal';
  import XIcon from '@lucide/svelte/icons/x';
  import { Permission, can } from '@platform/authz';
  import { Badge, Button } from '@scylla/ui/shadcn';
  import { getStatusIcon } from '@shared/presentation/ui';
  import { createMeasuredHeight } from '@scylla/ui/state';
  import { cn } from '@scylla/ui/utils';
  import { t } from '@scylla/ui/i18n';
  import { calculateExecutionDuration, formatDuration } from '@shared/utils/date-utils.ts';
  import { getStatusConfig } from '@shared/utils/status-config.ts';
  import type { JobEntity } from '../../../domain/entities/job.entity.ts';
  import { nodeIdOf } from '../jobs-table/job-timeline.calculator.ts';
  import JobLogDisplay from '../jobs-log/JobLogDisplay/JobLogDisplay.svelte';
  import { jobsMessages } from '../jobs.messages.ts';

  const PANEL_HEADER_HEIGHT = 36;
  const PANEL_BORDER_HEIGHT = 2;
  /** The column scrolls rather than shrink a log below this. */
  const MIN_LOG_HEIGHT = 192;
  /** A node log's height, however many are open: the column scrolls. */
  const NODE_LOG_HEIGHT = 448;

  interface Props {
    job: JobEntity;
    /** From the URL, in execution order. */
    openNodeIds: readonly string[];
    isWholeJobOpen: boolean;
    onToggleNode: (nodeId: string) => void;
    /** Closes every node panel, which shows the whole job again. */
    onShowWholeJob: () => void;
  }

  let { job, openNodeIds, isWholeJobOpen, onToggleNode, onShowWholeJob }: Props = $props();

  const canViewLogs = $derived(can(Permission.READ_JOB_LOGS));

  // Sized by the layout, never by the panels, or the measure feeds back into itself.
  const column = createMeasuredHeight();

  const collapsedIds = new SvelteSet<string>();

  const toggleCollapse = (nodeId: string) => {
    if (collapsedIds.has(nodeId)) collapsedIds.delete(nodeId);
    else collapsedIds.add(nodeId);
  };

  const nodes = $derived(
    job.nodeExecutions.map((node, index) => ({ node, id: nodeIdOf(node, index) })),
  );
  const openNodes = $derived(nodes.filter(({ id }) => openNodeIds.includes(id)));

  /** The whole job always shows alone: it gets the whole column. */
  const wholeJobLogHeight = $derived(
    column.height === null
      ? undefined
      : Math.max(MIN_LOG_HEIGHT, column.height - PANEL_HEADER_HEIGHT - PANEL_BORDER_HEIGHT),
  );

  const navButtonClass = (isOpen: boolean) =>
    cn(
      'shrink-0 rounded-lg border border-border px-3 py-2 text-left text-sm transition-colors hover:bg-accent hover:text-accent-foreground',
      isOpen && 'border-primary bg-primary/10 text-primary',
    );
</script>

<!--
  The whole job, or the nodes the reader opened side by side to compare them.
  Each open panel keeps its own stream; closing a panel cancels it.
-->
{#if !canViewLogs}
  <p class="text-sm italic text-muted-foreground">{t(jobsMessages.logsDenied)}</p>
{:else}
  <div class="flex min-h-0 flex-1 flex-col gap-3">
    <div class="flex items-center gap-2">
      <div class="flex size-8 items-center justify-center rounded-lg bg-primary/10">
        <TerminalIcon class="size-4 text-primary" />
      </div>
      <h2 class="text-lg font-semibold text-foreground">{t(jobsMessages.logs)}</h2>
      <span class="flex items-center gap-1.5 text-sm text-muted-foreground">
        <RadioIcon class="size-4 animate-pulse text-green-500" />
        {t(jobsMessages.streamingLive)}
      </span>
    </div>

    <div class="flex min-h-0 flex-1 flex-col gap-3 lg:flex-row">
      <nav
        aria-label={t(jobsMessages.nodeExecutions)}
        class="flex shrink-0 gap-1.5 overflow-x-auto lg:w-60 lg:flex-col lg:overflow-x-visible lg:overflow-y-auto"
      >
        <button
          type="button"
          onclick={onShowWholeJob}
          aria-pressed={isWholeJobOpen}
          class={navButtonClass(isWholeJobOpen)}
        >
          {t(jobsMessages.wholeJob)}
        </button>

        <span aria-hidden="true" class="w-px shrink-0 self-stretch bg-border lg:h-px lg:w-auto"
        ></span>

        {#each nodes as { node, id } (id)}
          {@const config = getStatusConfig(node.state)}
          {@const Icon = getStatusIcon(node.state)}
          {@const duration = calculateExecutionDuration(node.startedAt, node.finishedAt)}
          <button
            type="button"
            onclick={() => onToggleNode(id)}
            aria-pressed={openNodeIds.includes(id)}
            class={cn('flex items-center gap-2', navButtonClass(openNodeIds.includes(id)))}
          >
            <Icon class={cn('size-4 shrink-0', config.iconClassName)} />
            <span class="min-w-0 flex-1 truncate text-sm font-medium">{id}</span>
            <span class="shrink-0 text-xs text-muted-foreground">
              {duration === null ? '-' : formatDuration(duration)}
            </span>
          </button>
        {/each}
      </nav>

      <div
        use:column.measure
        class="flex min-h-0 min-w-0 flex-1 flex-col gap-3 overflow-y-auto"
      >
        {#if isWholeJobOpen}
          <section
            aria-label={t(jobsMessages.wholeJob)}
            class="flex min-w-0 shrink-0 flex-col overflow-hidden rounded-xl border border-border shadow-sm"
          >
            <header
              class="flex h-9 shrink-0 items-center border-b border-border bg-muted/40 px-3"
            >
              <p class="truncate text-sm font-medium text-foreground">
                {t(jobsMessages.wholeJob)}
              </p>
            </header>
            <JobLogDisplay jobId={job.id} maxHeight={wholeJobLogHeight} />
          </section>
        {:else}
          {#each openNodes as { node, id } (id)}
            {@const config = getStatusConfig(node.state)}
            {@const Icon = getStatusIcon(node.state)}
            {@const collapsed = collapsedIds.has(id)}
            <section
              aria-label={id}
              class="flex min-w-0 shrink-0 flex-col overflow-hidden rounded-xl border border-border shadow-sm"
            >
              <header
                class="flex shrink-0 items-center border-b border-border bg-muted/40 pr-2"
              >
                <Button
                  variant="ghost"
                  type="button"
                  onclick={() => toggleCollapse(id)}
                  aria-expanded={!collapsed}
                  aria-label={collapsed
                    ? t(jobsMessages.expandLogsFor(id))
                    : t(jobsMessages.collapseLogsFor(id))}
                  class="h-auto min-w-0 flex-1 justify-start gap-3 rounded-none p-3 hover:scale-100"
                >
                  {#if collapsed}
                    <ChevronRightIcon class="size-4 text-muted-foreground" />
                  {:else}
                    <ChevronDownIcon class="size-4 text-muted-foreground" />
                  {/if}
                  <Icon class={cn('size-5', config.iconClassName)} />
                  <p class="min-w-0 truncate text-sm font-medium text-foreground">{id}</p>
                  <Badge variant="outline" class={config.badgeClassName}>
                    {t(config.label)}
                  </Badge>
                </Button>
                <button
                  type="button"
                  onclick={() => onToggleNode(id)}
                  aria-label={t(jobsMessages.closeLogsFor(id))}
                  class="shrink-0 rounded-md p-1 text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
                >
                  <XIcon class="size-4" />
                </button>
              </header>
              <!-- Collapsing only hides the log: the stream stays open. -->
              <div class={cn(collapsed && 'hidden')}>
                <JobLogDisplay jobId={job.id} nodeId={id} maxHeight={NODE_LOG_HEIGHT} />
              </div>
            </section>
          {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}
