// src/modules/layout/presentation/ui/LanguageSelector.tsx
import { LanguagesIcon } from 'lucide-react';
import { useLingui } from '@lingui/react/macro';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger,
} from '@shadcn/dropdown-menu.tsx';
import { SidebarMenu, SidebarMenuButton, SidebarMenuItem, useSidebar } from '@shadcn/sidebar.tsx';
import { setAppLocale, type SupportedLocale } from '@shared/presentation/utils/i18n.ts';

interface LocaleOption {
  locale: SupportedLocale;
  label: string;
  short: string;
}

// Language names stay untranslated on purpose — a locale is always spelled in
// its own language so it stays recognizable whatever the active one is.
const LOCALE_OPTIONS: LocaleOption[] = [
  { locale: 'en', label: 'English', short: 'EN' },
  { locale: 'fr', label: 'Français', short: 'FR' },
];

export function LanguageSelector() {
  const { t, i18n } = useLingui();
  const { isMobile } = useSidebar();

  const currentLocale = (i18n.locale as SupportedLocale | undefined) ?? 'en';
  const current =
    LOCALE_OPTIONS.find(option => option.locale === currentLocale) ?? LOCALE_OPTIONS[0];

  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <SidebarMenuButton
              tooltip={`${t`Language`} · ${current.short}`}
              className='data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground'
            >
              <LanguagesIcon />
              <span className='flex-1 truncate'>{t`Language`}</span>
              <span className='text-xs text-muted-foreground'>{current.short}</span>
            </SidebarMenuButton>
          </DropdownMenuTrigger>
          <DropdownMenuContent
            className='min-w-40 rounded-lg border-border bg-background shadow-lg'
            side={isMobile ? 'bottom' : 'right'}
            align='end'
            sideOffset={4}
          >
            <DropdownMenuRadioGroup
              value={currentLocale}
              onValueChange={value => void setAppLocale(value as SupportedLocale)}
            >
              {LOCALE_OPTIONS.map(option => (
                <DropdownMenuRadioItem key={option.locale} value={option.locale}>
                  {option.label}
                </DropdownMenuRadioItem>
              ))}
            </DropdownMenuRadioGroup>
          </DropdownMenuContent>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  );
}

// src/modules/layout/presentation/ui/LanguageSelector/LanguageSelector.svelte
<script lang="ts">
  import LanguagesIcon from '@lucide/svelte/icons/languages';
  import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuRadioGroup,
    DropdownMenuRadioItem,
    DropdownMenuTrigger,
    getSidebar,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
  } from '@shadcn';
  import { setAppLocale, type SupportedLocale } from '@shared/presentation/utils/i18n.ts';
  import { activeLocale, t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { layoutMessages } from '../layout.messages.ts';

  const LOCALE_OPTIONS: { locale: SupportedLocale; label: string; short: string }[] = [
    { locale: 'en', label: 'English', short: 'EN' },
    { locale: 'fr', label: 'Français', short: 'FR' },
  ];

  const sidebar = getSidebar();

  const current = $derived(
    LOCALE_OPTIONS.find(option => option.locale === activeLocale()) ?? LOCALE_OPTIONS[0],
  );
</script>

<SidebarMenu>
  <SidebarMenuItem>
    <DropdownMenu>
      <DropdownMenuTrigger>
        {#snippet child({ props })}
          <SidebarMenuButton
            {...props}
            tooltip={`${t(layoutMessages.language)} · ${current.short}`}
            class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
          >
            <LanguagesIcon />
            <span class="flex-1 truncate">{t(layoutMessages.language)}</span>
            <span class="text-xs text-muted-foreground">{current.short}</span>
          </SidebarMenuButton>
        {/snippet}
      </DropdownMenuTrigger>
      <DropdownMenuContent
        class="min-w-40 rounded-lg border-border bg-background shadow-lg"
        side={sidebar.isMobile ? 'bottom' : 'right'}
        align="end"
        sideOffset={4}
      >
        <DropdownMenuRadioGroup
          value={current.locale}
          onValueChange={value => void setAppLocale(value as SupportedLocale)}
        >
          {#each LOCALE_OPTIONS as option (option.locale)}
            <DropdownMenuRadioItem value={option.locale}>{option.label}</DropdownMenuRadioItem>
          {/each}
        </DropdownMenuRadioGroup>
      </DropdownMenuContent>
    </DropdownMenu>
  </SidebarMenuItem>
</SidebarMenu>
