// src/modules/layout/presentation/ui/NavMain.svelte
<script lang="ts">
  import { navigateTo } from '@platform/context';
  import { routePathname } from '@platform/routing';
  import {
    SidebarGroup,
    SidebarGroupLabel,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
  } from '@shadcn';
  import type { NavItem, NavSection } from '../structs/nav-section.struct.ts';
  import { markSeen } from '../whats-new.svelte.ts';
  import { NAV_SECTION_CARD_CLASS, NAV_SECTION_DIVIDER_CLASS } from './nav-classes.ts';
  import NewBadge from './NewBadge.svelte';

  let { sections }: { sections: NavSection[] } = $props();

  const pathname = $derived(routePathname());

  const open = (item: NavItem) => {
    if (item.highlightId) markSeen(item.highlightId);
    navigateTo(item.url);
  };
</script>

{#each sections as section (section.title)}
  <SidebarGroup class={NAV_SECTION_CARD_CLASS}>
    {#if section.header}
      {@render section.header()}
      <div class={NAV_SECTION_DIVIDER_CLASS}></div>
    {:else}
      <SidebarGroupLabel class="group-data-[collapsible=icon]:hidden">
        {section.title}
      </SidebarGroupLabel>
    {/if}
    <SidebarMenu>
      {#each section.items as item (item.url)}
        <SidebarMenuItem
          class="transition-all duration-200 hover:scale-105 group-data-[collapsible=icon]:hover:scale-100"
        >
          <SidebarMenuButton
            tooltip={item.title}
            isActive={pathname.startsWith(item.url)}
            onclick={() => open(item)}
          >
            {#if item.icon}
              <item.icon />
            {/if}
            <span>{item.title}</span>
            {#if item.highlightId}
              <NewBadge highlightId={item.highlightId} />
            {/if}
          </SidebarMenuButton>
        </SidebarMenuItem>
      {/each}
    </SidebarMenu>
  </SidebarGroup>
{/each}

// src/modules/core/presentation/ui/NavMain.tsx
'use client';

import { ChevronRight, type LucideIcon } from 'lucide-react';

import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@shadcn/collapsible';
import {
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
} from '@shadcn/sidebar';

export function NavMain({
  items,
}: {
  items: {
    title: string;
    url: string;
    icon?: LucideIcon;
    isActive?: boolean;
    items?: {
      title: string;
      url: string;
    }[];
  }[];
}) {
  return (
    <SidebarGroup>
      <SidebarGroupLabel>Platform</SidebarGroupLabel>
      <SidebarMenu>
        {items.map(item => (
          <Collapsible
            key={item.title}
            asChild
            defaultOpen={item.isActive}
            className='group/collapsible'
          >
            <SidebarMenuItem>
              <CollapsibleTrigger asChild>
                <SidebarMenuButton tooltip={item.title}>
                  {item.icon && <item.icon />}
                  <span>{item.title}</span>
                  <ChevronRight className='ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90' />
                </SidebarMenuButton>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <SidebarMenuSub>
                  {item.items?.map(subItem => (
                    <SidebarMenuSubItem key={subItem.title}>
                      <SidebarMenuSubButton asChild>
                        <a href={subItem.url}>
                          <span>{subItem.title}</span>
                        </a>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                  ))}
                </SidebarMenuSub>
              </CollapsibleContent>
            </SidebarMenuItem>
          </Collapsible>
        ))}
      </SidebarMenu>
    </SidebarGroup>
  );
}
