// src/modules/shared/presentation/ui/data-display/Pagination.tsx
import { Trans } from '@lingui/react/macro';
import type { PaginationInfo } from '@shared/domain/structs/pagination.struct.ts';
import {
  Pagination as PaginationRoot,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from '@shared/presentation/ui/shadcn/pagination.tsx';

interface PaginationProps {
  paginationInfo: PaginationInfo;
  onPageChange: (page: number) => void;
  className?: string;
}

type PageItem = number | 'ellipsis';

const generatePageNumbers = (currentPage: number, totalPages: number): PageItem[] => {
  if (totalPages <= 7) {
    return Array.from({ length: totalPages }, (_, i) => i + 1);
  }

  if (currentPage <= 3) {
    return [1, 2, 3, 4, 'ellipsis', totalPages];
  }

  if (currentPage >= totalPages - 2) {
    return [1, 'ellipsis', totalPages - 3, totalPages - 2, totalPages - 1, totalPages];
  }

  return [1, 'ellipsis', currentPage - 1, currentPage, currentPage + 1, 'ellipsis', totalPages];
};

export const Pagination = ({ paginationInfo, onPageChange, className }: PaginationProps) => {
  const { page, pageSize, totalCount, totalPages, hasNext, hasPrevious } = paginationInfo;
  const pageItems = generatePageNumbers(page, totalPages);

  const start = (page - 1) * pageSize + 1;
  const end = Math.min(page * pageSize, totalCount);

  return (
    <div className={`flex flex-col items-center gap-2 ${className ?? ''}`}>
      <PaginationRoot>
        <PaginationContent className='flex-wrap justify-center'>
          <PaginationItem>
            <PaginationPrevious
              onClick={() => hasPrevious && onPageChange(page - 1)}
              className={hasPrevious ? 'cursor-pointer' : 'pointer-events-none opacity-50'}
            />
          </PaginationItem>

          {pageItems.map((item, index) => (
            <PaginationItem key={item === 'ellipsis' ? `ellipsis-${index}` : item}>
              {item === 'ellipsis' ? (
                <PaginationEllipsis />
              ) : (
                <PaginationLink
                  isActive={item === page}
                  onClick={() => onPageChange(item)}
                  className='cursor-pointer'
                >
                  {item}
                </PaginationLink>
              )}
            </PaginationItem>
          ))}

          <PaginationItem>
            <PaginationNext
              onClick={() => hasNext && onPageChange(page + 1)}
              className={hasNext ? 'cursor-pointer' : 'pointer-events-none opacity-50'}
            />
          </PaginationItem>
        </PaginationContent>
      </PaginationRoot>

      <p className='text-sm text-muted-foreground'>
        <Trans>
          Showing {start}-{end} of {totalCount}
        </Trans>
      </p>
    </div>
  );
};

// src/modules/shared/presentation/ui/data-display/Pagination.svelte
<script lang="ts">
  import {
    Pagination as PaginationRoot,
    PaginationContent,
    PaginationEllipsis,
    PaginationItem,
    PaginationLink,
    PaginationNext,
    PaginationPrevious,
  } from '@shadcn';
  import type { PaginationInfo } from '@shared/domain/structs/pagination.struct.ts';
  import { cn } from '@shared/presentation/utils';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { generatePageNumbers } from './pagination.ts';
  import { paginationMessages } from './pagination.messages.ts';

  interface Props {
    paginationInfo: PaginationInfo;
    onPageChange: (page: number) => void;
    class?: string;
  }

  let { paginationInfo, onPageChange, class: className }: Props = $props();

  const pageItems = $derived(generatePageNumbers(paginationInfo.page, paginationInfo.totalPages));
  const start = $derived((paginationInfo.page - 1) * paginationInfo.pageSize + 1);
  const end = $derived(Math.min(paginationInfo.page * paginationInfo.pageSize, paginationInfo.totalCount));
</script>

<div class={cn('flex flex-col items-center gap-2', className)}>
  <PaginationRoot>
    <PaginationContent class="flex-wrap justify-center">
      <PaginationItem>
        <PaginationPrevious
          onclick={() => paginationInfo.hasPrevious && onPageChange(paginationInfo.page - 1)}
          class={paginationInfo.hasPrevious
            ? 'cursor-pointer'
            : 'pointer-events-none opacity-50'}
        />
      </PaginationItem>

      {#each pageItems as item, index (item === 'ellipsis' ? `ellipsis-${index}` : item)}
        <PaginationItem>
          {#if item === 'ellipsis'}
            <PaginationEllipsis />
          {:else}
            <PaginationLink
              isActive={item === paginationInfo.page}
              onclick={() => onPageChange(item)}
              class="cursor-pointer"
            >
              {item}
            </PaginationLink>
          {/if}
        </PaginationItem>
      {/each}

      <PaginationItem>
        <PaginationNext
          onclick={() => paginationInfo.hasNext && onPageChange(paginationInfo.page + 1)}
          class={paginationInfo.hasNext ? 'cursor-pointer' : 'pointer-events-none opacity-50'}
        />
      </PaginationItem>
    </PaginationContent>
  </PaginationRoot>

  <p class="text-sm text-muted-foreground">
    {t(paginationMessages.showing(start, end, paginationInfo.totalCount))}
  </p>
</div>
