// extensions/scylla-base/src/shared/presentation/ui/data-display/StatusBar.svelte
<script lang="ts" generics="TItem extends StatusBarItem">
  import type { Snippet } from 'svelte';
  import { Tooltip, TooltipContent, TooltipTrigger } from '@scylla/ui/shadcn';
  import { cn } from '@scylla/ui/utils';
  import { t } from '@scylla/ui/i18n';
  import { getStatusConfig } from '@shared/utils/status-config.ts';
  import type { StatusBarItem } from './status-bar.ts';
  import { statusBarMessages } from './status-bar.messages.ts';

  interface Props {
    items: TItem[];
    /** The tooltip of every segment, with its item. Without it, no tooltips. */
    tooltip?: Snippet<[TItem]>;
    emptyLabel?: string;
    class?: string;
    /** A Tailwind height class. */
    height?: string;
  }

  let { items, tooltip, emptyLabel, class: className, height = 'h-6' }: Props = $props();

  type TriggerProps = Record<string, unknown> & { onclick?: (event: MouseEvent) => void };

  const segmentClass = (item: TItem) => {
    const config = getStatusConfig(item.status);
    return cn(
      'flex-1 min-w-[2px] max-w-full h-full rounded-sm transition-all duration-150 shrink',
      config.barClassName,
      config.barHoverClassName,
      (tooltip || item.onSelect) && 'cursor-pointer',
    );
  };
</script>

<!-- A bar of colored segments, one per status (job history, node timelines). -->
{#snippet segment(item: TItem, trigger: TriggerProps = {})}
  {#if item.onSelect}
    <button
      type="button"
      aria-label={item.label}
      data-item-id={item.id}
      {...trigger}
      onclick={event => {
        // Call the trigger's handler too: it closes the tooltip on click.
        trigger.onclick?.(event);
        event.stopPropagation();
        item.onSelect?.();
      }}
      class={segmentClass(item)}
    ></button>
  {:else}
    <div {...trigger} data-item-id={item.id} class={segmentClass(item)}></div>
  {/if}
{/snippet}

{#if items.length === 0}
  <div class={cn('w-full flex items-center justify-center py-1', height)}>
    <span class="text-xs text-muted-foreground italic">
      {emptyLabel ?? t(statusBarMessages.empty)}
    </span>
  </div>
{:else}
  <div
    class={cn(
      'w-full flex items-center gap-[1px] py-1 overflow-hidden rounded-md',
      height,
      className,
    )}
  >
    {#each items as item (item.id)}
      {#if tooltip}
        <Tooltip delayDuration={100}>
          <TooltipTrigger>
            {#snippet child({ props })}
              {@render segment(item, props)}
            {/snippet}
          </TooltipTrigger>
          <TooltipContent
            side="top"
            class="text-xs text-popover-foreground border-border p-3 shadow-lg bg-popover"
          >
            {@render tooltip(item)}
          </TooltipContent>
        </Tooltip>
      {:else}
        {@render segment(item)}
      {/if}
    {/each}
  </div>
{/if}

// src/modules/shared/presentation/ui/data-display/StatusBar.tsx
import { cn } from '@shared/presentation/utils';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@shadcn/tooltip.tsx';
import { getStatusConfig } from '@shared/utils/status-config.ts';
import type { ReactNode } from 'react';
import { Trans } from '@lingui/react/macro';

export interface StatusBarItem {
  id: string;
  status: string;
  tooltip?: ReactNode;
  /** Makes the segment activatable — it renders as a button instead of a plain bar. */
  onSelect?: () => void;
  /**
   * Accessible name for the activatable form. A colored bar has no text of its
   * own, and the tooltip is only `aria-describedby`, so without this the button
   * is unnameable for a screen reader and unfindable by name in a test.
   */
  label?: string;
}

interface StatusBarProps {
  items: StatusBarItem[];
  emptyLabel?: ReactNode;
  className?: string;
  height?: string;
}

/**
 * Generic bar chart showing colored segments per status.
 * Used for pipeline job history and job node timelines.
 */
export const StatusBar = ({ items, emptyLabel, className, height = 'h-6' }: StatusBarProps) => {
  if (items.length === 0) {
    return (
      <div className={cn('w-full flex items-center justify-center py-1', height)}>
        <span className='text-xs text-muted-foreground italic'>
          {emptyLabel ?? <Trans>No data</Trans>}
        </span>
      </div>
    );
  }

  return (
    <TooltipProvider delayDuration={100}>
      <div
        className={cn(
          'w-full flex items-center gap-[1px] py-1 overflow-hidden rounded-md',
          height,
          className,
        )}
      >
        {items.map(item => {
          const config = getStatusConfig(item.status);
          const className = cn(
            'flex-1 min-w-[2px] max-w-full h-full rounded-sm transition-all duration-150 shrink',
            config.barClassName,
            config.barHoverClassName,
            (item.tooltip || item.onSelect) && 'cursor-pointer',
          );

          const bar = item.onSelect ? (
            <button
              key={item.id}
              type='button'
              aria-label={item.label}
              onClick={event => {
                event.stopPropagation();
                item.onSelect?.();
              }}
              className={className}
            />
          ) : (
            <div key={item.id} className={className} />
          );

          if (!item.tooltip) return bar;

          return (
            <Tooltip key={item.id}>
              <TooltipTrigger asChild>{bar}</TooltipTrigger>
              <TooltipContent
                side='top'
                className='text-xs text-popover-foreground border-border p-3 shadow-lg bg-popover'
              >
                {item.tooltip}
              </TooltipContent>
            </Tooltip>
          );
        })}
      </div>
    </TooltipProvider>
  );
};
