// src/modules/features/apps/presentation/ui/components/AppCard.tsx
import { useNavigate } from 'react-router-dom';
import { Trans } from '@lingui/react/macro';
import { Copy, KeyRound, MoreHorizontal, Trash } from 'lucide-react';
import { Badge, Button, Card, CardContent } from '@shadcn';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@shadcn/dropdown-menu.tsx';
import type { AppEntity } from '@/modules/features/apps/domain/entities/app.entity.ts';
import { formatDate } from '@shared/utils/date-utils.ts';
import { toast } from 'sonner';
import { useLingui } from '@lingui/react/macro';
import { ToastMessages } from '@shared/utils/toast-messages.ts';

interface AppCardProps {
  app: AppEntity;
  onRequestDelete: (id: string) => void;
}

export const AppCard = ({ app, onRequestDelete }: AppCardProps) => {
  const navigate = useNavigate();
  const { i18n } = useLingui();

  const copyId = async () => {
    await navigator.clipboard.writeText(app.id);
    toast.success(i18n._(ToastMessages.APP_ID_COPIED));
  };

  return (
    <Card
      className='cursor-pointer gap-0 py-0 transition-colors hover:bg-accent/50'
      onClick={() => navigate(app.id)}
    >
      <CardContent className='p-4'>
        <div className='flex items-start justify-between gap-2'>
          <div className='flex min-w-0 items-center gap-3'>
            <span className='flex h-9 w-9 shrink-0 items-center justify-center rounded-md border border-success/30 bg-success/10'>
              <KeyRound className='h-4 w-4 text-success' />
            </span>
            <div className='min-w-0'>
              <p className='truncate font-semibold'>{app.name}</p>
              <p className='truncate font-mono text-xs text-muted-foreground'>{app.id}</p>
            </div>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant='ghost'
                size='icon'
                className='h-7 w-7 shrink-0'
                onClick={e => e.stopPropagation()}
              >
                <MoreHorizontal className='h-4 w-4' />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align='end' onClick={e => e.stopPropagation()}>
              <DropdownMenuItem onClick={copyId}>
                <Copy className='mr-2 h-4 w-4' />
                <Trans>Copy id</Trans>
              </DropdownMenuItem>
              <DropdownMenuItem variant='destructive' onClick={() => onRequestDelete(app.id)}>
                <Trash className='mr-2 h-4 w-4' />
                <Trans>Delete</Trans>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        {!app.isActive && (
          <Badge variant='secondary' className='mt-3'>
            <Trans>inactive</Trans>
          </Badge>
        )}
      </CardContent>

      <div className='flex items-center justify-between border-t border-dashed px-4 py-2.5'>
        <span className='text-xs text-muted-foreground'>
          <Trans>created</Trans> {formatDate(app.createdAt)}
        </span>
        <Button
          variant='ghost'
          size='icon'
          className='h-7 w-7 text-muted-foreground hover:text-destructive'
          onClick={e => {
            e.stopPropagation();
            onRequestDelete(app.id);
          }}
        >
          <Trash className='h-4 w-4' />
        </Button>
      </div>
    </Card>
  );
};

// src/modules/features/apps/presentation/ui/components/AppCard/AppCard.svelte
<script lang="ts">
  import { i18n } from '@lingui/core';
  import CopyIcon from '@lucide/svelte/icons/copy';
  import KeyRoundIcon from '@lucide/svelte/icons/key-round';
  import MoreHorizontalIcon from '@lucide/svelte/icons/more-horizontal';
  import TrashIcon from '@lucide/svelte/icons/trash';
  import { scyllaNavigate } from '@platform/context';
  import {
    Badge,
    Button,
    buttonVariants,
    Card,
    CardContent,
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
  } from '@shadcn';
  import { cn } from '@shared/presentation/utils';
  import { formatDate } from '@shared/utils/date-utils.ts';
  import { toast } from '@shared/presentation/utils/toast.ts';
  import { ToastMessages } from '@shared/utils/toast-messages.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { AppEntity } from '../../../../domain/entities/app.entity.ts';
  import { appsMessages } from '../../apps.messages.ts';

  interface Props {
    app: AppEntity;
    onRequestDelete: (id: string) => void;
    /** False disables both delete controls. */
    canDelete?: boolean;
  }

  let { app, onRequestDelete, canDelete = true }: Props = $props();

  const copyId = async () => {
    await navigator.clipboard.writeText(app.id);
    toast.success(i18n._(ToastMessages.APP_ID_COPIED));
  };
</script>

<Card
  class="cursor-pointer gap-0 py-0 transition-colors hover:bg-accent/50"
  onclick={() => scyllaNavigate.goToSubRoute(app.id)}
>
  <CardContent class="p-4">
    <div class="flex items-start justify-between gap-2">
      <div class="flex min-w-0 items-center gap-3">
        <span
          class="flex h-9 w-9 shrink-0 items-center justify-center rounded-md border border-success/30 bg-success/10"
        >
          <KeyRoundIcon class="h-4 w-4 text-success" />
        </span>
        <div class="min-w-0">
          <p class="truncate font-semibold">{app.name}</p>
          <p class="truncate font-mono text-xs text-muted-foreground">{app.id}</p>
        </div>
      </div>
      <DropdownMenu>
        <!-- The trigger is the button: `mergeProps` chains our `onclick` with the menu's. -->
        <DropdownMenuTrigger
          class={cn(buttonVariants({ variant: 'ghost', size: 'icon' }), 'h-7 w-7 shrink-0')}
          onclick={(event: MouseEvent) => event.stopPropagation()}
        >
          <MoreHorizontalIcon class="h-4 w-4" />
          <!-- An icon-only button: this is its name. -->
          <span class="sr-only">{t(appsMessages.appActions)}</span>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" onclick={(event: MouseEvent) => event.stopPropagation()}>
          <DropdownMenuItem onSelect={() => void copyId()}>
            <CopyIcon class="mr-2 h-4 w-4" />
            {t(appsMessages.copyId)}
          </DropdownMenuItem>
          <DropdownMenuItem
            variant="destructive"
            disabled={!canDelete}
            onSelect={() => onRequestDelete(app.id)}
          >
            <TrashIcon class="mr-2 h-4 w-4" />
            {t(appsMessages.delete)}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>

    {#if !app.isActive}
      <Badge variant="secondary" class="mt-3">{t(appsMessages.inactive)}</Badge>
    {/if}
  </CardContent>

  <div class="flex items-center justify-between border-t border-dashed px-4 py-2.5">
    <span class="text-xs text-muted-foreground">
      {t(appsMessages.created)}
      {formatDate(app.createdAt)}
    </span>
    <Button
      variant="ghost"
      size="icon"
      disabled={!canDelete}
      class="h-7 w-7 text-muted-foreground hover:text-destructive"
      onclick={event => {
        event.stopPropagation();
        onRequestDelete(app.id);
      }}
    >
      <TrashIcon class="h-4 w-4" />
      <!-- An icon-only button: this is its name. -->
      <span class="sr-only">{t(appsMessages.deleteApp)}</span>
    </Button>
  </div>
</Card>
