// src/modules/features/project/presentation/ui/ProjectHeader.tsx
import { AddProjectDialog } from '@/modules/features/project/presentation/ui/AddProjectDialog.tsx';
import { useState } from 'react';
import { Trans } from '@lingui/react/macro';
import { FeatureHeader } from '@shared/presentation/ui';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { useDeleteProject } from '@/modules/features/project/presentation/hooks/use-delete-project.ts';
import { Permission } from '@platform/authz';
import { useCan } from '@platform/authz';

interface ProjectHeaderProps {
  numberOfProjects: number;
  projectIds: string[];
}

export const ProjectHeader = ({ numberOfProjects, projectIds }: ProjectHeaderProps) => {
  const [open, setOpen] = useState(false);
  const deleteProject = useDeleteProject();
  const { headerProps } = useFeatureSelection('projects', projectIds, {
    deleteItem: id => deleteProject.mutateAsync(id),
  });

  // Creating a project is an organization-level capability; deleting one is
  // checked per project, so this only reflects the current context.
  const canCreate = useCan(Permission.CREATE_PROJECT);
  const canDelete = useCan(Permission.DELETE_PROJECT);

  return (
    <>
      <FeatureHeader
        count={numberOfProjects}
        label={<Trans>Project</Trans>}
        pluralLabel={<Trans>Projects</Trans>}
        {...headerProps}
        onNew={() => setOpen(true)}
        newLabel={<Trans>New project</Trans>}
        canNew={canCreate}
        newDeniedReason={<Trans>You don't have permission to create projects.</Trans>}
        canDelete={canDelete}
        deleteDeniedReason={<Trans>You don't have permission to delete projects.</Trans>}
      />
      <AddProjectDialog open={open} setOpen={setOpen} />
    </>
  );
};

// extensions/scylla-base/src/features/project/presentation/ui/ProjectHeader.svelte
<script lang="ts">
  import { can, Permission } from '@platform/authz';
  import { createMutation } from '@scylla/core-sdk';
  import { FeatureHeader } from '@scylla/ui';
  import { createFeatureSelection } from '@scylla/ui/state';
  import { t } from '@scylla/ui/i18n';
  import { projectMutations } from '../project.queries.ts';
  import AddProjectDialog from './AddProjectDialog.svelte';
  import { projectMessages } from './project.messages.ts';

  interface Props {
    numberOfProjects: number;
    projectIds: string[];
  }

  let { numberOfProjects, projectIds }: Props = $props();

  let open = $state(false);

  const deleteProject = createMutation(() => projectMutations.remove());

  const selection = createFeatureSelection('projects', () => projectIds, {
    deleteItem: id => deleteProject.mutateAsync(id),
  });

  // Creating is an organization capability; deleting is checked per project.
  const canCreate = $derived(can(Permission.CREATE_PROJECT));
  const canDelete = $derived(can(Permission.DELETE_PROJECT));
</script>

<FeatureHeader
  count={numberOfProjects}
  label={t(projectMessages.project)}
  pluralLabel={t(projectMessages.projects)}
  {...selection.headerProps}
  onNew={() => (open = true)}
  newLabel={t(projectMessages.newProject)}
  canNew={canCreate}
  newDeniedReason={t(projectMessages.createDenied)}
  {canDelete}
  deleteDeniedReason={t(projectMessages.deleteDenied)}
/>
<AddProjectDialog {open} setOpen={next => (open = next)} />
