// src/modules/features/triggers/presentation/ui/Triggers.page.tsx
import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { Trans } from '@lingui/react/macro';
import { ErrorState } from '@/modules/shared/presentation/ui/feedback/ErrorState.tsx';
import { SecretRevealDialog } from '@shared/presentation/ui';
import { useContextStore } from '@platform/context';
import { usePipelineTriggers } from '@/modules/features/triggers/presentation/hooks/use-pipeline-triggers.ts';
import {
  TriggersHeader,
  TriggersOverview,
} from '@/modules/features/triggers/presentation/ui/components/index.ts';
import { TriggersTable } from '@/modules/features/triggers/presentation/ui/triggers-table/index.ts';
import { TriggerFormDialog } from '@/modules/features/triggers/presentation/ui/dialogs/TriggerFormDialog.tsx';
import type { CreatedTrigger } from '@/modules/features/triggers/domain/entities/trigger.entity.ts';

interface RevealedSecret {
  id: string;
  name: string;
  secret: string;
}

export const TriggersPage = () => {
  const { pipelineId, projectId } = useParams<{ pipelineId: string; projectId: string }>();
  const pipelineName = useContextStore(state => state.pipeline?.name) ?? '';

  const { triggers, isLoading, isError, error } = usePipelineTriggers(pipelineId ?? '');

  const [isCreateOpen, setCreateOpen] = useState(false);
  const [revealed, setRevealed] = useState<RevealedSecret | null>(null);

  if (!pipelineId || !projectId) {
    return <ErrorState message={<Trans>Pipeline ID is missing</Trans>} />;
  }
  if (isLoading) {
    return <></>;
  }
  if (isError) {
    return <ErrorState message={error?.userMessage() ?? 'Unable to load triggers'} />;
  }

  const handleCreated = (created: CreatedTrigger) => {
    // Webhook secret is returned exactly once — reveal it now or it's lost.
    if (created.webhookSecret) {
      setRevealed({
        id: created.trigger.id,
        name: created.trigger.name,
        secret: created.webhookSecret,
      });
    }
  };

  return (
    <div className='flex flex-col gap-4 w-full min-h-full'>
      <TriggersHeader
        count={triggers.length}
        triggerIds={triggers.map(trigger => trigger.id)}
        pipelineId={pipelineId}
        onNew={() => setCreateOpen(true)}
      />

      {triggers.length > 0 && <TriggersOverview triggers={triggers} />}

      <div className='overflow-hidden'>
        {triggers.length > 0 ? (
          <TriggersTable triggers={triggers} pipelineId={pipelineId} pipelineName={pipelineName} />
        ) : (
          <div className='flex items-center justify-center min-h-[300px]'>
            <div className='text-center space-y-2'>
              <p className='text-muted-foreground'>
                <Trans>No triggers yet</Trans>
              </p>
              <p className='text-sm text-muted-foreground'>
                <Trans>Add a cron schedule or webhook to start runs automatically.</Trans>
              </p>
            </div>
          </div>
        )}
      </div>

      <TriggerFormDialog
        open={isCreateOpen}
        onOpenChange={setCreateOpen}
        pipelineId={pipelineId}
        onCreated={handleCreated}
      />

      {revealed && (
        <SecretRevealDialog
          open={true}
          title={<Trans>{revealed.name} webhook secret</Trans>}
          description={<Trans>Copy the secret below — it is shown only once.</Trans>}
          secret={revealed.secret}
          secretLabel={`Secret`}
          revealedNote={
            <Trans>Add this signing secret to your webhook sender's HMAC configuration.</Trans>
          }
          onClose={() => setRevealed(null)}
        />
      )}
    </div>
  );
};

export default TriggersPage;

// extensions/scylla-base/src/features/triggers/presentation/ui/Triggers/Triggers.page.svelte
<script lang="ts">
  import { contextStore } from '@platform/context';
  import { createQuery } from '@scylla/core-sdk';
  import { ErrorState, SecretRevealDialog } from '@scylla/ui';
  import { toRune } from '@scylla/ui/stores';
  import { ScyllaError } from '@shared/utils/scylla-result.ts';
  import { t } from '@scylla/ui/i18n';
  import type { CreatedTrigger } from '../../../domain/entities/trigger.entity.ts';
  import { triggerQueries } from '../../triggers.queries.ts';
  import TriggersHeader from '../components/TriggersHeader/TriggersHeader.svelte';
  import TriggersOverview from '../components/TriggersOverview/TriggersOverview.svelte';
  import TriggerFormDialog from '../dialogs/TriggerFormDialog/TriggerFormDialog.svelte';
  import TriggersTable from '../triggers-table/TriggersTable.svelte';
  import { triggersMessages } from '../triggers.messages.ts';

  interface Props {
    pipelineId?: string;
    projectId?: string;
  }

  let { pipelineId, projectId }: Props = $props();

  const context = toRune(contextStore);
  const pipelineName = $derived(context().pipeline?.name ?? '');

  const triggersQuery = createQuery(() => triggerQueries.byPipeline(pipelineId ?? ''));
  const triggers = $derived(triggersQuery.data ?? []);

  let isCreateOpen = $state(false);
  /** Held only while the dialog shows it. */
  let revealed = $state<{ id: string; name: string; secret: string } | null>(null);

  const errorMessage = $derived(
    triggersQuery.error instanceof ScyllaError
      ? triggersQuery.error.userMessage()
      : t(triggersMessages.loadError),
  );

  const handleCreated = (created: CreatedTrigger) => {
    // Returned only once: reveal it now.
    if (!created.webhookSecret) return;

    revealed = {
      id: created.trigger.id,
      name: created.trigger.name,
      secret: created.webhookSecret,
    };
  };
</script>

{#if !pipelineId || !projectId}
  <ErrorState message={t(triggersMessages.pipelineIdMissing)} />
{:else if triggersQuery.isLoading}
  <!-- Nothing: a skeleton of the list would be the page itself. -->
{:else if triggersQuery.isError}
  <ErrorState message={errorMessage} />
{:else}
  <div class="flex flex-col gap-4 w-full min-h-full">
    <TriggersHeader
      count={triggers.length}
      triggerIds={triggers.map(trigger => trigger.id)}
      {pipelineId}
      onNew={() => (isCreateOpen = true)}
    />

    {#if triggers.length > 0}
      <TriggersOverview {triggers} />
    {/if}

    <div class="overflow-hidden">
      {#if triggers.length > 0}
        <TriggersTable {triggers} {pipelineId} {pipelineName} />
      {:else}
        <div class="flex items-center justify-center min-h-[300px]">
          <div class="text-center space-y-2">
            <p class="text-muted-foreground">{t(triggersMessages.noTriggersYet)}</p>
            <p class="text-sm text-muted-foreground">{t(triggersMessages.noTriggersBody)}</p>
          </div>
        </div>
      {/if}
    </div>

    <TriggerFormDialog
      open={isCreateOpen}
      onOpenChange={open => (isCreateOpen = open)}
      {pipelineId}
      onCreated={handleCreated}
    />

    {#if revealed}
      <SecretRevealDialog
        open
        title={t(triggersMessages.webhookSecretOf(revealed.name))}
        description={t(triggersMessages.copySecretOnce)}
        secret={revealed.secret}
        secretLabel="Secret"
        revealedNote={t(triggersMessages.addSigningSecret)}
        onClose={() => (revealed = null)}
      />
    {/if}
  </div>
{/if}
