// src/modules/features/apps/presentation/ui/Apps.page.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApps } from '@/modules/features/apps/presentation/hooks/use-apps.ts';
import { createAppItems } from '@/modules/features/apps/presentation/utils/create-app-form-items.ts';
import { AppCard } from '@/modules/features/apps/presentation/ui/components/AppCard.tsx';
import type { CreatedApp } from '@/modules/features/apps/domain/structs/app.struct.ts';
import { FeatureHeader, FormDialog, SecretRevealDialog } from '@shared/presentation/ui';
import { ErrorState } from '@shared/presentation/ui/feedback/ErrorState.tsx';
import { Card } from '@shadcn';
import { Skeleton } from '@shadcn/skeleton.tsx';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@shadcn/alert-dialog.tsx';
import type { FormValues } from '@shared/presentation/structs/scylla-form.struct.ts';
import { KeyRound, Plus } from 'lucide-react';
import { Trans } from '@lingui/react/macro';
import { Permission, PermissionButton, useCan } from '@platform/authz';

export const AppsPage = () => {
  const { apps, isLoading, isError, createApp, deleteApp } = useApps();
  const navigate = useNavigate();
  const [createOpen, setCreateOpen] = useState(false);
  const [created, setCreated] = useState<CreatedApp | null>(null);
  const [toDelete, setToDelete] = useState<string | null>(null);

  const canCreate = useCan(Permission.CREATE_APP);
  const canDelete = useCan(Permission.DELETE_APP);

  const handleCreate = ({ name }: FormValues<'name'>) => {
    if (!name.trim()) return;
    createApp.mutate(name.trim(), {
      onSuccess: data => {
        setCreateOpen(false);
        setCreated(data);
      },
    });
  };

  const activeCount = apps.filter(a => a.isActive).length;

  if (isError) return <ErrorState message={<Trans>Error loading apps</Trans>} />;

  return (
    <div className='flex flex-col w-full h-full overflow-hidden'>
      <div className='px-2 pt-2'>
        <p className='mb-1 font-mono text-xs uppercase tracking-wider text-muted-foreground'>
          <Trans>Service</Trans>
        </p>
        <FeatureHeader
          count={apps.length}
          label={<Trans>App</Trans>}
          pluralLabel={<Trans>Apps</Trans>}
          onNew={() => setCreateOpen(true)}
          canNew={canCreate}
          newDeniedReason={<Trans>You don't have permission to create apps.</Trans>}
        />
        {!isLoading && (
          <p className='mt-1 font-mono text-xs text-muted-foreground'>
            {activeCount} <Trans>active</Trans> · {apps.length - activeCount}{' '}
            <Trans>inactive</Trans>
          </p>
        )}
      </div>

      {isLoading ? (
        <div className='grid gap-3 p-2 sm:grid-cols-2 lg:grid-cols-3'>
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className='h-32 w-full rounded-xl' />
          ))}
        </div>
      ) : apps.length === 0 ? (
        <div className='flex flex-1 items-center justify-center p-6'>
          <Card className='flex max-w-sm flex-col items-center gap-3 p-8 text-center'>
            <span className='flex h-14 w-14 items-center justify-center rounded-xl border border-dashed border-success/40 bg-success/5'>
              <KeyRound className='h-6 w-6 text-success' />
            </span>
            <h2 className='text-lg font-semibold'>
              <Trans>No apps yet</Trans>
            </h2>
            <p className='text-sm text-muted-foreground'>
              <Trans>
                Apps are machine credentials. Create one to let an automation authenticate against
                the Scylla API.
              </Trans>
            </p>
            <PermissionButton
              permission={Permission.CREATE_APP}
              onClick={() => setCreateOpen(true)}
              deniedReason={<Trans>You don't have permission to create apps.</Trans>}
            >
              <Trans>Create your first app</Trans>
            </PermissionButton>
          </Card>
        </div>
      ) : (
        <div className='grid gap-3 p-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3'>
          {apps.map(app => (
            <AppCard key={app.id} app={app} onRequestDelete={setToDelete} canDelete={canDelete} />
          ))}
          {/* The header already shows a disabled "New" without CREATE_APP, so
              this duplicate tile is hidden rather than disabled. */}
          {canCreate && (
            <button
              type='button'
              onClick={() => setCreateOpen(true)}
              className='flex min-h-32 items-center justify-center gap-2 rounded-xl border border-dashed text-sm text-muted-foreground transition-colors hover:bg-accent/50 hover:text-foreground'
            >
              <Plus className='h-4 w-4' />
              <Trans>New App</Trans>
            </button>
          )}
        </div>
      )}

      <FormDialog
        open={createOpen}
        onOpenChange={setCreateOpen}
        title={<Trans>New App</Trans>}
        description={<Trans>Get credentials to authenticate.</Trans>}
        items={createAppItems()}
        isPending={createApp.isPending}
        submitLabel={<Trans>Create &amp; reveal secret →</Trans>}
        onSubmit={handleCreate}
      />

      {created && (
        <SecretRevealDialog
          open={!!created}
          title={<Trans>{created.app.name} credentials</Trans>}
          description={<Trans>Copy the secret below — it is shown only once.</Trans>}
          secret={created.secret}
          secretLabel={created.app.id}
          revealedNote={
            <Trans>
              Use these credentials (id + secret) to authenticate an automation against the Scylla
              API.
            </Trans>
          }
          onClose={() => {
            const id = created.app.id;
            setCreated(null);
            void navigate(id);
          }}
        />
      )}

      <AlertDialog open={!!toDelete} onOpenChange={o => !o && setToDelete(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              <Trans>Delete app?</Trans>
            </AlertDialogTitle>
            <AlertDialogDescription>
              <Trans>This revokes the app's credentials. Cannot be undone.</Trans>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>
              <Trans>Cancel</Trans>
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (toDelete) deleteApp.mutate(toDelete);
                setToDelete(null);
              }}
            >
              <Trans>Delete</Trans>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

// extensions/scylla-base/src/features/apps/presentation/ui/Apps/Apps.page.svelte
<script lang="ts">
  import KeyRoundIcon from '@lucide/svelte/icons/key-round';
  import PlusIcon from '@lucide/svelte/icons/plus';
  import { can, Permission } from '@platform/authz';
  import { scyllaNavigate, contextStore } from '@platform/context';
  import { createMutation, createQuery } from '@scylla/core-sdk';
  import { Card, Skeleton } from '@scylla/ui/shadcn';
  import {
    ConfirmOperationAlertDialog,
    ErrorState,
    FeatureHeader,
    FormDialog,
    GatedButton,
    SecretRevealDialog,
    type FormValues,
  } from '@scylla/ui';
  import { toRune } from '@scylla/ui/stores';
  import { activeLocale, t } from '@scylla/ui/i18n';
  import type { CreatedApp } from '../../../domain/structs/app.struct.ts';
  import { appMutations, appQueries } from '../../apps.queries.ts';
  import { createAppItems } from '../../utils/create-app-form-items.ts';
  import AppCard from '../components/AppCard/AppCard.svelte';
  import { appsMessages } from '../apps.messages.ts';

  // From the context store: the organization selector writes there.
  const context = toRune(contextStore);
  const organizationId = $derived(context().organization.id ?? '');

  const appsQuery = createQuery(() => appQueries.byOrganization(organizationId));
  const createApp = createMutation(() => appMutations.create(organizationId));
  const deleteApp = createMutation(() => appMutations.remove(organizationId));

  const apps = $derived(appsQuery.data ?? []);
  const activeCount = $derived(apps.filter(app => app.isActive).length);

  let createOpen = $state(false);
  let created = $state<CreatedApp | null>(null);
  let pendingDeletion = $state<string | null>(null);

  const canCreate = $derived(can(Permission.CREATE_APP));
  const canDelete = $derived(can(Permission.DELETE_APP));

  const items = $derived((activeLocale(), createAppItems()));

  const handleCreate = ({ name }: FormValues<'name'>) => {
    if (!name.trim()) return;

    createApp.mutate(name.trim(), {
      onSuccess: data => {
        createOpen = false;
        created = data;
      },
    });
  };

  const confirmDelete = () => {
    if (pendingDeletion) deleteApp.mutate(pendingDeletion);
    pendingDeletion = null;
  };

  const openCreated = () => {
    const appId = created?.app.id;
    created = null;
    if (appId) scyllaNavigate.goToSubRoute(appId);
  };
</script>

{#if appsQuery.isError}
  <ErrorState message={t(appsMessages.loadError)} />
{:else}
  <div class="flex flex-col w-full h-full overflow-hidden">
    <div class="px-2 pt-2">
      <p class="mb-1 font-mono text-xs uppercase tracking-wider text-muted-foreground">
        {t(appsMessages.service)}
      </p>
      <FeatureHeader
        count={apps.length}
        label={t(appsMessages.app)}
        pluralLabel={t(appsMessages.apps)}
        onNew={() => (createOpen = true)}
        newLabel={t(appsMessages.newApp)}
        canNew={canCreate}
        newDeniedReason={t(appsMessages.createDenied)}
      />
      {#if !appsQuery.isLoading}
        <p class="mt-1 font-mono text-xs text-muted-foreground">
          {activeCount}
          {t(appsMessages.active)} · {apps.length - activeCount}
          {t(appsMessages.inactive)}
        </p>
      {/if}
    </div>

    {#if appsQuery.isLoading}
      <div class="grid gap-3 p-2 sm:grid-cols-2 lg:grid-cols-3">
        {#each { length: 6 } as _, index (index)}
          <Skeleton class="h-32 w-full rounded-xl" />
        {/each}
      </div>
    {:else if apps.length === 0}
      <div class="flex flex-1 items-center justify-center p-6">
        <Card class="flex max-w-sm flex-col items-center gap-3 p-8 text-center">
          <span
            class="flex h-14 w-14 items-center justify-center rounded-xl border border-dashed border-success/40 bg-success/5"
          >
            <KeyRoundIcon class="h-6 w-6 text-success" />
          </span>
          <h2 class="text-lg font-semibold">{t(appsMessages.noAppsYet)}</h2>
          <p class="text-sm text-muted-foreground">{t(appsMessages.noAppsBody)}</p>
          <GatedButton
            allowed={canCreate}
            deniedReason={t(appsMessages.createDenied)}
            onclick={() => (createOpen = true)}
          >
            {t(appsMessages.createFirstApp)}
          </GatedButton>
        </Card>
      </div>
    {:else}
      <div class="grid gap-3 p-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">
        {#each apps as app (app.id)}
          <AppCard {app} onRequestDelete={id => (pendingDeletion = id)} {canDelete} />
        {/each}
        <!-- The header already shows a disabled "New": this tile is hidden instead. -->
        {#if canCreate}
          <button
            type="button"
            onclick={() => (createOpen = true)}
            class="flex min-h-32 items-center justify-center gap-2 rounded-xl border border-dashed text-sm text-muted-foreground transition-colors hover:bg-accent/50 hover:text-foreground"
          >
            <PlusIcon class="h-4 w-4" />
            {t(appsMessages.newApp)}
          </button>
        {/if}
      </div>
    {/if}

    <FormDialog
      open={createOpen}
      onOpenChange={open => (createOpen = open)}
      title={t(appsMessages.newApp)}
      description={t(appsMessages.getCredentials)}
      {items}
      isPending={createApp.isPending}
      submitLabel={t(appsMessages.createAndReveal)}
      onSubmit={handleCreate}
    />

    {#if created}
      <SecretRevealDialog
        open
        title={t(appsMessages.credentialsOf(created.app.name))}
        description={t(appsMessages.copySecretOnce)}
        secret={created.secret}
        secretLabel={created.app.id}
        revealedNote={t(appsMessages.useTheseCredentials)}
        onClose={openCreated}
      />
    {/if}

    <ConfirmOperationAlertDialog
      open={pendingDeletion !== null}
      onOpenChange={open => {
        if (!open) pendingDeletion = null;
      }}
      onContinue={confirmDelete}
      title={t(appsMessages.deleteAppTitle)}
      description={t(appsMessages.deleteAppBody)}
    />
  </div>
{/if}
