// src/modules/features/project/presentation/ui/EditProjectDialog.svelte
<script lang="ts">
  import { createMutation } from '@platform/query';
  import {
    FormDialog,
    FormItemType,
    type FormItem,
    type FormValues,
  } from '@shared/presentation/ui';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { ProjectEntity } from '../../domain/entities/project.entity.ts';
  import { projectMutations } from '../project.queries.ts';
  import { projectMessages } from './project.messages.ts';

  interface Props {
    open: boolean;
    setOpen: (open: boolean) => void;
    project: ProjectEntity;
  }

  let { open, setOpen, project }: Props = $props();

  const updateProject = createMutation(() => projectMutations.update());

  // Prefilled: Save is enabled on an untouched form.
  const items: readonly FormItem<'name' | 'description'>[] = $derived([
    {
      id: 'name',
      label: t(projectMessages.projectName),
      placeholder: project.name,
      defaultValue: project.name,
      type: FormItemType.Input,
      inputType: 'text',
    },
    {
      id: 'description',
      label: t(projectMessages.description),
      placeholder: project.description || t(projectMessages.addDescription),
      defaultValue: project.description,
      type: FormItemType.Input,
      inputType: 'text',
    },
  ]);

  const handleSubmit = ({ name, description }: FormValues<'name' | 'description'>) => {
    updateProject.mutate(
      {
        projectId: project.id,
        name: name.trim() || undefined,
        description: description.trim() || undefined,
      },
      { onSuccess: () => setOpen(false) },
    );
  };
</script>

<FormDialog
  {open}
  onOpenChange={setOpen}
  title={t(projectMessages.editTitle)}
  description={t(projectMessages.editDescription)}
  {items}
  isPending={updateProject.isPending}
  submitLabel={t(projectMessages.save)}
  pendingLabel={t(projectMessages.saving)}
  onSubmit={handleSubmit}
/>

// src/modules/features/project/presentation/ui/EditProjectDialog.tsx
import { Trans, useLingui } from '@lingui/react/macro';
import { FormDialog } from '@shared/presentation/ui';
import {
  type FormItem,
  FormItemType,
  type FormValues,
} from '@shared/presentation/structs/scylla-form.struct.ts';
import { useUpdateProject } from '@/modules/features/project/presentation/hooks/use-update-project.ts';
import type { ProjectEntity } from '@/modules/features/project/domain/entities/project.entity.ts';

interface EditProjectDialogProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  project: ProjectEntity;
}

export function EditProjectDialog({ open, setOpen, project }: EditProjectDialogProps) {
  const { t } = useLingui();
  const updateProject = useUpdateProject();

  const items: readonly FormItem<'name' | 'description'>[] = [
    {
      id: 'name',
      label: t`Project name`,
      placeholder: project.name,
      type: FormItemType.Input,
      defaultValue: project.name,
      inputType: 'text',
    },
    {
      id: 'description',
      label: t`Description`,
      placeholder: project.description || t`Add a description...`,
      defaultValue: project.description,
      type: FormItemType.Input,
      inputType: 'text',
    },
  ];

  const handleSubmit = ({ name, description }: FormValues<'name' | 'description'>) => {
    updateProject.mutate(
      {
        projectId: project.id,
        name: name.trim() || undefined,
        description: description.trim() || undefined,
      },
      { onSuccess: () => setOpen(false) },
    );
  };

  return (
    <FormDialog
      open={open}
      onOpenChange={setOpen}
      title={<Trans>Edit project</Trans>}
      description={<Trans>Update the project name and description.</Trans>}
      items={items}
      isPending={updateProject.isPending}
      submitLabel={<Trans>Save</Trans>}
      pendingLabel={<Trans>Saving...</Trans>}
      onSubmit={handleSubmit}
    />
  );
}
