// src/modules/features/project/presentation/ui/ProjectPage.tsx
import { useProjects } from '@/modules/features/project/presentation/hooks/useProjects.ts';
import ProjectCard from '@/modules/features/project/presentation/ui/ProjectCard.tsx';
import { ProjectHeader } from '@/modules/features/project/presentation/ui/ProjectHeader.tsx';
import { useContextStore } from '@shared/presentation/stores/use-context.store.ts';
import { Pagination } from '@/modules/shared/presentation/ui/Pagination.tsx';
import { ErrorState } from '@/modules/shared/presentation/ui/ErrorState.tsx';
import { Trans } from '@lingui/react/macro';

export const ProjectPage = () => {
  const organizationId = useContextStore(state => state.organization.id);
  const { projects, isLoading, isError, paginationInfo, setPage } = useProjects(organizationId);

  if (!organizationId) {
    return (
      <div className='flex items-center justify-center h-full'>
        <div className='text-center space-y-2'>
          <p className='text-muted-foreground text-lg font-semibold'>
            <Trans>No organization selected</Trans>
          </p>
          <p className='text-sm text-muted-foreground'>
            <Trans>Select an organization from the sidebar to view its projects</Trans>
          </p>
        </div>
      </div>
    );
  }

  if (isLoading) {
    return <></>;
  }

  if (isError || !projects) {
    return <ErrorState message='Unable to load projects' />;
  }

  return (
    <div className='flex flex-col gap-4 w-full min-h-full p-2'>
      <ProjectHeader numberOfProjects={paginationInfo?.totalCount ?? projects.length} />
      <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4'>
        {projects.map(project => (
          <ProjectCard key={project.id} project={project} />
        ))}
      </div>
      {paginationInfo && paginationInfo.totalPages > 1 && (
        <Pagination paginationInfo={paginationInfo} onPageChange={setPage} className='pb-2' />
      )}
    </div>
  );
};

export default ProjectPage;

// src/modules/features/project/presentation/ui/Project.page.svelte
<script lang="ts">
  import { contextStore } from '@platform/context';
  import { toRune } from '@shared/presentation/stores/to-rune.svelte.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import ProjectList from './ProjectList.svelte';
  import { projectMessages } from './project.messages.ts';

  const context = toRune(contextStore);
  const organizationId = $derived(context().organization.id);
</script>

{#if !organizationId}
  <div class="flex h-full items-center justify-center">
    <div class="space-y-2 text-center">
      <p class="text-lg font-semibold text-muted-foreground">
        {t(projectMessages.noOrganization)}
      </p>
      <p class="text-sm text-muted-foreground">{t(projectMessages.noOrganizationHint)}</p>
    </div>
  </div>
{:else}
  <!-- Keyed on the organization: the page number resets on a switch. -->
  {#key organizationId}
    <ProjectList {organizationId} />
  {/key}
{/if}
