// extensions/scylla-base/src/features/project/presentation/ui/ProjectCard/ProjectCard.svelte
<script lang="ts">
  import FolderIcon from '@lucide/svelte/icons/folder';
  import PencilIcon from '@lucide/svelte/icons/pencil';
  import { can, Permission } from '@platform/authz';
  import { scyllaNavigate } from '@platform/context';
  import {
    Card,
    CardContent,
    CardHeader,
    CardTitle,
    Checkbox,
    Tooltip,
    TooltipContent,
    TooltipTrigger,
  } from '@scylla/ui/shadcn';
  import { IconButton } from '@scylla/ui';
  import { createSelection } from '@scylla/ui/state';
  import { cn } from '@scylla/ui/utils';
  import { t } from '@scylla/ui/i18n';
  import type { ProjectEntity } from '../../../domain/entities/project.entity.ts';
  import EditProjectDialog from '../EditProjectDialog.svelte';
  import { projectMessages } from '../project.messages.ts';

  interface Props {
    project: ProjectEntity;
  }

  let { project }: Props = $props();

  const selection = createSelection('projects');
  const isSelected = $derived(selection.selectedIds.includes(project.id));

  let editOpen = $state(false);
</script>

<Card
  onclick={() => scyllaNavigate.goToProject(project.id, project.name)}
  class={cn(
    'group flex h-full cursor-pointer flex-col transition-all duration-200 hover:border-primary/50 hover:shadow-lg active:scale-[0.98]',
    isSelected && 'border-primary ring-2 ring-primary',
  )}
>
  <CardHeader class="pb-2">
    <div class="flex items-start justify-between gap-2">
      <div class="flex min-w-0 flex-1 items-center gap-3">
        <div class="shrink-0 rounded-lg bg-primary/10 p-2 transition-colors group-hover:bg-primary/20">
          <FolderIcon class="h-5 w-5 text-primary" />
        </div>
        <CardTitle class="min-w-0 truncate text-base font-semibold" title={project.name}>
          {project.name}
        </CardTitle>
      </div>
      <div class="flex shrink-0 flex-row items-center gap-1">
        {#if can(Permission.UPDATE_PROJECT, { projectId: project.id })}
          <IconButton
            icon={PencilIcon}
            tooltip={t(projectMessages.edit)}
            onclick={event => {
              event.stopPropagation();
              editOpen = true;
            }}
            class="h-7 w-7 sm:opacity-0 sm:group-hover:opacity-100 sm:focus-visible:opacity-100"
            iconClass="h-3.5 w-3.5"
          />
        {/if}
        <Tooltip>
          <TooltipTrigger>
            {#snippet child({ props })}
              <span {...props} class="mr-2">
                <Checkbox
                  checked={isSelected}
                  class="cursor-pointer transition-all hover:scale-125 hover:border-primary"
                  onclick={event => event.stopPropagation()}
                  onCheckedChange={() => selection.select(project.id)}
                />
              </span>
            {/snippet}
          </TooltipTrigger>
          <TooltipContent>
            <p>{t(projectMessages.select)}</p>
          </TooltipContent>
        </Tooltip>
      </div>
    </div>
  </CardHeader>

  <CardContent class="flex-1 pt-0">
    <p class="line-clamp-2 text-sm text-muted-foreground">
      {#if project.description}
        {project.description}
      {:else}
        <span class="italic">{t(projectMessages.noDescription)}</span>
      {/if}
    </p>
  </CardContent>
</Card>

<EditProjectDialog open={editOpen} setOpen={open => (editOpen = open)} {project} />

// src/modules/features/project/presentation/ui/ProjectCard.tsx
import { Card, CardContent, CardHeader, CardTitle } from '@shadcn';
import { Folder, Pencil } from 'lucide-react';
import { useScyllaNavigate } from '@shared/presentation/hooks/use-scylla-navigate.ts';
import { Trans } from '@lingui/react/macro';
import type { ProjectEntity } from '@/modules/features/project/domain/entities/project.entity.ts';
import { useSelection } from '@shared/presentation/hooks/use-selection.ts';
import { EditProjectDialog } from '@/modules/features/project/presentation/ui/EditProjectDialog.tsx';
import { useState } from 'react';
import { cn } from '@shared/presentation/utils';
import { Checkbox } from '@shadcn/checkbox.tsx';
import { Tooltip, TooltipContent, TooltipTrigger } from '@shadcn/tooltip.tsx';
import { IconButton } from '@shared/presentation/ui';

type ProjectCardProps = {
  project: ProjectEntity;
};

export const ProjectCard = ({ project }: ProjectCardProps) => {
  const navigate = useScyllaNavigate();
  const { selectedIds, select } = useSelection('projects');
  const isSelected = selectedIds.includes(project.id);
  const [editOpen, setEditOpen] = useState(false);

  return (
    <>
      <Card
        onClick={() => navigate.goToProject(project)}
        className={cn(
          'group cursor-pointer transition-all duration-200 hover:shadow-lg hover:border-primary/50 active:scale-[0.98] h-full flex flex-col',
          isSelected && 'ring-2 ring-primary border-primary',
        )}
      >
        <CardHeader className='pb-2 overflow-hidden'>
          <div className='flex items-start justify-between gap-2 overflow-hidden'>
            <div className='flex items-center gap-3 min-w-0 flex-1 overflow-hidden'>
              <div className='rounded-lg bg-primary/10 p-2 group-hover:bg-primary/20 transition-colors shrink-0'>
                <Folder className='h-5 w-5 text-primary' />
              </div>
              <CardTitle className='text-base font-semibold truncate min-w-0' title={project.name}>
                {project.name}
              </CardTitle>
            </div>
            <div className='flex flex-row items-center gap-1 shrink-0'>
              <IconButton
                icon={Pencil}
                tooltip={<Trans>Edit</Trans>}
                onClick={e => {
                  e.stopPropagation();
                  setEditOpen(true);
                }}
                className='h-7 w-7 opacity-0 group-hover:opacity-100'
                iconClassName='h-3.5 w-3.5'
              />
              <Tooltip>
                <TooltipTrigger asChild>
                  <span className={'mr-2'}>
                    <Checkbox
                      checked={isSelected}
                      className='transition-all cursor-pointer hover:scale-125 hover:border-primary'
                      onClick={e => e.stopPropagation()}
                      onCheckedChange={() => select(project.id)}
                    />
                  </span>
                </TooltipTrigger>
                <TooltipContent>
                  <p>
                    <Trans>Select</Trans>
                  </p>
                </TooltipContent>
              </Tooltip>
            </div>
          </div>
        </CardHeader>

        <CardContent className='flex-1 pt-0'>
          <p className='text-sm text-muted-foreground line-clamp-2'>
            {project.description || (
              <span className='italic'>
                <Trans>No description</Trans>
              </span>
            )}
          </p>
        </CardContent>
      </Card>
      <EditProjectDialog open={editOpen} setOpen={setEditOpen} project={project} />
    </>
  );
};

export default ProjectCard;
