// src/modules/features/apps/presentation/ui/AppDetails.page.tsx
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useApp, useApps } from '@/modules/features/apps/presentation/hooks/use-apps.ts';
import { AppSecretsCard } from '@/modules/features/apps/presentation/ui/components/AppSecretsCard.tsx';
import { ErrorState } from '@shared/presentation/ui/feedback/ErrorState.tsx';
import { useResourceError } from '@shared/presentation/hooks/use-resource-error.ts';
import { Badge, Button, Card, CardContent } from '@shadcn';
import { Skeleton } from '@shadcn/skeleton.tsx';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@shadcn/alert-dialog.tsx';
import { CodeSnippet } from '@shadcn/code-snippet.tsx';
import { Switch } from '@shadcn/switch.tsx';
import { KeyRound } from 'lucide-react';
import { formatDate } from '@shared/utils/date-utils.ts';
import { Trans, useLingui } from '@lingui/react/macro';
import { useLingui as useLinguiRuntime } from '@lingui/react';
import { ToastMessages } from '@shared/utils/toast-messages.ts';

const Label = ({ children }: { children: React.ReactNode }) => (
  <dt className='font-mono text-[11px] uppercase tracking-wide text-muted-foreground'>{children}</dt>
);

export const AppDetailsPage = () => {
  const { t } = useLingui();
  const { _ } = useLinguiRuntime();
  const { appId } = useParams<{ appId: string }>();
  const navigate = useNavigate();
  const { data: app, isLoading, isError, error } = useApp(appId ?? '');
  const { deleteApp, setAppActive } = useApps();
  const [confirmDelete, setConfirmDelete] = useState(false);

  // NOT_FOUND (deleted / bad id) → toast + back to the apps list.
  const { redirecting } = useResourceError({
    error,
    redirectTo: '..',
    notFoundMessage: t`App not found`,
  });

  if (redirecting) return null;
  if (isLoading) return <Skeleton className='m-4 h-64 rounded-xl' />;
  if (isError || !app) return <ErrorState message={<Trans>Error loading app</Trans>} />;

  return (
    <div className='space-y-4 p-4'>
      <div className='flex items-start justify-between gap-3'>
        <div className='flex items-center gap-3'>
          <span className='flex h-12 w-12 items-center justify-center rounded-lg border border-success/30 bg-success/10'>
            <KeyRound className='h-6 w-6 text-success' />
          </span>
          <div>
            <div className='flex items-center gap-2'>
              <h1 className='text-xl font-semibold'>{app.name}</h1>
              <Badge variant={app.isActive ? 'default' : 'secondary'}>
                {app.isActive ? <Trans>active</Trans> : <Trans>inactive</Trans>}
              </Badge>
            </div>
            <p className='text-sm text-muted-foreground'>
              <Trans>Machine credential · no runtime presence</Trans>
            </p>
          </div>
        </div>
        <div className='flex items-center gap-3'>
          <label className='flex items-center gap-2 text-sm text-muted-foreground'>
            <Switch
              checked={app.isActive}
              disabled={setAppActive.isPending}
              onCheckedChange={active => setAppActive.mutate({ appId: app.id, active })}
              aria-label={t`Toggle app active`}
            />
            {app.isActive ? <Trans>active</Trans> : <Trans>inactive</Trans>}
          </label>
          <Button variant='outline' disabled title={t`Coming soon`}>
            <Trans>Rename</Trans>
          </Button>
          <Button variant='destructive' onClick={() => setConfirmDelete(true)}>
            <Trans>Delete</Trans>
          </Button>
        </div>
      </div>

      <Card>
        <CardContent className='p-5'>
          <dl className='grid gap-4 sm:grid-cols-2'>
            <div className='sm:col-span-2'>
              <dd className='mt-1'>
                <CodeSnippet
                  multiline
                  value={app.id}
                  label={<Trans>App ID</Trans>}
                  copyToast={_(ToastMessages.APP_ID_COPIED)}
                />
              </dd>
            </div>
            <div>
              <Label>
                <Trans>Name</Trans>
              </Label>
              <dd className='mt-1'>{app.name}</dd>
            </div>
            <div>
              <Label>
                <Trans>Status</Trans>
              </Label>
              <dd className='mt-1'>
                <Badge variant={app.isActive ? 'default' : 'secondary'}>
                  {app.isActive ? <Trans>active</Trans> : <Trans>inactive</Trans>}
                </Badge>
              </dd>
            </div>
            <div>
              <Label>
                <Trans context='date-prefix'>Created</Trans>
              </Label>
              <dd className='mt-1'>{formatDate(app.createdAt)}</dd>
            </div>
            <div>
              <Label>
                <Trans context='date-prefix'>Updated</Trans>
              </Label>
              <dd className='mt-1'>{formatDate(app.updatedAt)}</dd>
            </div>
          </dl>

          <div className='mt-5 rounded-md border-l-2 border-success bg-success/5 p-3 text-sm text-muted-foreground'>
            <Trans>
              Apps are credentials, not processes. There's nothing to monitor here — no
              online/offline, no runs. If you need observability, create an Agent instead.
            </Trans>
          </div>
        </CardContent>
      </Card>

      <AppSecretsCard app={app} />

      <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              <Trans>Delete app?</Trans>
            </AlertDialogTitle>
            <AlertDialogDescription>
              <Trans>This revokes the app's credentials. Cannot be undone.</Trans>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>
              <Trans>Cancel</Trans>
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                deleteApp.mutate(app.id, { onSuccess: () => void navigate('..') });
                setConfirmDelete(false);
              }}
            >
              <Trans>Delete</Trans>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

// src/modules/features/apps/presentation/ui/AppDetails/AppDetails.page.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import KeyRoundIcon from '@lucide/svelte/icons/key-round';
  import { i18n } from '@lingui/core';
  import { createResourceError, scyllaNavigate, contextStore } from '@platform/context';
  import { createMutation, createQuery } from '@platform/query';
  import { Badge, Button, Card, CardContent, CodeSnippet, Skeleton, Switch } from '@shadcn';
  import { ConfirmOperationAlertDialog, ErrorState } from '@shared/presentation/ui';
  import { toRune } from '@shared/presentation/stores/to-rune.svelte.ts';
  import { formatDate } from '@shared/utils/date-utils.ts';
  import { ToastMessages } from '@shared/utils/toast-messages.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { appMutations, appQueries } from '../../apps.queries.ts';
  import AppSecretsCard from '../components/AppSecretsCard.svelte';
  import { appsMessages } from '../apps.messages.ts';

  interface Props {
    appId?: string;
  }

  let { appId }: Props = $props();

  const context = toRune(contextStore);
  const organizationId = $derived(context().organization.id ?? '');

  const appQuery = createQuery(() => appQueries.byId(appId ?? ''));
  const deleteApp = createMutation(() => appMutations.remove(organizationId));
  const setAppActive = createMutation(() => appMutations.setActive(organizationId));

  const app = $derived(appQuery.data);

  const resourceError = createResourceError({
    error: () => appQuery.error,
    redirectTo: '..',
    notFoundMessage: t(appsMessages.notFound),
  });

  let confirmDelete = $state(false);

  const handleDelete = () => {
    if (!app) return;
    deleteApp.mutate(app.id, { onSuccess: () => scyllaNavigate.navigate('..') });
    confirmDelete = false;
  };
</script>

{#snippet label(children: Snippet)}
  <dt class="font-mono text-[11px] uppercase tracking-wide text-muted-foreground">
    {@render children()}
  </dt>
{/snippet}

{#snippet statusBadge(isActive: boolean)}
  <Badge variant={isActive ? 'default' : 'secondary'}>
    {isActive ? t(appsMessages.active) : t(appsMessages.inactive)}
  </Badge>
{/snippet}

{#if resourceError.redirecting}
  <!-- The redirect is in flight. -->
{:else if appQuery.isLoading}
  <Skeleton class="m-4 h-64 rounded-xl" />
{:else if appQuery.isError || !app}
  <ErrorState message={t(appsMessages.detailsLoadError)} />
{:else}
  <div class="space-y-4 p-4">
    <div class="flex items-start justify-between gap-3">
      <div class="flex items-center gap-3">
        <span
          class="flex h-12 w-12 items-center justify-center rounded-lg border border-success/30 bg-success/10"
        >
          <KeyRoundIcon class="h-6 w-6 text-success" />
        </span>
        <div>
          <div class="flex items-center gap-2">
            <h1 class="text-xl font-semibold">{app.name}</h1>
            {@render statusBadge(app.isActive)}
          </div>
          <p class="text-sm text-muted-foreground">{t(appsMessages.machineCredential)}</p>
        </div>
      </div>
      <div class="flex items-center gap-3">
        <label class="flex items-center gap-2 text-sm text-muted-foreground">
          <Switch
            checked={app.isActive}
            disabled={setAppActive.isPending}
            onCheckedChange={active => setAppActive.mutate({ appId: app.id, active })}
            aria-label={t(appsMessages.toggleActive)}
          />
          {app.isActive ? t(appsMessages.active) : t(appsMessages.inactive)}
        </label>
        <Button variant="outline" disabled title={t(appsMessages.comingSoon)}>
          {t(appsMessages.rename)}
        </Button>
        <Button variant="destructive" onclick={() => (confirmDelete = true)}>
          {t(appsMessages.delete)}
        </Button>
      </div>
    </div>

    <Card>
      <CardContent class="p-5">
        <dl class="grid gap-4 sm:grid-cols-2">
          <div class="sm:col-span-2">
            <dd class="mt-1">
              <CodeSnippet
                multiline
                value={app.id}
                label={appIdLabel}
                copyToast={i18n._(ToastMessages.APP_ID_COPIED)}
              />
            </dd>
          </div>
          <div>
            {@render label(nameLabel)}
            <dd class="mt-1">{app.name}</dd>
          </div>
          <div>
            {@render label(statusLabel)}
            <dd class="mt-1">{@render statusBadge(app.isActive)}</dd>
          </div>
          <div>
            {@render label(createdLabel)}
            <dd class="mt-1">{formatDate(app.createdAt)}</dd>
          </div>
          <div>
            {@render label(updatedLabel)}
            <dd class="mt-1">{formatDate(app.updatedAt)}</dd>
          </div>
        </dl>

        <div
          class="mt-5 rounded-md border-l-2 border-success bg-success/5 p-3 text-sm text-muted-foreground"
        >
          {t(appsMessages.notProcesses)}
        </div>
      </CardContent>
    </Card>

    <AppSecretsCard {app} />

    <ConfirmOperationAlertDialog
      open={confirmDelete}
      onOpenChange={open => (confirmDelete = open)}
      onContinue={handleDelete}
      title={t(appsMessages.deleteAppTitle)}
      description={t(appsMessages.deleteAppBody)}
    />
  </div>
{/if}

{#snippet appIdLabel()}{t(appsMessages.appId)}{/snippet}
{#snippet nameLabel()}{t(appsMessages.name)}{/snippet}
{#snippet statusLabel()}{t(appsMessages.status)}{/snippet}
{#snippet createdLabel()}{t(appsMessages.createdOn)}{/snippet}
{#snippet updatedLabel()}{t(appsMessages.updatedOn)}{/snippet}
