// src/modules/features/login/presentation/ui/LoginForm.tsx
import { Trans, useLingui } from '@lingui/react/macro';
import { Button } from '@/modules/shared/presentation/ui/shadcn';
import { ScyllaForm } from '@shared/presentation/ui/forms/ScyllaForm.tsx';
import { FormItemType } from '@shared/presentation/structs/scylla-form.struct.ts';
import { useMemo } from 'react';

type LoginFormProps = {
  handleSubmit: (login: string, password: string) => void;
  isPending?: boolean;
};

export const LoginForm = ({ handleSubmit, isPending = false }: LoginFormProps) => {
  const { t } = useLingui();

  // `as const` keeps the ids literal, which is what types the submitted values.
  const formItems = useMemo(
    () =>
      [
        {
          id: 'username',
          label: <Trans>Username</Trans>,
          placeholder: t`username`,
          type: FormItemType.Input,
          inputType: 'text',
        },
        {
          id: 'password',
          label: <Trans>Password</Trans>,
          placeholder: t`••••••••`,
          type: FormItemType.Input,
          inputType: 'password',
        },
      ] as const,
    [t],
  );

  return (
    <ScyllaForm
      items={formItems}
      className='gap-4'
      onSubmit={values => handleSubmit(values.username, values.password)}
      isPending={isPending}
      footer={({ isValid, isPending }) => (
        <Button type='submit' className='mt-2 w-full' disabled={!isValid || isPending}>
          <Trans>Login</Trans>
        </Button>
      )}
    />
  );
};

// src/modules/features/login/presentation/ui/LoginForm/LoginForm.svelte
<script lang="ts">
  import { Button } from '@shadcn';
  import { ScyllaForm, FormItemType, type FormItem } from '@shared/presentation/ui';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { loginMessages } from '../login.messages.ts';

  interface Props {
    handleSubmit: (login: string, password: string) => void;
    isPending?: boolean;
  }

  let { handleSubmit, isPending = false }: Props = $props();

  const items: readonly FormItem<'username' | 'password'>[] = $derived([
    {
      id: 'username',
      label: t(loginMessages.username),
      placeholder: t(loginMessages.usernamePlaceholder),
      type: FormItemType.Input,
      inputType: 'text',
    },
    {
      id: 'password',
      label: t(loginMessages.password),
      placeholder: t(loginMessages.passwordPlaceholder),
      type: FormItemType.Input,
      inputType: 'password',
    },
  ]);
</script>

<ScyllaForm
  {items}
  class="gap-4"
  onSubmit={values => handleSubmit(values.username, values.password)}
  {isPending}
>
  {#snippet footer({ isValid, isPending: pending })}
    <Button type="submit" class="mt-2 w-full" disabled={!isValid || pending}>
      {t(loginMessages.submit)}
    </Button>
  {/snippet}
</ScyllaForm>
