// extensions/scylla-base/src/features/agents/presentation/ui/Agents/Agents.page.svelte
<script lang="ts">
  import CpuIcon from '@lucide/svelte/icons/cpu';
  import PlusIcon from '@lucide/svelte/icons/plus';
  import { can, Permission } from '@platform/authz';
  import { scyllaNavigate, contextStore } from '@platform/context';
  import { createMutation, createQuery } from '@scylla/core-sdk';
  import { Button, Card, Skeleton } from '@scylla/ui/shadcn';
  import {
    ConfirmOperationAlertDialog,
    ErrorState,
    FeatureHeader,
    FormDialog,
    SecretRevealDialog,
    type FormValues,
  } from '@scylla/ui';
  import { AgentRunInstructions } from '@shared/presentation/ui';
  import { toRune } from '@scylla/ui/stores';
  import { activeLocale, t } from '@scylla/ui/i18n';
  import type { CreatedAgent } from '../../../domain/structs/agent.struct.ts';
  import { agentMutations, agentQueries } from '../../agents.queries.ts';
  import { createAgentItems } from '../../utils/create-agent-form-items.ts';
  import AgentCard from '../components/AgentCard/AgentCard.svelte';
  import { agentsMessages } from '../agents.messages.ts';

  const context = toRune(contextStore);
  const organizationId = $derived(context().organization.id ?? '');

  const agentsQuery = createQuery(() => agentQueries.byOrganization(organizationId));
  const createAgent = createMutation(() => agentMutations.create(organizationId));
  const deleteAgent = createMutation(() => agentMutations.remove(organizationId));

  const agents = $derived(agentsQuery.data ?? []);
  const onlineCount = $derived(agents.filter(agent => agent.connected).length);

  const canCreate = $derived(can(Permission.CREATE_AGENT));

  let createOpen = $state(false);
  /** Held only while the dialog shows it. */
  let created = $state<CreatedAgent | null>(null);
  let pendingDeletion = $state<string | null>(null);

  const items = $derived((activeLocale(), createAgentItems()));

  const handleCreate = ({ name }: FormValues<'name'>) => {
    if (!name.trim()) return;

    // On error the dialog stays open; the global handler toasts.
    createAgent.mutate(name.trim(), {
      onSuccess: data => {
        createOpen = false;
        created = data;
      },
    });
  };

  const confirmDelete = () => {
    if (pendingDeletion) deleteAgent.mutate(pendingDeletion);
    pendingDeletion = null;
  };

  const openCreated = () => {
    const agentId = created?.agent.id;
    created = null;
    if (agentId) scyllaNavigate.goToSubRoute(agentId);
  };
</script>

{#snippet onlineSummary()}
  {#if !agentsQuery.isLoading && agents.length > 0}
    <p class="mt-1 flex items-center gap-3 font-mono text-xs text-muted-foreground">
      <span class="flex items-center gap-1.5">
        <span class="h-2 w-2 rounded-full bg-success"></span>
        {onlineCount}
        {t(agentsMessages.online)}
      </span>
      <span class="flex items-center gap-1.5">
        <span class="h-2 w-2 rounded-full bg-destructive"></span>
        {agents.length - onlineCount}
        {t(agentsMessages.offline)}
      </span>
    </p>
  {/if}
{/snippet}

{#snippet runInstructions()}
  {#if created}
    <AgentRunInstructions appId={created.agent.id} secret={created.secret} />
  {/if}
{/snippet}

{#if agentsQuery.isError}
  <ErrorState message={t(agentsMessages.loadError)} />
{:else}
  <div class="flex flex-col gap-4 w-full h-full">
    <FeatureHeader
      count={agents.length}
      label={t(agentsMessages.agent)}
      pluralLabel={t(agentsMessages.agents)}
      onNew={() => (createOpen = true)}
      newLabel={t(agentsMessages.newAgent)}
      canNew={canCreate}
      newDeniedReason={t(agentsMessages.createDenied)}
      underLabel={onlineSummary}
    />

    {#if agentsQuery.isLoading}
      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {#each { length: 6 } as _, index (index)}
          <Skeleton class="h-40 w-full rounded-xl" />
        {/each}
      </div>
    {:else if agents.length === 0}
      <div class="flex flex-1 items-center justify-center">
        <Card class="flex max-w-sm flex-col items-center gap-3 p-8 text-center">
          <span
            class="relative flex h-14 w-14 items-center justify-center rounded-xl border border-dashed border-muted-foreground/40 bg-muted/30"
          >
            <CpuIcon class="h-6 w-6 text-muted-foreground" />
            <span
              class="absolute -bottom-1 -right-1 h-3 w-3 rounded-full border-2 border-card bg-muted-foreground/50"
            ></span>
          </span>
          <h2 class="text-lg font-semibold">{t(agentsMessages.noAgentsConnected)}</h2>
          <p class="text-sm text-muted-foreground">{t(agentsMessages.noAgentsBody)}</p>
          {#if canCreate}
            <Button onclick={() => (createOpen = true)}>
              {t(agentsMessages.createFirstAgent)}
            </Button>
          {/if}
        </Card>
      </div>
    {:else}
      <div class="grid gap-3 p-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">
        {#each agents as agent (agent.id)}
          <AgentCard {agent} onRequestDelete={id => (pendingDeletion = id)} />
        {/each}
        {#if canCreate}
          <button
            type="button"
            onclick={() => (createOpen = true)}
            class="flex min-h-40 items-center justify-center gap-2 rounded-xl border border-dashed text-sm text-muted-foreground transition-colors hover:bg-accent/50 hover:text-foreground"
          >
            <PlusIcon class="h-4 w-4" />
            {t(agentsMessages.newAgent)}
          </button>
        {/if}
      </div>
    {/if}

    <FormDialog
      open={createOpen}
      onOpenChange={open => (createOpen = open)}
      title={t(agentsMessages.newAgent)}
      description={t(agentsMessages.getCredentials)}
      {items}
      isPending={createAgent.isPending}
      submitLabel={t(agentsMessages.createAndReveal)}
      onSubmit={handleCreate}
    />

    {#if created}
      <SecretRevealDialog
        open
        title={t(agentsMessages.agentIsReady(created.agent.name))}
        description={t(agentsMessages.twoSteps)}
        secret={created.secret}
        secretLabel={t(agentsMessages.secretForAgent)}
        secondStep={{ title: t(agentsMessages.startYourAgent), content: runInstructions }}
        onClose={openCreated}
      />
    {/if}

    <ConfirmOperationAlertDialog
      open={pendingDeletion !== null}
      onOpenChange={open => {
        if (!open) pendingDeletion = null;
      }}
      onContinue={confirmDelete}
      title={t(agentsMessages.deleteAgentTitle)}
      description={t(agentsMessages.deleteAgentBody)}
    />
  </div>
{/if}

// src/modules/features/agents/presentation/ui/Agents.page.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAgents } from '@/modules/features/agents/presentation/hooks/use-agents.ts';
import { createAgentItems } from '@/modules/features/agents/presentation/utils/create-agent-form-items.ts';
import { AgentCard } from '@/modules/features/agents/presentation/ui/components/AgentCard.tsx';
import type { CreatedAgent } from '@/modules/features/agents/domain/structs/agent.struct.ts';
import {
  AgentRunInstructions,
  FeatureHeader,
  FormDialog,
  SecretRevealDialog,
} from '@shared/presentation/ui';
import { ErrorState } from '@shared/presentation/ui/feedback/ErrorState.tsx';
import { Button, Card } from '@shadcn';
import { Skeleton } from '@shadcn/skeleton.tsx';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@shadcn/alert-dialog.tsx';
import { Cpu, Plus } from 'lucide-react';
import { Trans } from '@lingui/react/macro';
import type { FormValues } from '@shared/presentation/structs/scylla-form.struct.ts';
import { Permission, useCan } from '@platform/authz';

export const AgentsPage = () => {
  const { agents, isLoading, isError, createAgent, deleteAgent } = useAgents();
  const navigate = useNavigate();
  const canCreate = useCan(Permission.CREATE_AGENT);
  const [createOpen, setCreateOpen] = useState(false);
  const [created, setCreated] = useState<CreatedAgent | null>(null);
  const [toDelete, setToDelete] = useState<string | null>(null);

  const handleCreate = ({ name }: FormValues<'name'>) => {
    if (!name.trim()) return;
    // On error the dialog stays open so the name can be fixed in place;
    // the toast comes from the global MutationCache onError handler.
    createAgent.mutate(name.trim(), {
      onSuccess: data => {
        setCreateOpen(false);
        setCreated(data);
      },
    });
  };

  const onlineCount = agents.filter(a => a.connected).length;

  if (isError) return <ErrorState message={<Trans>Error loading agents</Trans>} />;

  return (
    <div className='flex flex-col gap-4 w-full h-full'>
      <FeatureHeader
        count={agents.length}
        label={<Trans>Agent</Trans>}
        pluralLabel={<Trans>Agents</Trans>}
        onNew={() => setCreateOpen(true)}
        canNew={canCreate}
        newDeniedReason={<Trans>You don't have permission to create agents.</Trans>}
        underLabel={
          <>
            {!isLoading && agents.length > 0 && (
              <p className='mt-1 flex items-center gap-3 font-mono text-xs text-muted-foreground'>
                <span className='flex items-center gap-1.5'>
                  <span className='h-2 w-2 rounded-full bg-success' />
                  {onlineCount} <Trans>online</Trans>
                </span>
                <span className='flex items-center gap-1.5'>
                  <span className='h-2 w-2 rounded-full bg-destructive' />
                  {agents.length - onlineCount} <Trans>offline</Trans>
                </span>
              </p>
            )}
          </>
        }
      />

      {isLoading ? (
        <div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3'>
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className='h-40 w-full rounded-xl' />
          ))}
        </div>
      ) : agents.length === 0 ? (
        <div className='flex flex-1 items-center justify-center'>
          <Card className='flex max-w-sm flex-col items-center gap-3 p-8 text-center'>
            <span className='relative flex h-14 w-14 items-center justify-center rounded-xl border border-dashed border-muted-foreground/40 bg-muted/30'>
              <Cpu className='h-6 w-6 text-muted-foreground' />
              <span className='absolute -bottom-1 -right-1 h-3 w-3 rounded-full border-2 border-card bg-muted-foreground/50' />
            </span>
            <h2 className='text-lg font-semibold'>
              <Trans>No agents connected</Trans>
            </h2>
            <p className='text-sm text-muted-foreground'>
              <Trans>
                An agent runs jobs. Create one to get credentials, then start the agent — it'll pull
                jobs and report back.
              </Trans>
            </p>
            {canCreate && (
              <Button onClick={() => setCreateOpen(true)}>
                <Trans>Create your first agent</Trans>
              </Button>
            )}
          </Card>
        </div>
      ) : (
        <div className='grid gap-3 p-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3'>
          {agents.map(agent => (
            <AgentCard key={agent.id} agent={agent} onRequestDelete={setToDelete} />
          ))}
          {canCreate && (
            <button
              type='button'
              onClick={() => setCreateOpen(true)}
              className='flex min-h-40 items-center justify-center gap-2 rounded-xl border border-dashed text-sm text-muted-foreground transition-colors hover:bg-accent/50 hover:text-foreground'
            >
              <Plus className='h-4 w-4' />
              <Trans>New Agent</Trans>
            </button>
          )}
        </div>
      )}

      <FormDialog
        open={createOpen}
        onOpenChange={setCreateOpen}
        title={<Trans>New Agent</Trans>}
        description={<Trans>Get credentials to connect an agent.</Trans>}
        items={createAgentItems()}
        isPending={createAgent.isPending}
        submitLabel={<Trans>Create &amp; reveal secret →</Trans>}
        onSubmit={handleCreate}
      />

      {created && (
        <SecretRevealDialog
          open={!!created}
          title={<Trans>{created.agent.name} is ready</Trans>}
          description={<Trans>Two steps and it picks up jobs.</Trans>}
          secret={created.secret}
          secretLabel={<Trans>Secret for the agent</Trans>}
          secondStep={{
            title: <Trans>Start your agent</Trans>,
            content: <AgentRunInstructions appId={created.agent.id} secret={created.secret} />,
          }}
          onClose={() => {
            const id = created.agent.id;
            setCreated(null);
            void navigate(id);
          }}
        />
      )}

      <AlertDialog open={!!toDelete} onOpenChange={o => !o && setToDelete(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              <Trans>Delete agent?</Trans>
            </AlertDialogTitle>
            <AlertDialogDescription>
              <Trans>This revokes the agent's grants and disconnects it. Cannot be undone.</Trans>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>
              <Trans>Cancel</Trans>
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (toDelete) deleteAgent.mutate(toDelete);
                setToDelete(null);
              }}
            >
              <Trans>Delete</Trans>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};
