// src/modules/features/jobs/presentation/ui/Jobs.page.svelte
<script lang="ts">
  import { loadNoAgentsBanner } from '@/modules/features/agents';
  import { createQuery } from '@platform/query';
  import { ErrorState, PaginationSlot } from '@shared/presentation/ui';
  import { createPagination } from '@shared/presentation/state/pagination.svelte.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { ScyllaError } from '@shared/utils/scylla-result.ts';
  import { jobQueries } from '../jobs.queries.ts';
  import JobsHeader from './JobsHeader/JobsHeader.svelte';
  import JobsTable from './jobs-table/JobsTable.svelte';
  import { jobsMessages } from './jobs.messages.ts';

  interface Props {
    /** Passed by `PipelineJobsRoute`: `pipeline` owns this route (the Run action). */
    pipelineId?: string;
    onRun?: () => Promise<void>;
  }

  let { pipelineId, onRun }: Props = $props();

  const pagination = createPagination({ responsive: true });

  const jobsQuery = createQuery(() =>
    jobQueries.byPipeline(pipelineId ?? '', pagination.paginationParams, {
      enabled: pagination.isPageSizeReady,
    }),
  );

  const jobs = $derived(jobsQuery.data?.items);

  // Clamps the page when the last row of the last page is deleted.
  $effect(() => {
    pagination.updatePaginationInfo(jobsQuery.data?.pagination);
  });

  const errorMessage = $derived(
    jobsQuery.error instanceof ScyllaError
      ? jobsQuery.error.userMessage()
      : t(jobsMessages.loadError),
  );
</script>

{#if !pipelineId}
  <ErrorState message={t(jobsMessages.pipelineIdMissing)} />
{:else if jobsQuery.isError}
  <ErrorState message={errorMessage} />
{:else}
  <!-- The frame renders first: the table area's height decides what to fetch. -->
  <div class="flex flex-col gap-4 w-full h-full min-h-0">
    <JobsHeader
      numberOfJobs={pagination.paginationInfo?.totalCount ?? jobs?.length ?? 0}
      jobIds={jobs?.map(job => job.id) ?? []}
      {pipelineId}
      onRefresh={() => void jobsQuery.refetch()}
      {onRun}
    />

    <!-- A loader from the barrel. Nothing shows until it loads: the banner is advisory. -->
    {#await loadNoAgentsBanner() then banner}
      <banner.default hasPendingJobs={jobs?.some(job => job.status === 'pending') ?? false} />
    {/await}

    <div use:pagination.measure class="flex-1 min-h-0 overflow-auto">
      <div class="relative">
        {#if jobs && jobs.length > 0}
          <JobsTable {jobs} {pipelineId} />
        {:else if jobs}
          <div class="flex items-center justify-center h-full min-h-[400px]">
            <div class="text-center space-y-2">
              <p class="text-muted-foreground">{t(jobsMessages.noJobsFound)}</p>
              <p class="text-sm text-muted-foreground">{t(jobsMessages.noJobsBody)}</p>
            </div>
          </div>
        {/if}
      </div>
    </div>

    <PaginationSlot
      paginationInfo={pagination.paginationInfo}
      onPageChange={page => pagination.setPage(page)}
    />
  </div>
{/if}

// src/modules/features/jobs/presentation/ui/Jobs.page.tsx
import { usePipelinesJobs } from '@/modules/features/jobs/presentation/hooks/use-pipelines-jobs.ts';
import { JobsHeader } from '@/modules/features/jobs/presentation/ui/JobsHeader.tsx';
import { useParams } from 'react-router-dom';
import { JobsTable } from '@/modules/features/jobs/presentation/ui/jobs-table';
import { ErrorState } from '@/modules/shared/presentation/ui/feedback/ErrorState.tsx';
import { Trans } from '@lingui/react/macro';
import { PaginationSlot } from '@shared/presentation/ui/data-display/Pagination.tsx';
import { NoAgentsBanner } from '@/modules/features/agents';

interface JobsPageProps {
  /** Passed through to {@link JobsHeader} — see the note on its `onRun` prop. */
  onRun?: () => Promise<void>;
}

export const JobsPage = ({ onRun }: JobsPageProps) => {
  const { pipelineId } = useParams<{ pipelineId: string }>();
  const { jobs, isError, errorMessage, refetch, paginationInfo, setPage, containerRef } =
    usePipelinesJobs(pipelineId || '');

  if (!pipelineId) {
    return <ErrorState message={<Trans>Pipeline ID is missing</Trans>} />;
  }

  if (isError) {
    return <ErrorState message={String(errorMessage) || 'Unable to load jobs'} />;
  }

  // The frame renders before the jobs do: the table area has to be in the DOM
  // for its height to be measured, and that height decides what to fetch.
  return (
    <div className='flex flex-col gap-4 w-full h-full min-h-0'>
      <JobsHeader
        numberOfJobs={paginationInfo?.totalCount ?? jobs?.length ?? 0}
        jobIds={jobs?.map(job => job.id) ?? []}
        pipelineId={pipelineId}
        onRefresh={() => refetch()}
        onRun={onRun}
      />
      <NoAgentsBanner hasPendingJobs={jobs?.some(job => job.status === 'pending') ?? false} />
      <div ref={containerRef} className='flex-1 min-h-0 overflow-auto'>
        <div className={'relative'}>
          {jobs && jobs.length > 0 && <JobsTable jobs={jobs} pipelineId={pipelineId} />}
          {jobs && jobs.length === 0 && (
            <div className='flex items-center justify-center h-full min-h-[400px]'>
              <div className='text-center space-y-2'>
                <p className='text-muted-foreground'>
                  <Trans>No jobs found</Trans>
                </p>
                <p className='text-sm text-muted-foreground'>
                  <Trans>Run your pipeline to create the first job</Trans>
                </p>
              </div>
            </div>
          )}
        </div>
      </div>

      <PaginationSlot paginationInfo={paginationInfo} onPageChange={setPage} />
    </div>
  );
};
