// extensions/scylla-base/src/features/organization/presentation/ui/EditOrganizationDialog/EditOrganizationDialog.svelte
<script lang="ts">
  import { createMutation } from '@scylla/core-sdk';
  import {
    FormDialog,
    FormItemType,
    type FormItem,
    type FormValues,
  } from '@scylla/ui';
  import { t } from '@scylla/ui/i18n';
  import { organizationMutations } from '../../organization.queries.ts';
  import { organizationMessages } from '../organization.messages.ts';

  interface Props {
    open: boolean;
    setOpen: (open: boolean) => void;
    organization: { id: string; name: string; description?: string };
  }

  let { open, setOpen, organization }: Props = $props();

  const updateOrganization = createMutation(() => organizationMutations.update());

  const items: readonly FormItem<'name' | 'description'>[] = $derived([
    {
      id: 'name',
      label: t(organizationMessages.organizationName),
      placeholder: organization.name,
      type: FormItemType.Input,
      inputType: 'text',
    },
    {
      id: 'description',
      label: t(organizationMessages.description),
      placeholder: organization.description || t(organizationMessages.addDescription),
      type: FormItemType.Input,
      inputType: 'text',
    },
  ]);

  // Empty means "leave it alone": placeholders, not default values.
  const handleSubmit = ({ name, description }: FormValues<'name' | 'description'>) => {
    updateOrganization.mutate(
      {
        organizationId: organization.id,
        name: name.trim() || undefined,
        description: description.trim() || undefined,
      },
      { onSuccess: () => setOpen(false) },
    );
  };
</script>

<FormDialog
  {open}
  onOpenChange={setOpen}
  title={t(organizationMessages.editTitle)}
  description={t(organizationMessages.editDescription)}
  {items}
  isPending={updateOrganization.isPending}
  submitLabel={t(organizationMessages.save)}
  pendingLabel={t(organizationMessages.saving)}
  onSubmit={handleSubmit}
/>

// src/modules/features/organization/presentation/ui/EditOrganizationDialog.tsx
import { Trans, useLingui } from '@lingui/react/macro';
import { FormDialog } from '@shared/presentation/ui';
import {
  type FormItem,
  FormItemType,
  type FormValues,
} from '@shared/presentation/structs/scylla-form.struct.ts';
import { useUpdateOrganization } from '@/modules/features/organization/presentation/hooks/use-update-organization.ts';

interface EditOrganizationDialogProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  organization: { id: string; name: string; description?: string };
}

export function EditOrganizationDialog({
  open,
  setOpen,
  organization,
}: EditOrganizationDialogProps) {
  const { t } = useLingui();
  const updateOrganization = useUpdateOrganization();

  const items: readonly FormItem<'name' | 'description'>[] = [
    {
      id: 'name',
      label: t`Organization name`,
      placeholder: organization.name,
      type: FormItemType.Input,
      inputType: 'text',
    },
    {
      id: 'description',
      label: t`Description`,
      placeholder: organization.description || t`Add a description...`,
      type: FormItemType.Input,
      inputType: 'text',
    },
  ];

  const handleSubmit = ({ name, description }: FormValues<'name' | 'description'>) => {
    updateOrganization.mutate(
      {
        organizationId: organization.id,
        name: name.trim() || undefined,
        description: description.trim() || undefined,
      },
      { onSuccess: () => setOpen(false) },
    );
  };

  return (
    <FormDialog
      open={open}
      onOpenChange={setOpen}
      title={<Trans>Edit organization</Trans>}
      description={<Trans>Update the organization name and description.</Trans>}
      items={items}
      isPending={updateOrganization.isPending}
      submitLabel={<Trans>Save</Trans>}
      pendingLabel={<Trans>Saving...</Trans>}
      onSubmit={handleSubmit}
    />
  );
}
