// extensions/scylla-base/src/features/organization/presentation/ui/OrganizationList/OrganizationList.svelte
<script lang="ts">
  import type { Component, Snippet } from 'svelte';
  import Building2Icon from '@lucide/svelte/icons/building-2';
  import PencilIcon from '@lucide/svelte/icons/pencil';
  import TrashIcon from '@lucide/svelte/icons/trash';
  import UsersIcon from '@lucide/svelte/icons/users';
  import { can, Permission } from '@platform/authz';
  import { navigateTo, contextStore } from '@platform/context';
  import { createMutation, createQuery } from '@scylla/core-sdk';
  import { Skeleton } from '@scylla/ui/shadcn';
  import {
    ConfirmOperationAlertDialog,
    ContextItem,
    IconButton,
  } from '@scylla/ui';
  import { toRune } from '@scylla/ui/stores';
  import { slugifyOrgName } from '@shared/utils/slug.ts';
  import { t } from '@scylla/ui/i18n';
  import { organizationMutations, organizationQueries } from '../../organization.queries.ts';
  import { organizationMessages } from '../organization.messages.ts';
  import EditOrganizationDialog from '../EditOrganizationDialog/EditOrganizationDialog.svelte';
  import OrganizationRow from '../OrganizationRow.svelte';

  type RowProps = {
    class?: string;
    onSelect?: () => void;
    children?: Snippet;
  };

  let { row: Row = OrganizationRow }: { row?: Component<RowProps> } = $props();

  const organizationsQuery = createQuery(() => organizationQueries.mine());
  const organizations = $derived(organizationsQuery.data);

  const deleteOrganization = createMutation(() => organizationMutations.remove());

  const context = toRune(contextStore);
  const currentOrganizationId = $derived(context().organization.id);

  let editOrg = $state<{ id: string; name: string; description?: string } | null>(null);
  let deleteOrgId = $state<string | null>(null);

  const selectOrganization = (id: string, name: string) => {
    contextStore.getState().setOrganization(id, name);
    navigateTo(`/${slugifyOrgName(name)}/dashboard`);
  };

  /** Deleting the current organization moves the context to another one, or to none. */
  const onDeleteOrganization = async () => {
    if (!deleteOrgId) return;

    const deletedId = deleteOrgId;
    await deleteOrganization.mutateAsync(deletedId);
    deleteOrgId = null;

    if (deletedId !== currentOrganizationId) return;

    const other = organizations?.find(organization => organization.id !== deletedId);
    contextStore.getState().setOrganization(other?.id ?? null, other?.name ?? null);
    if (other) navigateTo(`/${slugifyOrgName(other.name)}/dashboard`);
  };
</script>

{#if !organizations}
  {#each Array.from({ length: 3 }) as _, index (index)}
    <Row class="group">
      <div class="flex items-center gap-3 px-1 py-1">
        <Skeleton class="h-8 w-8 rounded-md" />
        <Skeleton class="h-4 w-24" />
      </div>
    </Row>
  {/each}
{:else}
  {#each organizations as organization (organization.id)}
    <Row
      class="group rounded-md transition-colors hover:bg-accent/70"
      onSelect={() => selectOrganization(organization.id, organization.name)}
    >
      <div class="flex w-full items-center">
        <div class="min-w-0 flex-1">
          <ContextItem
            name={organization.name}
            description={organization.description}
            icon={Building2Icon}
          />
        </div>
        <div class="flex gap-0.5 opacity-0 transition-opacity group-hover:opacity-100">
          {#if can(Permission.LIST_ORGANIZATION_MEMBERS, { organizationId: organization.id })}
            <IconButton
              icon={UsersIcon}
              tooltip={t(organizationMessages.members)}
              onclick={event => {
                event.stopPropagation();
                // The members page reads the organization from the context.
                contextStore.getState().setOrganization(organization.id, organization.name);
                navigateTo(`/${slugifyOrgName(organization.name)}/members`);
              }}
              class="h-7 w-7"
              iconClass="h-3.5 w-3.5"
            />
          {/if}
          {#if can(Permission.UPDATE_ORGANIZATION, { organizationId: organization.id })}
            <IconButton
              icon={PencilIcon}
              tooltip={t(organizationMessages.edit)}
              onclick={event => {
                event.stopPropagation();
                editOrg = {
                  id: organization.id,
                  name: organization.name,
                  description: organization.description,
                };
              }}
              class="h-7 w-7"
              iconClass="h-3.5 w-3.5"
            />
          {/if}
          {#if can(Permission.DELETE_ORGANIZATION, { organizationId: organization.id })}
            <IconButton
              icon={TrashIcon}
              tooltip={t(organizationMessages.delete)}
              onclick={event => {
                event.stopPropagation();
                deleteOrgId = organization.id;
              }}
              class="h-7 w-7 hover:bg-destructive-subtle hover:text-destructive"
              iconClass="h-3.5 w-3.5"
            />
          {/if}
        </div>
      </div>
    </Row>
  {/each}
{/if}

{#if editOrg}
  <EditOrganizationDialog
    open={!!editOrg}
    setOpen={open => {
      if (!open) editOrg = null;
    }}
    organization={editOrg}
  />
{/if}

<ConfirmOperationAlertDialog
  open={!!deleteOrgId}
  onOpenChange={open => {
    if (!open) deleteOrgId = null;
  }}
  onContinue={onDeleteOrganization}
/>

// src/modules/features/organization/presentation/ui/OrganizationList.tsx
import { useOrganizations } from '@/modules/features/organization/presentation/hooks/useOrganizations.ts';
import { type ComponentType, type ReactNode, useCallback } from 'react';
import { useState } from 'react';
import { useContextStore } from '@platform/context';
import { ContextItem } from '@shared/presentation/ui/layout/ContextItem.tsx';
import { Skeleton } from '@/modules/shared/presentation/ui/shadcn/skeleton.tsx';
import { Building2, Pencil, Trash, Users } from 'lucide-react';
import { IconButton } from '@shared/presentation/ui';
import { EditOrganizationDialog } from '@/modules/features/organization/presentation/ui/EditOrganizationDialog.tsx';
import { useDeleteOrganization } from '@/modules/features/organization/presentation/hooks/use-delete-organization.ts';
import { ConfirmOperationAlertDialog } from '@shared/presentation/ui/feedback/ConfirmOperationAlertDialog.tsx';
import { Trans } from '@lingui/react/macro';
import { slugifyOrgName } from '@shared/utils/slug.ts';
import { Permission } from '@platform/authz';
import { Can } from '@platform/authz';
import { useNavigate } from 'react-router-dom';

interface OrganizationListProps {
  Wrapper: ComponentType<{ children: ReactNode; onSelect?: () => void; className?: string }>;
}

export const OrganizationList = ({ Wrapper }: OrganizationListProps) => {
  const { organizations } = useOrganizations();
  const setOrganization = useContextStore(state => state.setOrganization);
  const currentOrganizationId = useContextStore(state => state.organization.id);
  const navigate = useNavigate();
  const deleteOrganization = useDeleteOrganization();

  const [editOrg, setEditOrg] = useState<{ id: string; name: string; description?: string } | null>(
    null,
  );
  const [deleteOrgId, setDeleteOrgId] = useState<string | null>(null);

  const onDeleteOrganization = useCallback(async () => {
    if (!deleteOrgId) return;

    await deleteOrganization.mutateAsync(deleteOrgId);
    setDeleteOrgId(null);

    if (deleteOrgId !== currentOrganizationId) return;

    const otherOrganization = organizations?.find(
      org => org.id !== deleteOrgId,
    );
    setOrganization(
      otherOrganization ? otherOrganization.id : null,
      otherOrganization?.name ?? null,
    );
    if (otherOrganization) {
      void navigate(`/${slugifyOrgName(otherOrganization.name)}/dashboard`);
    }
  }, [
    deleteOrgId,
    deleteOrganization,
    currentOrganizationId,
    organizations,
    setOrganization,
    navigate,
  ]);

  if (!organizations)
    return (
      <>
        {Array.from({ length: 3 }).map((_, i) => (
          <Wrapper key={i} className='group'>
            <div className='flex items-center gap-3 px-1 py-1'>
              <Skeleton className='h-8 w-8 rounded-md' />
              <Skeleton className='h-4 w-24' />
            </div>
          </Wrapper>
        ))}
      </>
    );

  return (
    <>
      {organizations.map(organisation => (
        <Wrapper
          className='group rounded-md transition-colors hover:bg-accent/70'
          key={organisation.id}
          onSelect={() => {
            setOrganization(organisation.id, organisation.name);
            void navigate(`/${slugifyOrgName(organisation.name)}/dashboard`);
          }}
        >
          <div className='flex items-center w-full'>
            <div className='flex-1 min-w-0'>
              <ContextItem
                name={organisation.name}
                description={organisation.description}
                icon={Building2}
              />
            </div>
            <div className='flex gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity'>
              <Can
                permission={Permission.LIST_ORGANIZATION_MEMBERS}
                target={{ organizationId: organisation.id }}
              >
                <IconButton
                  icon={Users}
                  tooltip={<Trans>Members</Trans>}
                  onClick={e => {
                    e.stopPropagation();
                    // The members page reads the organization from the context
                    // store, so looking at another org's members means moving
                    // to it — the row's own click does the same thing.
                    setOrganization(organisation.id, organisation.name);
                    void navigate(`/${slugifyOrgName(organisation.name)}/members`);
                  }}
                  className='h-7 w-7'
                  iconClassName='h-3.5 w-3.5'
                />
              </Can>
              <Can
                permission={Permission.UPDATE_ORGANIZATION}
                target={{ organizationId: organisation.id }}
              >
                <IconButton
                  icon={Pencil}
                  tooltip={<Trans>Edit</Trans>}
                  onClick={e => {
                    e.stopPropagation();
                    setEditOrg({
                      id: organisation.id,
                      name: organisation.name,
                      description: organisation.description,
                    });
                  }}
                  className='h-7 w-7'
                  iconClassName='h-3.5 w-3.5'
                />
              </Can>
              <Can
                permission={Permission.DELETE_ORGANIZATION}
                target={{ organizationId: organisation.id }}
              >
                <IconButton
                  icon={Trash}
                  tooltip={<Trans>Delete</Trans>}
                  onClick={e => {
                    e.stopPropagation();
                    setDeleteOrgId(organisation.id);
                  }}
                  className='h-7 w-7 hover:text-destructive hover:bg-destructive-subtle'
                  iconClassName='h-3.5 w-3.5'
                />
              </Can>
            </div>
          </div>
        </Wrapper>
      ))}

      {editOrg && (
        <EditOrganizationDialog
          open={!!editOrg}
          setOpen={open => {
            if (!open) setEditOrg(null);
          }}
          organization={editOrg}
        />
      )}

      <ConfirmOperationAlertDialog
        open={!!deleteOrgId}
        onOpenChange={open => {
          if (!open) setDeleteOrgId(null);
        }}
        onContinue={onDeleteOrganization}
      />
    </>
  );
};
