// src/modules/shared/presentation/ui/data-display/AgentRunInstructions.svelte
<script lang="ts">
  import ContainerIcon from '@lucide/svelte/icons/container';
  import TerminalIcon from '@lucide/svelte/icons/terminal';
  import { CodeSnippet, Tabs, TabsContent, TabsList, TabsTrigger } from '@shadcn';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { agentRunInstructionsMessages as messages } from './agent-run-instructions.messages.ts';

  interface Props {
    appId: string;
    /** Shown once at creation. Without it, a placeholder. */
    secret?: string;
  }

  let { appId, secret }: Props = $props();

  const SECRET_PLACEHOLDER = '<APP_SECRET>';
  const DOCKER_IMAGE = 'godlyjaaaaj/scylla-agent:latest';

  const secretValue = $derived(secret ?? SECRET_PLACEHOLDER);
  // The control plane serves this page, so its URL is the page's origin.
  const controlPlaneUrl = window.location.origin;

  const cargoCommand = $derived(
    [
      'cargo run --release --bin scylla-agent -- \\',
      `  --control-plane-url ${controlPlaneUrl} \\`,
      `  --app-id ${appId} \\`,
      `  --app-secret ${secretValue} \\`,
      '  --workspace-root "$HOME/.scylla/workspaces"',
    ].join('\n'),
  );

  const dockerCommand = $derived(
    [
      `docker run ${DOCKER_IMAGE} \\`,
      `  --control-plane-url ${controlPlaneUrl} \\`,
      `  --app-id ${appId} \\`,
      `  --app-secret ${secretValue}`,
    ].join('\n'),
  );

  const triggerClass =
    'h-auto flex-none gap-1.5 rounded-none border-0 border-b-2 border-transparent bg-transparent ' +
    'px-0 pb-2 text-xs text-muted-foreground shadow-none transition-colors hover:text-foreground ' +
    'data-[state=active]:border-primary data-[state=active]:text-primary ' +
    'data-[state=active]:bg-transparent data-[state=active]:shadow-none';
</script>

<!-- How to start the worker: `cargo run` from a checkout, or the Docker image. -->
<div class="w-full space-y-3">
  <Tabs value="cargo" class="w-full">
    <TabsList
      class="h-auto w-full justify-start gap-4 rounded-none border-b border-border bg-transparent p-0"
    >
      <TabsTrigger value="cargo" class={triggerClass}>
        <TerminalIcon class="h-3.5 w-3.5" />
        {t(messages.fromSource)}
      </TabsTrigger>
      <TabsTrigger value="docker" class={triggerClass}>
        <ContainerIcon class="h-3.5 w-3.5" />
        Docker
      </TabsTrigger>
    </TabsList>

    <TabsContent value="cargo" class="mt-2.5 space-y-1.5 focus-visible:outline-none">
      <CodeSnippet
        multiline
        value={cargoCommand}
        copyToast={t(messages.commandCopied)}
        label={cargoLabel}
      />
      <p class="text-xs text-muted-foreground leading-normal">
        {t(messages.requiresRustBefore)}
        <a
          href="https://github.com/scylla-ops/scylla"
          target="_blank"
          rel="noreferrer"
          class="underline underline-offset-2 hover:text-foreground"
        >
          {t(messages.scyllaRepoLink)}
        </a>
        {t(messages.requiresRustAfter)}
      </p>
    </TabsContent>

    <TabsContent value="docker" class="mt-2.5 space-y-1.5 focus-visible:outline-none">
      <CodeSnippet
        multiline
        value={dockerCommand}
        copyToast={t(messages.commandCopied)}
        label={dockerLabel}
      />
      <p class="text-xs text-muted-foreground leading-normal">{t(messages.dockerForeground)}</p>
    </TabsContent>
  </Tabs>

  <p class="text-xs text-muted-foreground leading-normal">{t(messages.replaceUrl)}</p>

  {#if !secret}
    <p
      class="rounded-md border border-border bg-muted/40 px-3 py-2 text-xs text-muted-foreground leading-normal"
    >
      {t(messages.replaceSecret)}
    </p>
  {/if}
</div>

{#snippet cargoLabel()}{t(messages.runFromCheckout)}{/snippet}
{#snippet dockerLabel()}{t(messages.runWithDocker)}{/snippet}

// src/modules/shared/presentation/ui/AgentRunInstructions.tsx
import { Trans } from '@lingui/react/macro';
import { Container, Terminal } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@shadcn/tabs.tsx';
import { CodeSnippet } from '@shadcn/code-snippet.tsx';

interface AgentRunInstructionsProps {
  /** The agent's app id (its identity towards the control plane). */
  appId: string;
  /** One-time plaintext secret (creation flow). Omitted → placeholder. */
  secret?: string;
}

const SECRET_PLACEHOLDER = '<APP_SECRET>';
const URL_PLACEHOLDER = '<CONTROL_PLANE_URL>';
const DOCKER_IMAGE = 'godlyjaaaaj/scylla-agent:latest';

/**
 * "How do I start this worker?" — the copy-paste answer, in the two supported
 * flavors: `cargo run` from a repo checkout (first — no extra tooling concepts
 * beyond Rust itself), or the published Docker image. Shared by the one-time
 * secret dialog (shown after the reveal) and the agent detail page
 * (placeholder secret).
 *
 * The control-plane URL is deliberately a placeholder, not a guessed value:
 * the UI only knows how the BROWSER reaches the API, which is rarely the
 * address a worker on some other machine (or inside Docker) should dial.
 * Better an explicit "fill this in" than a copied command that half-works.
 */
export const AgentRunInstructions = ({ appId, secret }: AgentRunInstructionsProps) => {
  const secretValue = secret ?? SECRET_PLACEHOLDER;

  const cargoCommand = [
    'cargo run --release --bin scylla-agent -- \\',
    `  --control-plane-url ${URL_PLACEHOLDER} \\`,
    `  --app-id ${appId} \\`,
    `  --app-secret ${secretValue} \\`,
    '  --workspace-root "$HOME/.scylla/workspaces"',
  ].join('\n');

  const dockerCommand = [
    `docker run ${DOCKER_IMAGE} \\`,
    `  --control-plane-url ${URL_PLACEHOLDER} \\`,
    `  --app-id ${appId} \\`,
    `  --app-secret ${secretValue}`,
  ].join('\n');

  const triggerClass =
    'h-auto flex-none gap-1.5 rounded-none border-0 border-b-2 border-transparent bg-transparent ' +
    'px-0 pb-2 text-xs text-muted-foreground shadow-none transition-colors hover:text-foreground ' +
    'data-[state=active]:border-primary data-[state=active]:text-primary ' +
    'data-[state=active]:bg-transparent data-[state=active]:shadow-none';

  return (
    <div className='space-y-2'>
      <Tabs defaultValue='cargo' className='w-full'>
        <TabsList className='h-auto w-full justify-start gap-4 rounded-none border-b bg-transparent p-0'>
          <TabsTrigger value='cargo' className={triggerClass}>
            <Terminal className='h-3.5 w-3.5' />
            <Trans>From source</Trans>
          </TabsTrigger>
          <TabsTrigger value='docker' className={triggerClass}>
            <Container className='h-3.5 w-3.5' />
            Docker
          </TabsTrigger>
        </TabsList>

        <TabsContent value='cargo' className='space-y-2 pt-2'>
          <CodeSnippet
            multiline
            value={cargoCommand}
            copyToast='Command copied'
            label={<Trans>Run from a repo checkout</Trans>}
          />
          <p className='text-xs text-muted-foreground'>
            <Trans>
              Requires the Rust toolchain, from a clone of{' '}
              <a
                href='https://github.com/scylla-ops/scylla'
                target='_blank'
                rel='noreferrer'
                className='underline underline-offset-2 hover:text-foreground'
              >
                the scylla repo
              </a>{' '}
              (crate scylla-agent). The worker runs in the foreground and Ctrl-C stops it.
            </Trans>
          </p>
        </TabsContent>

        <TabsContent value='docker' className='space-y-2 pt-2'>
          <CodeSnippet
            multiline
            value={dockerCommand}
            copyToast='Command copied'
            label={<Trans>Run with Docker</Trans>}
          />
          <p className='text-xs text-muted-foreground'>
            <Trans>
              The worker starts in the foreground: its logs show up right in the terminal and Ctrl-C
              stops it.
            </Trans>
          </p>
        </TabsContent>
      </Tabs>

      <p className='text-xs text-muted-foreground'>
        <Trans>
          Replace CONTROL_PLANE_URL with the address your worker reaches the control plane at — for
          example http://localhost:50051 on the same machine, or http://host.docker.internal:50051
          from inside Docker.
        </Trans>
      </p>

      {!secret && (
        <p className='rounded-md border bg-muted/40 p-2.5 text-xs text-muted-foreground'>
          <Trans>
            Replace APP_SECRET with the secret revealed when this agent was created — it cannot be
            shown again. Lost it? Delete this agent and create a new one.
          </Trans>
        </p>
      )}
    </div>
  );
};

export default AgentRunInstructions;
