// src/modules/shared/presentation/ui/data-display/DataTable/DataTable.svelte
<script lang="ts" generics="TData extends RowData">
  import type { Snippet } from 'svelte';
  import { createTable, FlexRender } from '@tanstack/svelte-table';
  import type { Row, RowData } from '@tanstack/table-core';
  import { TableBody, TableCell, TableHead, TableHeader, TableRow } from '@shadcn';
  import { cn } from '@shared/presentation/utils';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { dataTableMessages } from '../data-table.messages.ts';
  import {
    DATA_TABLE_FEATURES,
    alignClass,
    buildGridTemplate,
    cellAlignClass,
    headAlignClass,
    minTableWidthOf,
    type ColumnAlign,
    type DataTableColumn,
    type DataTableFeatures,
  } from '../data-table.ts';

  type TableRowOf = Row<DataTableFeatures, TData>;

  interface Props {
    columns: DataTableColumn<TData>[];
    data: TData[];
    onRowClick?: (row: TableRowOf) => void;
    getRowId?: (row: TData, index: number) => string;
    isRowSelected?: (row: TData) => boolean;
    /** Rendered in a full-width row under the row it belongs to. */
    expandedContent?: Snippet<[TableRowOf]>;
    isRowExpanded?: (row: TData) => boolean;
    alignColumnsCenter?: boolean;
    alignRowsCenter?: boolean;
  }

  let {
    columns,
    data,
    onRowClick,
    getRowId,
    isRowSelected,
    expandedContent,
    isRowExpanded,
    alignColumnsCenter = false,
    alignRowsCenter = false,
  }: Props = $props();

  // Getters: the adapter re-reads them, which keeps `getRowModel()` in step with the data.
  const table = createTable<DataTableFeatures, TData>({
    features: DATA_TABLE_FEATURES,
    get columns() {
      return columns;
    },
    get data() {
      return data;
    },
    get getRowId() {
      return getRowId;
    },
  });

  const gridTemplateColumns = $derived(buildGridTemplate(columns));
  const minTableWidth = $derived(minTableWidthOf(columns));
  const rowStyle = $derived(`grid-template-columns: ${gridTemplateColumns}`);

  const defaultAlign = (centered: boolean): ColumnAlign => (centered ? 'center' : 'left');
</script>

<div
  class="h-full w-full overflow-auto rounded-2xl border border-border/70 bg-card shadow-[0_1px_2px_oklch(0_0_0/0.04),0_12px_32px_-16px_oklch(0_0_0/0.18)]"
>
  <!-- Rows are CSS grids (see `buildGridTemplate`); table, thead and tbody stay blocks so
    the header can stick. They lose their implicit ARIA roles: restate them. -->
  <!-- svelte-ignore a11y_no_redundant_roles -->
  <table
    role="table"
    class="block w-full text-sm"
    style:min-width={minTableWidth > 0 ? `${minTableWidth}px` : undefined}
  >
    <TableHeader
      role="rowgroup"
      class="sticky top-0 z-10 block bg-card/80 shadow-[inset_0_-1px_0_0_var(--border)] backdrop-blur-xl"
    >
      {#each table.getHeaderGroups() as headerGroup (headerGroup.id)}
        <TableRow role="row" class="grid hover:bg-transparent" style={rowStyle}>
          {#each headerGroup.headers as header (header.id)}
            {@const align = header.column.columnDef.meta?.align ?? defaultAlign(alignColumnsCenter)}
            <TableHead
              role="columnheader"
              class={cn(
                'flex h-11 min-w-0 items-center overflow-hidden px-5 text-[0.6875rem] font-semibold tracking-[0.08em] text-muted-foreground/90 uppercase',
                alignClass[align],
                headAlignClass[align],
              )}
            >
              {#if !header.isPlaceholder}
                <FlexRender {header} />
              {/if}
            </TableHead>
          {/each}
        </TableRow>
      {/each}
    </TableHeader>

    <TableBody role="rowgroup" class="block">
      {#each table.getRowModel().rows as row (row.id)}
        {@const selected = isRowSelected?.(row.original) ?? false}
        <TableRow
          role="row"
          data-state={selected ? 'selected' : undefined}
          onclick={() => onRowClick?.(row)}
          style={rowStyle}
          class={cn(
            'grid transition-colors duration-150',
            onRowClick && 'cursor-pointer',
            onRowClick && !selected && 'hover:bg-muted/40',
            // An inset shadow, not a border: the accent bar does not shift the first column.
            selected &&
              '[&>td]:bg-primary/[0.07] [&>td:first-child]:shadow-[inset_3px_0_0_0_var(--primary)] hover:[&>td]:bg-primary/[0.1]',
          )}
        >
          {#each row.getAllCells() as cell (cell.id)}
            {@const align = cell.column.columnDef.meta?.align ?? defaultAlign(alignRowsCenter)}
            <TableCell
              role="cell"
              class={cn('flex min-w-0 items-center overflow-hidden px-5 py-3.5', alignClass[align])}
            >
              <div class={cn('w-full min-w-0', cellAlignClass[align])}>
                <FlexRender {cell} />
              </div>
            </TableCell>
          {/each}
        </TableRow>

        {#if (isRowExpanded?.(row.original) ?? false) && expandedContent}
          <TableRow role="row" class="grid grid-cols-[minmax(0,1fr)] hover:bg-transparent">
            <TableCell role="cell" class="min-w-0 overflow-hidden bg-muted/30 p-0">
              {@render expandedContent(row)}
            </TableCell>
          </TableRow>
        {/if}
      {:else}
        <TableRow role="row" class="grid grid-cols-[minmax(0,1fr)] hover:bg-transparent">
          <TableCell
            role="cell"
            class="flex h-28 items-center justify-center text-sm text-muted-foreground"
          >
            {t(dataTableMessages.noResults)}
          </TableCell>
        </TableRow>
      {/each}
    </TableBody>
  </table>
</div>

// src/modules/shared/presentation/ui/DataTable.tsx
import React from 'react';
import {
  flexRender,
  getCoreRowModel,
  useReactTable,
  type ColumnDef,
  type Row,
} from '@tanstack/react-table';
import {
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/modules/shared/presentation/ui/shadcn/table';
import { cn } from '@shared/presentation/utils';

type ColumnAlign = 'left' | 'center' | 'right';

declare module '@tanstack/react-table' {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface ColumnMeta<TData, TValue> {
    align?: ColumnAlign;
  }
}

const alignClass: Record<ColumnAlign, string> = {
  left: 'text-left',
  center: 'text-center',
  right: 'text-right',
};

const cellAlignClass: Record<ColumnAlign, string> = {
  left: '',
  center: 'flex items-center justify-center',
  right: 'flex items-center justify-end',
};

interface DataTableProps<TData, TValue> {
  columns: ColumnDef<TData, TValue>[];
  data: TData[];
  onRowClick?: (row: Row<TData>) => void;
  getRowId?: (row: TData, index: number) => string;
  isRowSelected?: (row: TData) => boolean;
  expandedContent?: (row: Row<TData>) => React.ReactNode;
  isRowExpanded?: (row: TData) => boolean;
  alignColumnsCenter?: boolean;
  alignRowsCenter?: boolean;
}

export function DataTable<TData, TValue>({
  columns,
  data,
  onRowClick,
  getRowId,
  isRowSelected,
  expandedContent,
  isRowExpanded,
  alignRowsCenter = false,
  alignColumnsCenter = false,
}: DataTableProps<TData, TValue>) {
  const table = useReactTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
    getRowId,
  });

  return (
    <div className='w-full h-full border border-slate-200 bg-white shadow-sm rounded-xl overflow-auto'>
      <table className='w-full caption-bottom text-sm relative'>
        <TableHeader className='bg-slate-50 sticky top-0 z-10'>
          {table.getHeaderGroups().map(headerGroup => (
            <TableRow
              key={headerGroup.id}
              className='hover:bg-transparent border-b border-slate-200'
            >
              {headerGroup.headers.map(header => {
                const align =
                  header.column.columnDef.meta?.align ?? (alignColumnsCenter ? 'center' : 'left');
                return (
                  <TableHead
                    key={header.id}
                    style={{
                      width: header.getSize() !== 150 ? `${header.getSize()}px` : 'auto',
                      minWidth: header.column.columnDef.minSize
                        ? `${header.column.columnDef.minSize}px`
                        : undefined,
                    }}
                    className={cn(
                      'h-12 px-4 text-slate-600 font-semibold bg-slate-50 text-xs uppercase tracking-wider',
                      alignClass[align],
                    )}
                  >
                    {header.isPlaceholder
                      ? null
                      : flexRender(header.column.columnDef.header, header.getContext())}
                  </TableHead>
                );
              })}
            </TableRow>
          ))}
        </TableHeader>

        <TableBody>
          {table.getRowModel().rows?.length ? (
            table.getRowModel().rows.map(row => {
              const isSelected = isRowSelected?.(row.original) ?? false;
              const isExpanded = isRowExpanded?.(row.original) ?? false;

              return (
                <React.Fragment key={row.id}>
                  <TableRow
                    data-state={isSelected ? 'selected' : undefined}
                    onClick={() => onRowClick?.(row)}
                    className={cn(
                      'border-b [&>td:first-child]:border-l-[3px] border-slate-100 [&>td:first-child]:border-l-transparent transition-colors duration-150',
                      onRowClick && 'cursor-pointer',
                      onRowClick && !isSelected && 'hover:bg-slate-50',
                      isSelected &&
                        '[&>td]:bg-primary/6 [&>td:first-child]:border-l-[3px] [&>td:first-child]:border-l-primary hover:bg-primary/9',
                    )}
                  >
                    {row.getVisibleCells().map((cell, index) => {
                      const header = table.getHeaderGroups()[0].headers[index];
                      const align =
                        cell.column.columnDef.meta?.align ?? (alignRowsCenter ? 'center' : 'left');
                      return (
                        <TableCell
                          key={cell.id}
                          style={{
                            width: header.getSize() !== 150 ? `${header.getSize()}px` : 'auto',
                            minWidth: header.column.columnDef.minSize
                              ? `${header.column.columnDef.minSize}px`
                              : undefined,
                          }}
                          className={cn('px-4 py-4', alignClass[align])}
                        >
                          <div className={cn(cellAlignClass[align])}>
                            {flexRender(cell.column.columnDef.cell, cell.getContext())}
                          </div>
                        </TableCell>
                      );
                    })}
                  </TableRow>

                  {isExpanded && expandedContent && (
                    <TableRow
                      key={`${row.id}-expanded`}
                      className='border-b border-slate-200 bg-slate-50/50'
                    >
                      <TableCell colSpan={columns.length} className='p-0'>
                        {expandedContent(row)}
                      </TableCell>
                    </TableRow>
                  )}
                </React.Fragment>
              );
            })
          ) : (
            <TableRow>
              <TableCell colSpan={columns.length} className='h-24 text-center text-slate-500'>
                No results.
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </table>
    </div>
  );
}
