// src/modules/features/jobs/presentation/ui/jobs-table/JobStatus.tsx
import { Badge } from '@shadcn';
import type { JobEntity } from '@/modules/features/jobs/domain/entities/job.entity.ts';
import { getStatusConfig } from '@shared/utils/status-config.ts';
import { TruncatedText } from '@shared/presentation/ui';
import { Trans } from '@lingui/react/macro';
import { useLingui } from '@lingui/react';

type JobStatusProps = {
  job: JobEntity;
};

/**
 * Display the status badge for a job with icon and label
 */
export const JobStatus = ({ job }: JobStatusProps) => {
  const { _ } = useLingui();
  const config = getStatusConfig(job.status);
  const Icon = config.icon;

  return (
    <div className='w-full flex items-center gap-2'>
      <Icon className={`w-5 h-5 ${config.iconClassName}`} />
      <div className='flex min-w-0 flex-col'>
        <Badge variant={config.variant} className='w-fit'>
          {_(config.label)}
        </Badge>
        {job.status === 'pending' && (
          <TruncatedText className='text-xs text-muted-foreground'>
            <Trans>queued — waiting for an agent</Trans>
          </TruncatedText>
        )}
        {job.status === 'orphaned' && (
          <TruncatedText className='text-xs text-muted-foreground'>
            <Trans>agent disconnected mid-run</Trans>
          </TruncatedText>
        )}
      </div>
    </div>
  );
};

// src/modules/features/jobs/presentation/ui/jobs-table/JobStatus/JobStatus.svelte
<script lang="ts">
  import { Badge } from '@shadcn';
  import { TruncatedText, getStatusIcon } from '@shared/presentation/ui';
  import { cn } from '@shared/presentation/utils';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { getStatusConfig } from '@shared/utils/status-config.ts';
  import type { JobEntity } from '../../../../domain/entities/job.entity.ts';
  import { jobsMessages } from '../../jobs.messages.ts';

  interface Props {
    job: JobEntity;
  }

  let { job }: Props = $props();

  const config = $derived(getStatusConfig(job.status));
  const Icon = $derived(getStatusIcon(job.status));
</script>

<div class="w-full flex items-center gap-2">
  <Icon class={cn('w-5 h-5', config.iconClassName)} />
  <div class="flex min-w-0 flex-col">
    <Badge variant="outline" class={cn('w-fit', config.badgeClassName)}>
      {t(config.label)}
    </Badge>
    {#if job.status === 'pending'}
      <TruncatedText class="text-xs text-muted-foreground">
        {t(jobsMessages.queuedHint)}
      </TruncatedText>
    {:else if job.status === 'orphaned'}
      <TruncatedText class="text-xs text-muted-foreground">
        {t(jobsMessages.orphanedHint)}
      </TruncatedText>
    {/if}
  </div>
</div>
