// extensions/scylla-base/src/features/pipeline/presentation/ui/dashboard/pipeline-table/PipelineActions.svelte
<script lang="ts">
  import CopyIcon from '@lucide/svelte/icons/copy';
  import ListChecksIcon from '@lucide/svelte/icons/list-checks';
  import Loader2Icon from '@lucide/svelte/icons/loader-2';
  import MoreHorizontalIcon from '@lucide/svelte/icons/more-horizontal';
  import PencilIcon from '@lucide/svelte/icons/pencil';
  import PlayIcon from '@lucide/svelte/icons/play';
  import ZapIcon from '@lucide/svelte/icons/zap';
  import { Permission, can } from '@platform/authz';
  import {
    Button,
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
  } from '@scylla/ui/shadcn';
  import { IconButton } from '@scylla/ui';
  import { createCompactContainer } from '@scylla/ui/state';
  import { t } from '@scylla/ui/i18n';
  import { pipelineMessages } from '../../../pipeline.messages.ts';

  interface Props {
    onRun: (event: MouseEvent) => void;
    onEdit: (event: MouseEvent) => void;
    onDuplicate: (event: MouseEvent) => void;
    onViewJobs?: (event: MouseEvent) => void;
    onViewTriggers?: (event: MouseEvent) => void;
    isRunning?: boolean;
    isDuplicating?: boolean;
  }

  let {
    onRun,
    onEdit,
    onDuplicate,
    onViewJobs,
    onViewTriggers,
    isRunning = false,
    isDuplicating = false,
  }: Props = $props();

  const compact = createCompactContainer();

  const canRun = $derived(can(Permission.RUN_PIPELINE));
  const canEdit = $derived(can(Permission.UPDATE_PIPELINE));
  const canDuplicate = $derived(can(Permission.CREATE_PIPELINE));
  const showTriggers = $derived(!!onViewTriggers && can(Permission.MANAGE_TRIGGERS));
</script>

<!-- Falls back to a menu when the column is too narrow. -->
<div
  use:compact.measure
  class="flex w-full shrink-0 items-center justify-center gap-2"
>
  {#if compact.isCompact}
    <DropdownMenu>
      <DropdownMenuTrigger>
        {#snippet child({ props })}
          <Button
            {...props}
            type="button"
            size="icon"
            variant="ghost"
            class="h-8 w-8 shrink-0 rounded-full text-slate-400 hover:text-slate-900"
          >
            <MoreHorizontalIcon class="h-4 w-4" />
            <!-- An icon-only button: this is its name. -->
            <span class="sr-only">{t(pipelineMessages.pipelineActions)}</span>
          </Button>
        {/snippet}
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" class="w-40">
        {#if canRun}
          <DropdownMenuItem onclick={onRun}>
            <PlayIcon class="mr-2 h-4 w-4" />
            {t(pipelineMessages.run)}
          </DropdownMenuItem>
        {/if}
        {#if canEdit}
          <DropdownMenuItem onclick={onEdit}>
            <PencilIcon class="mr-2 h-4 w-4" />
            {t(pipelineMessages.edit)}
          </DropdownMenuItem>
        {/if}
        {#if canDuplicate}
          <DropdownMenuItem onclick={onDuplicate}>
            <CopyIcon class="mr-2 h-4 w-4" />
            {t(pipelineMessages.duplicate)}
          </DropdownMenuItem>
        {/if}
        {#if onViewJobs}
          <DropdownMenuItem onclick={onViewJobs}>
            <ListChecksIcon class="mr-2 h-4 w-4" />
            {t(pipelineMessages.viewJobs)}
          </DropdownMenuItem>
        {/if}
        {#if showTriggers}
          <DropdownMenuItem onclick={onViewTriggers}>
            <ZapIcon class="mr-2 h-4 w-4" />
            {t(pipelineMessages.triggers)}
          </DropdownMenuItem>
        {/if}
      </DropdownMenuContent>
    </DropdownMenu>
  {:else}
    {#if canRun}
      <IconButton
        icon={isRunning ? Loader2Icon : PlayIcon}
        tooltip={t(pipelineMessages.run)}
        onclick={onRun}
        busy={isRunning}
        iconClass={isRunning ? 'animate-spin' : 'fill-current'}
      />
    {/if}

    {#if canEdit}
      <IconButton
        icon={PencilIcon}
        tooltip={t(pipelineMessages.editPipeline)}
        onclick={onEdit}
      />
    {/if}

    {#if canDuplicate}
      <IconButton
        icon={isDuplicating ? Loader2Icon : CopyIcon}
        tooltip={t(pipelineMessages.duplicate)}
        onclick={onDuplicate}
        busy={isDuplicating}
        iconClass={isDuplicating ? 'animate-spin' : undefined}
      />
    {/if}

    {#if onViewJobs}
      <IconButton
        icon={ListChecksIcon}
        tooltip={t(pipelineMessages.viewJobs)}
        onclick={onViewJobs}
      />
    {/if}

    {#if showTriggers}
      <IconButton icon={ZapIcon} tooltip={t(pipelineMessages.triggers)} onclick={onViewTriggers} />
    {/if}
  {/if}
</div>

// src/modules/features/pipeline/presentation/ui/dashboard/pipeline-table/PipelineActions.tsx
import { Button } from '@shadcn';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@shadcn/dropdown-menu.tsx';
import { EditIcon, PlayIcon, MoreHorizontal, ListChecks, Loader2, Copy, Zap } from 'lucide-react';
import type { SyntheticEvent } from 'react';
import { Trans } from '@lingui/react/macro';
import { IconButton } from '@shared/presentation/ui';
import { useCompactContainer } from '@shared/presentation/hooks/use-compact-container.ts';
import { Permission } from '@platform/authz';
import { useCan } from '@platform/authz';

type PipelineActionsProps = {
  onRun: (e: SyntheticEvent) => void;
  onEdit: (e: SyntheticEvent) => void;
  onDuplicate: (e: SyntheticEvent) => void;
  onViewJobs?: (e: SyntheticEvent) => void;
  onViewTriggers?: (e: SyntheticEvent) => void;
  onMore?: (e: SyntheticEvent) => void;
  isRunning?: boolean;
  isDuplicating?: boolean;
};

/**
 * Display actions for a pipeline in the status card, such as run, edit, and more options.
 * Automatically switches to dropdown mode when space is limited.
 */
export const PipelineActions = ({
  onRun,
  onEdit,
  onDuplicate,
  onViewJobs,
  onViewTriggers,
  onMore,
  isRunning,
  isDuplicating,
}: PipelineActionsProps) => {
  const { containerRef, isCompact } = useCompactContainer();

  // Gate each action by the permission it needs, in the current project context.
  const canRun = useCan(Permission.RUN_PIPELINE);
  const canEdit = useCan(Permission.UPDATE_PIPELINE);
  const canDuplicate = useCan(Permission.CREATE_PIPELINE);
  const canManageTriggers = useCan(Permission.MANAGE_TRIGGERS);
  const showTriggers = !!onViewTriggers && canManageTriggers;

  return (
    <div ref={containerRef} className='flex w-full items-center justify-center gap-2 shrink-0'>
      {isCompact ? (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              type={'button'}
              size='icon'
              variant='ghost'
              className='h-8 w-8 shrink-0 text-slate-400 hover:text-slate-900 rounded-full'
            >
              <MoreHorizontal className='w-4 h-4' />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align='end' className='w-40'>
            {canRun && (
              <DropdownMenuItem onClick={onRun}>
                <PlayIcon className='w-4 h-4 mr-2' />
                <Trans>Run</Trans>
              </DropdownMenuItem>
            )}
            {canEdit && (
              <DropdownMenuItem onClick={onEdit}>
                <EditIcon className='w-4 h-4 mr-2' />
                <Trans>Edit</Trans>
              </DropdownMenuItem>
            )}
            {canDuplicate && (
              <DropdownMenuItem onClick={onDuplicate}>
                <Copy className='w-4 h-4 mr-2' />
                <Trans>Duplicate</Trans>
              </DropdownMenuItem>
            )}
            {onViewJobs && (
              <DropdownMenuItem onClick={onViewJobs}>
                <ListChecks className='w-4 h-4 mr-2' />
                <Trans>View Jobs</Trans>
              </DropdownMenuItem>
            )}
            {showTriggers && (
              <DropdownMenuItem onClick={onViewTriggers}>
                <Zap className='w-4 h-4 mr-2' />
                <Trans>Triggers</Trans>
              </DropdownMenuItem>
            )}
            {onMore && (
              <DropdownMenuItem onClick={onMore}>
                <MoreHorizontal className='w-4 h-4 mr-2' />
                <Trans>More options</Trans>
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      ) : (
        <>
          {canRun && (
            <IconButton
              icon={isRunning ? Loader2 : PlayIcon}
              tooltip={<Trans>Run</Trans>}
              onClick={onRun}
              busy={isRunning}
              iconClassName={isRunning ? 'animate-spin' : 'fill-current'}
            />
          )}

          {canEdit && (
            <IconButton icon={EditIcon} tooltip={<Trans>Edit pipeline</Trans>} onClick={onEdit} />
          )}

          {canDuplicate && (
            <IconButton
              icon={isDuplicating ? Loader2 : Copy}
              tooltip={<Trans>Duplicate</Trans>}
              onClick={onDuplicate}
              busy={isDuplicating}
              iconClassName={isDuplicating ? 'animate-spin' : undefined}
            />
          )}

          {onViewJobs && (
            <IconButton icon={ListChecks} tooltip={<Trans>View Jobs</Trans>} onClick={onViewJobs} />
          )}

          {showTriggers && (
            <IconButton icon={Zap} tooltip={<Trans>Triggers</Trans>} onClick={onViewTriggers} />
          )}

          {onMore && (
            <IconButton
              icon={MoreHorizontal}
              tooltip={<Trans>More options</Trans>}
              onClick={onMore}
            />
          )}
        </>
      )}
    </div>
  );
};
