// src/modules/features/dashboard/presentation/ui/AgentOutcomesChart.tsx
import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from 'recharts';
import { Trans } from '@lingui/react/macro';
import { Card, CardContent, CardHeader, CardTitle } from '@shadcn';
import { Skeleton } from '@shadcn/skeleton.tsx';
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from '@shadcn/chart.tsx';
import { cn } from '@shared/presentation/utils';
import { useAgents } from '@/modules/features/agents';
import { useAgentStats } from '@/modules/features/agents';
import type { DailyOutcome } from '@/modules/features/agents';

type Range = '7d' | '14d' | '30d';
type StatusFilter = 'all' | 'completed' | 'failed' | 'cancelled';

const RANGES: Range[] = ['7d', '14d', '30d'];
const RANGE_DAYS: Record<Range, number> = { '7d': 7, '14d': 14, '30d': 30 };
const STATUS_FILTERS: StatusFilter[] = ['all', 'completed', 'failed', 'cancelled'];

const CHART_CONFIG = {
  completed: { label: <Trans>Completed</Trans>, color: 'var(--success)' },
  failed: { label: <Trans>Failed</Trans>, color: 'var(--destructive)' },
  cancelled: { label: <Trans>Cancelled</Trans>, color: 'var(--warning)' },
} satisfies ChartConfig;

const STATUS_FILTER_LABEL: Record<StatusFilter, ReactNode> = {
  all: <Trans>all</Trans>,
  completed: <Trans>completed</Trans>,
  failed: <Trans>failed</Trans>,
  cancelled: <Trans>cancelled</Trans>,
};

const localDay = (iso: string): string => {
  const d = new Date(iso);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};

const fillBuckets = (daily: DailyOutcome[], days: number) => {
  const byDay = new Map(daily.map(d => [localDay(d.day), d]));
  const today = new Date();
  return Array.from({ length: days }, (_, i) => {
    const d = new Date(today);
    d.setDate(today.getDate() - (days - 1 - i));
    const key = localDay(d.toISOString());
    const hit = byDay.get(key);
    return {
      day: key,
      label: `${d.getDate()}`,
      completed: hit?.completed ?? 0,
      failed: hit?.failed ?? 0,
      cancelled: hit?.cancelled ?? 0,
    };
  });
};

const ToggleGroup = <T extends string>({
  options,
  value,
  onChange,
  label,
}: {
  options: T[];
  value: T;
  onChange: (v: T) => void;
  label: (v: T) => ReactNode;
}) => (
  <div className='flex overflow-hidden rounded border text-[11px] font-mono'>
    {options.map(opt => (
      <button
        key={opt}
        type='button'
        onClick={() => onChange(opt)}
        className={cn(
          'px-2.5 py-1 capitalize transition-colors',
          opt === value ? 'bg-foreground text-background' : 'text-muted-foreground hover:bg-muted',
        )}
      >
        {label(opt)}
      </button>
    ))}
  </div>
);

const AgentChartInner = ({ agentId }: { agentId: string }) => {
  const [range, setRange] = useState<Range>('14d');
  const [status, setStatus] = useState<StatusFilter>('all');

  const { data: stats, isLoading } = useAgentStats(agentId);

  const buckets = useMemo(
    () => fillBuckets(stats?.daily ?? [], RANGE_DAYS[range]),
    [stats?.daily, range],
  );

  const hasData = buckets.some(b => b.completed + b.failed + b.cancelled > 0);

  const activeConfig = useMemo<ChartConfig>(() => {
    if (status === 'all') return CHART_CONFIG;
    return { [status]: CHART_CONFIG[status] };
  }, [status]);

  if (isLoading) {
    return <Skeleton className='h-[160px] w-full' />;
  }

  return (
    <div className='space-y-3'>
      <div className='flex flex-wrap items-center justify-between gap-2'>
        <ToggleGroup<StatusFilter>
          options={STATUS_FILTERS}
          value={status}
          onChange={setStatus}
          label={v => STATUS_FILTER_LABEL[v]}
        />
        <ToggleGroup<Range> options={RANGES} value={range} onChange={setRange} label={v => v} />
      </div>

      {!hasData ? (
        <div className='flex h-[160px] items-center justify-center text-center'>
          <p className='text-sm text-muted-foreground'>
            <Trans>No finished jobs in this window.</Trans>
          </p>
        </div>
      ) : (
        <ChartContainer config={activeConfig} className='h-[160px] w-full'>
          <AreaChart data={buckets} margin={{ top: 4, right: 8, bottom: 0, left: -16 }}>
            <defs>
              <linearGradient id='grad-completed' x1='0' y1='0' x2='0' y2='1'>
                <stop offset='5%' stopColor='var(--success)' stopOpacity={0.25} />
                <stop offset='95%' stopColor='var(--success)' stopOpacity={0} />
              </linearGradient>
              <linearGradient id='grad-failed' x1='0' y1='0' x2='0' y2='1'>
                <stop offset='5%' stopColor='var(--destructive)' stopOpacity={0.25} />
                <stop offset='95%' stopColor='var(--destructive)' stopOpacity={0} />
              </linearGradient>
              <linearGradient id='grad-cancelled' x1='0' y1='0' x2='0' y2='1'>
                <stop offset='5%' stopColor='var(--warning)' stopOpacity={0.25} />
                <stop offset='95%' stopColor='var(--warning)' stopOpacity={0} />
              </linearGradient>
            </defs>
            <CartesianGrid strokeDasharray='3 3' vertical={false} />
            <XAxis
              dataKey='label'
              tickLine={false}
              axisLine={false}
              tick={{ fontSize: 10 }}
              interval='preserveStartEnd'
            />
            <YAxis
              tickLine={false}
              axisLine={false}
              tick={{ fontSize: 10 }}
              allowDecimals={false}
            />
            <ChartTooltip
              content={
                <ChartTooltipContent
                  labelFormatter={(_, payload) => {
                    const day = payload?.[0]?.payload?.day as string | undefined;
                    return day ?? '';
                  }}
                />
              }
            />
            {(status === 'all' || status === 'completed') && (
              <Area
                type='monotone'
                dataKey='completed'
                stroke='var(--success)'
                strokeWidth={2}
                fill='url(#grad-completed)'
                dot={false}
                activeDot={{ r: 4 }}
              />
            )}
            {(status === 'all' || status === 'failed') && (
              <Area
                type='monotone'
                dataKey='failed'
                stroke='var(--destructive)'
                strokeWidth={2}
                fill='url(#grad-failed)'
                dot={false}
                activeDot={{ r: 4 }}
              />
            )}
            {(status === 'all' || status === 'cancelled') && (
              <Area
                type='monotone'
                dataKey='cancelled'
                stroke='var(--warning)'
                strokeWidth={2}
                fill='url(#grad-cancelled)'
                dot={false}
                activeDot={{ r: 4 }}
              />
            )}
            {status === 'all' && <ChartLegend content={<ChartLegendContent />} />}
          </AreaChart>
        </ChartContainer>
      )}
    </div>
  );
};

export const AgentOutcomesChart = () => {
  const { agents, isLoading: agentsLoading } = useAgents();
  const [selectedAgentId, setSelectedAgentId] = useState<string | null>(null);

  const agentId = selectedAgentId ?? agents[0]?.id ?? null;

  if (agentsLoading) {
    return (
      <Card>
        <CardContent className='p-4'>
          <Skeleton className='h-[210px] w-full' />
        </CardContent>
      </Card>
    );
  }

  if (agents.length === 0) {
    return (
      <Card>
        <CardContent className='flex h-[140px] items-center justify-center p-4'>
          <p className='text-sm text-muted-foreground'>
            <Trans>No agents found. Connect an agent to see execution history.</Trans>
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader className='pb-2 px-4 pt-4'>
        <div className='flex flex-wrap items-center justify-between gap-3'>
          <CardTitle className='text-base'>
            <Trans>Agent Outcomes</Trans>
          </CardTitle>
          <div className='flex overflow-hidden rounded border text-[11px] font-mono'>
            {agents.map(agent => (
              <button
                key={agent.id}
                type='button'
                onClick={() => setSelectedAgentId(agent.id)}
                className={cn(
                  'flex items-center gap-1.5 px-2.5 py-1 transition-colors',
                  agent.id === agentId
                    ? 'bg-foreground text-background'
                    : 'text-muted-foreground hover:bg-muted',
                )}
              >
                <span
                  className={cn(
                    'h-1.5 w-1.5 rounded-full',
                    agent.connected ? 'bg-success' : 'bg-muted-foreground/50',
                  )}
                />
                {agent.name}
              </button>
            ))}
          </div>
        </div>
      </CardHeader>
      <CardContent className='px-4 pb-4'>
        {agentId && <AgentChartInner agentId={agentId} />}
      </CardContent>
    </Card>
  );
};

// extensions/scylla-base/src/features/dashboard/presentation/ui/AgentOutcomesChart/AgentOutcomesChart.svelte
<script lang="ts">
  import { contextStore } from '@platform/context';
  import { createQuery } from '@scylla/core-sdk';
  import { Card, CardContent, CardHeader, CardTitle, Skeleton } from '@scylla/ui/shadcn';
  import { toRune } from '@scylla/ui/stores';
  import { cn } from '@scylla/ui/utils';
  import { t } from '@scylla/ui/i18n';
  import { agentQueries } from '@base/features/agents';
  import {
    fillBuckets,
    hasActivity,
    labelVisibility,
    monotoneAreaPath,
    monotoneLinePath,
    niceTicks,
    peakOf,
    projectPoints,
    type ChartGeometry,
    type OutcomeSeries,
  } from '../outcomes-chart.calculator.ts';
  import { dashboardMessages } from '../dashboard.messages.ts';

  type Range = '7d' | '14d' | '30d';
  type StatusFilter = 'all' | OutcomeSeries;

  const RANGES: Range[] = ['7d', '14d', '30d'];
  const RANGE_DAYS: Record<Range, number> = { '7d': 7, '14d': 14, '30d': 30 };
  const STATUS_FILTERS: StatusFilter[] = ['all', 'completed', 'failed', 'cancelled'];

  /** In SVG user units: the SVG stretches (`preserveAspectRatio="none"`). */
  const GEOMETRY: ChartGeometry = {
    width: 600,
    height: 160,
    padding: { top: 6, right: 2, bottom: 6, left: 2 },
  };

  const SERIES: { key: OutcomeSeries; color: string }[] = [
    { key: 'completed', color: 'var(--success)' },
    { key: 'failed', color: 'var(--destructive)' },
    { key: 'cancelled', color: 'var(--warning)' },
  ];

  const context = toRune(contextStore);
  const organizationId = $derived(context().organization.id ?? '');

  const agentsQuery = createQuery(() => agentQueries.byOrganization(organizationId));
  const agents = $derived(agentsQuery.data ?? []);

  let selectedAgentId = $state<string | null>(null);
  const agentId = $derived(selectedAgentId ?? agents[0]?.id ?? null);

  let range = $state<Range>('14d');
  let status = $state<StatusFilter>('all');
  let hover = $state<number | null>(null);

  const statsQuery = createQuery(() => agentQueries.statsOf(agentId ?? ''));

  const buckets = $derived(fillBuckets(statsQuery.data?.daily ?? [], RANGE_DAYS[range]));
  const shownSeries = $derived(
    status === 'all' ? SERIES : SERIES.filter(series => series.key === status),
  );
  const ticks = $derived(niceTicks(peakOf(buckets, shownSeries.map(series => series.key))));
  const axisTop = $derived(ticks[ticks.length - 1]);
  const showLabel = $derived(labelVisibility(buckets.length));

  const statusLabel = (filter: StatusFilter) =>
    t(
      {
        all: dashboardMessages.filterAll,
        completed: dashboardMessages.filterCompleted,
        failed: dashboardMessages.filterFailed,
        cancelled: dashboardMessages.filterCancelled,
      }[filter],
    );

  const seriesLabel = (key: OutcomeSeries) =>
    t(
      {
        completed: dashboardMessages.completed,
        failed: dashboardMessages.failed,
        cancelled: dashboardMessages.cancelled,
      }[key],
    );

  const pathsOf = (key: OutcomeSeries) => {
    const points = projectPoints(
      buckets.map(bucket => bucket[key]),
      axisTop,
      GEOMETRY,
    );
    return {
      line: monotoneLinePath(points),
      area: monotoneAreaPath(points, GEOMETRY.height - GEOMETRY.padding.bottom),
    };
  };
</script>

<!--
  The SVG stretches to the card; the stroke does not (`non-scaling-stroke`). Text is
  HTML beside it, or it would stretch too. Hover is one band per day.
-->
{#if agentsQuery.isLoading}
  <Card><CardContent class="p-4"><Skeleton class="h-[210px] w-full" /></CardContent></Card>
{:else if agents.length === 0}
  <Card>
    <CardContent class="flex h-[140px] items-center justify-center p-4">
      <p class="text-sm text-muted-foreground">{t(dashboardMessages.noAgents)}</p>
    </CardContent>
  </Card>
{:else}
  <Card>
    <CardHeader class="pb-2 px-4 pt-4">
      <div class="flex flex-wrap items-center justify-between gap-3">
        <CardTitle class="text-base">{t(dashboardMessages.agentOutcomes)}</CardTitle>
        <div class="flex overflow-hidden rounded border text-[11px] font-mono">
          {#each agents as agent (agent.id)}
            <button
              type="button"
              onclick={() => (selectedAgentId = agent.id)}
              aria-pressed={agent.id === agentId}
              class={cn(
                'flex items-center gap-1.5 px-2.5 py-1 transition-colors',
                agent.id === agentId
                  ? 'bg-foreground text-background'
                  : 'text-muted-foreground hover:bg-muted',
              )}
            >
              <span
                class={cn(
                  'h-1.5 w-1.5 rounded-full',
                  agent.connected ? 'bg-success' : 'bg-muted-foreground/50',
                )}
              ></span>
              {agent.name}
            </button>
          {/each}
        </div>
      </div>
    </CardHeader>

    <CardContent class="px-4 pb-4">
      <div class="space-y-3">
        <div class="flex flex-wrap items-center justify-between gap-2">
          <div class="flex overflow-hidden rounded border text-[11px] font-mono">
            {#each STATUS_FILTERS as filter (filter)}
              <button
                type="button"
                onclick={() => (status = filter)}
                aria-pressed={filter === status}
                class={cn(
                  'px-2.5 py-1 capitalize transition-colors',
                  filter === status
                    ? 'bg-foreground text-background'
                    : 'text-muted-foreground hover:bg-muted',
                )}
              >
                {statusLabel(filter)}
              </button>
            {/each}
          </div>
          <div class="flex overflow-hidden rounded border text-[11px] font-mono">
            {#each RANGES as option (option)}
              <button
                type="button"
                onclick={() => (range = option)}
                aria-pressed={option === range}
                class={cn(
                  'px-2.5 py-1 transition-colors',
                  option === range
                    ? 'bg-foreground text-background'
                    : 'text-muted-foreground hover:bg-muted',
                )}
              >
                {option}
              </button>
            {/each}
          </div>
        </div>

        {#if statsQuery.isLoading}
          <Skeleton class="h-[160px] w-full" />
        {:else if !hasActivity(buckets)}
          <div class="flex h-[160px] items-center justify-center text-center">
            <p class="text-sm text-muted-foreground">{t(dashboardMessages.noFinishedJobs)}</p>
          </div>
        {:else}
          <div class="relative pl-7">
            <div
              class="pointer-events-none absolute left-0 top-0 flex h-[160px] w-6 flex-col justify-between text-right font-mono text-[10px] text-muted-foreground"
            >
              {#each [...ticks].reverse() as tick (tick)}
                <span>{tick}</span>
              {/each}
            </div>

            <div class="relative h-[160px]">
              <svg
                viewBox={`0 0 ${GEOMETRY.width} ${GEOMETRY.height}`}
                preserveAspectRatio="none"
                class="h-full w-full overflow-visible"
                role="img"
                aria-label={t(dashboardMessages.agentOutcomes)}
              >
                <defs>
                  {#each SERIES as series (series.key)}
                    <linearGradient id={`grad-${series.key}`} x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stop-color={series.color} stop-opacity="0.25" />
                      <stop offset="95%" stop-color={series.color} stop-opacity="0" />
                    </linearGradient>
                  {/each}
                </defs>

                {#each ticks as tick (tick)}
                  {@const y =
                    GEOMETRY.padding.top +
                    (GEOMETRY.height - GEOMETRY.padding.top - GEOMETRY.padding.bottom) *
                      (1 - tick / (axisTop || 1))}
                  <line
                    x1="0"
                    x2={GEOMETRY.width}
                    y1={y}
                    y2={y}
                    class="stroke-border"
                    stroke-dasharray="3 3"
                    vector-effect="non-scaling-stroke"
                  />
                {/each}

                {#each shownSeries as series (series.key)}
                  {@const paths = pathsOf(series.key)}
                  <path d={paths.area} fill={`url(#grad-${series.key})`} />
                  <path
                    d={paths.line}
                    fill="none"
                    stroke={series.color}
                    stroke-width="2"
                    vector-effect="non-scaling-stroke"
                  />
                {/each}
              </svg>

              <div class="absolute inset-0 flex">
                {#each buckets as bucket, index (bucket.day)}
                  <!-- svelte-ignore a11y_no_static_element_interactions -->
                  <div
                    class="relative flex-1"
                    onmouseenter={() => (hover = index)}
                    onmouseleave={() => {
                      if (hover === index) hover = null;
                    }}
                  >
                    {#if hover === index}
                      <div
                        class="pointer-events-none absolute bottom-2 left-1/2 z-10 w-max -translate-x-1/2 rounded bg-foreground px-2 py-1.5 text-[10px] text-background shadow-md"
                      >
                        <p class="font-semibold">{bucket.day}</p>
                        {#each shownSeries as series (series.key)}
                          <p>
                            <span style={`color: ${series.color}`}>●</span>
                            {seriesLabel(series.key)}
                            {bucket[series.key]}
                          </p>
                        {/each}
                      </div>
                    {/if}
                  </div>
                {/each}
              </div>
            </div>

            <div class="mt-1 flex">
              {#each buckets as bucket, index (bucket.day)}
                <span
                  class={cn(
                    'flex-1 text-center font-mono text-[10px]',
                    hover === index ? 'text-foreground' : 'text-muted-foreground',
                  )}
                >
                  {showLabel[index] || hover === index ? bucket.label : ''}
                </span>
              {/each}
            </div>
          </div>

          {#if status === 'all'}
            <div class="flex flex-wrap items-center justify-center gap-4 text-xs">
              {#each SERIES as series (series.key)}
                <span class="flex items-center gap-1.5">
                  <span class="h-2 w-2 rounded-sm" style={`background: ${series.color}`}></span>
                  {seriesLabel(series.key)}
                </span>
              {/each}
            </div>
          {/if}
        {/if}
      </div>
    </CardContent>
  </Card>
{/if}
