// src/modules/features/triggers/presentation/ui/triggers-table/TriggerSourceCell.tsx
import { TriggerKind } from '@/modules/features/triggers/domain/structs/trigger-source.struct.ts';
import type { TriggerEntity } from '@/modules/features/triggers/domain/entities/trigger.entity.ts';
import { convertCronToLocal } from '@/modules/features/triggers/presentation/utils/trigger-form.utils.ts';
import { CopyableText } from '@shared/presentation/ui/data-display/CopyableText.tsx';
import { Trans } from '@lingui/react/macro';

/** Cron triggers show their expression; webhook triggers show their (copyable) URL. */
export const TriggerSourceCell = ({ trigger }: { trigger: TriggerEntity }) => {
  if (trigger.source.kind === TriggerKind.Cron) {
    return (
      <div className='flex items-center justify-center gap-2'>
        <code className='font-mono text-xs text-muted-foreground'>
          {convertCronToLocal(trigger.source.expression) || '—'}
        </code>
      </div>
    );
  }

  if (!trigger.source.webhookUrl) return <div className='w-full' />;

  return (
    <CopyableText
      value={trigger.source.webhookUrl}
      truncate={12}
      showFullOnHover
      copyLabel={<Trans>Copy url</Trans>}
      className='w-full justify-center'
    />
  );
};

// extensions/scylla-base/src/features/triggers/presentation/ui/triggers-table/TriggerSourceCell/TriggerSourceCell.svelte
<script lang="ts">
  import { CopyableText } from '@scylla/ui';
  import { t } from '@scylla/ui/i18n';
  import type { TriggerEntity } from '../../../../domain/entities/trigger.entity.ts';
  import { TriggerKind } from '../../../../domain/structs/trigger-source.struct.ts';
  import { convertCronToLocal } from '../../../utils/trigger-form.utils.ts';
  import { triggersMessages } from '../../triggers.messages.ts';

  interface Props {
    trigger: TriggerEntity;
  }

  let { trigger }: Props = $props();
</script>

{#if trigger.source.kind === TriggerKind.Cron}
  <div class="flex items-center justify-center gap-2">
    <code class="font-mono text-xs text-muted-foreground">
      {convertCronToLocal(trigger.source.expression) || '—'}
    </code>
  </div>
{:else if trigger.source.kind === TriggerKind.Webhook}
  <CopyableText
    value={trigger.source.webhookUrl}
    showFullOnHover
    copyLabel={t(triggersMessages.copyUrl)}
    class="w-full justify-center"
  />
{:else}
  <div class="flex items-center justify-center">
    <code class="font-mono text-xs text-muted-foreground">—</code>
  </div>
{/if}
