// extensions/scylla-base/src/features/triggers/presentation/ui/triggers-table/TriggerActions/TriggerActions.svelte
<script lang="ts">
  import EditIcon from '@lucide/svelte/icons/pencil';
  import Loader2Icon from '@lucide/svelte/icons/loader-2';
  import MoreHorizontalIcon from '@lucide/svelte/icons/more-horizontal';
  import PlayIcon from '@lucide/svelte/icons/play';
  import Trash2Icon from '@lucide/svelte/icons/trash-2';
  import { can, Permission } from '@platform/authz';
  import {
    buttonVariants,
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
  } from '@scylla/ui/shadcn';
  import { IconButton } from '@scylla/ui';
  import { createCompactContainer } from '@scylla/ui/state';
  import { cn } from '@scylla/ui/utils';
  import { t } from '@scylla/ui/i18n';
  import { triggersMessages } from '../../triggers.messages.ts';

  interface Props {
    onFire: (event: Event) => void;
    onEdit: (event: Event) => void;
    onDelete: (event: Event) => void;
    isFiring?: boolean;
  }

  let { onFire, onEdit, onDelete, isFiring = false }: Props = $props();

  const canManage = $derived(can(Permission.MANAGE_TRIGGERS));

  const container = createCompactContainer();
</script>

<!-- Every action writes: all hidden without `MANAGE_TRIGGERS`. A menu when the column is narrow. -->
{#if canManage}
  <div
    use:container.measure
    class="flex w-full shrink-0 items-center justify-center gap-1"
  >
    {#if container.isCompact}
      <DropdownMenu>
        <DropdownMenuTrigger
          class={cn(
            buttonVariants({ variant: 'ghost', size: 'icon' }),
            'h-8 w-8 shrink-0 rounded-full text-slate-400 hover:text-slate-900',
          )}
          onclick={(event: MouseEvent) => event.stopPropagation()}
        >
          <MoreHorizontalIcon class="h-4 w-4" />
          <span class="sr-only">{t(triggersMessages.triggerActions)}</span>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" class="w-40">
          <DropdownMenuItem onSelect={onFire} disabled={isFiring}>
            <PlayIcon class="mr-2 h-4 w-4" />
            {t(triggersMessages.fireNow)}
          </DropdownMenuItem>
          <DropdownMenuItem onSelect={onEdit}>
            <EditIcon class="mr-2 h-4 w-4" />
            {t(triggersMessages.edit)}
          </DropdownMenuItem>
          <DropdownMenuItem onSelect={onDelete} class="text-destructive">
            <Trash2Icon class="mr-2 h-4 w-4" />
            {t(triggersMessages.delete)}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    {:else}
      <IconButton
        icon={isFiring ? Loader2Icon : PlayIcon}
        tooltip={t(triggersMessages.fireNow)}
        onclick={onFire}
        busy={isFiring}
        iconClass={isFiring ? 'animate-spin' : 'fill-current'}
      />
      <IconButton icon={EditIcon} tooltip={t(triggersMessages.edit)} onclick={onEdit} />
      <IconButton
        icon={Trash2Icon}
        tooltip={t(triggersMessages.delete)}
        onclick={onDelete}
        iconClass="text-destructive"
      />
    {/if}
  </div>
{/if}

// src/modules/features/triggers/presentation/ui/triggers-table/TriggerActions.tsx
import type { SyntheticEvent } from 'react';
import { EditIcon, Loader2, MoreHorizontal, PlayIcon, Trash2 } from 'lucide-react';
import { Trans } from '@lingui/react/macro';
import { Button } from '@shadcn';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@shadcn/dropdown-menu.tsx';
import { IconButton } from '@shared/presentation/ui';
import { useCompactContainer } from '@shared/presentation/hooks/use-compact-container.ts';
import { Permission } from '@platform/authz';
import { useCan } from '@platform/authz';

interface TriggerActionsProps {
  onFire: (e: SyntheticEvent) => void;
  onEdit: (e: SyntheticEvent) => void;
  onDelete: (e: SyntheticEvent) => void;
  isFiring?: boolean;
}

/**
 * Row actions: fire now (test), edit, delete. All three write to the trigger,
 * so they hide together behind `MANAGE_TRIGGERS`.
 *
 * Switches to dropdown mode when the column gets too narrow for three buttons.
 */
export const TriggerActions = ({ onFire, onEdit, onDelete, isFiring }: TriggerActionsProps) => {
  const canManage = useCan(Permission.MANAGE_TRIGGERS);
  const { containerRef, isCompact } = useCompactContainer();

  if (!canManage) return null;

  return (
    <div ref={containerRef} className='flex w-full shrink-0 items-center justify-center gap-1'>
      {isCompact ? (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              type='button'
              size='icon'
              variant='ghost'
              className='h-8 w-8 shrink-0 rounded-full text-slate-400 hover:text-slate-900'
            >
              <MoreHorizontal className='h-4 w-4' />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align='end' className='w-40'>
            <DropdownMenuItem onClick={onFire} disabled={isFiring}>
              <PlayIcon className='mr-2 h-4 w-4' />
              <Trans>Fire now</Trans>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={onEdit}>
              <EditIcon className='mr-2 h-4 w-4' />
              <Trans>Edit</Trans>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={onDelete} className='text-destructive'>
              <Trash2 className='mr-2 h-4 w-4' />
              <Trans>Delete</Trans>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      ) : (
        <>
          <IconButton
            icon={isFiring ? Loader2 : PlayIcon}
            tooltip={<Trans>Fire now</Trans>}
            onClick={onFire}
            busy={isFiring}
            iconClassName={isFiring ? 'animate-spin' : 'fill-current'}
          />
          <IconButton icon={EditIcon} tooltip={<Trans>Edit</Trans>} onClick={onEdit} />
          <IconButton
            icon={Trash2}
            tooltip={<Trans>Delete</Trans>}
            onClick={onDelete}
            iconClassName='text-destructive'
          />
        </>
      )}
    </div>
  );
};
