// extensions/scylla-base/src/features/triggers/presentation/ui/triggers-table/TriggersTable.svelte
<script lang="ts">
  import { SvelteSet } from 'svelte/reactivity';
  import ClockIcon from '@lucide/svelte/icons/clock';
  import HelpCircleIcon from '@lucide/svelte/icons/help-circle';
  import WebhookIcon from '@lucide/svelte/icons/webhook';
  import { scyllaNavigate } from '@platform/context';
  import { createMutation } from '@scylla/core-sdk';
  import { Switch } from '@scylla/ui/shadcn';
  import {
    ConfirmOperationAlertDialog,
    CopyableText,
    DataTable,
  } from '@scylla/ui';
  import { createSelection } from '@scylla/ui/state';
  import { t } from '@scylla/ui/i18n';
  import type { TriggerEntity } from '../../../domain/entities/trigger.entity.ts';
  import { TriggerKind } from '../../../domain/structs/trigger-source.struct.ts';
  import { triggerMutations } from '../../triggers.queries.ts';
  import TriggerActions from './TriggerActions/TriggerActions.svelte';
  import TriggerSourceCell from './TriggerSourceCell/TriggerSourceCell.svelte';
  import TriggerStatusCell from './TriggerStatusCell/TriggerStatusCell.svelte';
  import TriggerFormDialog from '../dialogs/TriggerFormDialog/TriggerFormDialog.svelte';
  import { triggerColumns } from './trigger-columns.ts';
  import { triggersMessages } from '../triggers.messages.ts';

  interface Props {
    triggers: TriggerEntity[];
    pipelineId: string;
    pipelineName: string;
  }

  let { triggers, pipelineId, pipelineName }: Props = $props();

  const SOURCE_ICON = {
    [TriggerKind.Cron]: ClockIcon,
    [TriggerKind.Webhook]: WebhookIcon,
    [TriggerKind.Unknown]: HelpCircleIcon,
  } as const;

  const selection = createSelection('triggers');
  const deleteTrigger = createMutation(() => triggerMutations.remove(pipelineId));
  const setEnabled = createMutation(() => triggerMutations.setEnabled(pipelineId));
  const fireNow = createMutation(() => triggerMutations.fireNow(pipelineId));

  let editTarget = $state<TriggerEntity | null>(null);
  let deleteTargetId = $state<string | null>(null);
  const firingIds = new SvelteSet<string>();

  const handleFire = (trigger: TriggerEntity) => {
    firingIds.add(trigger.id);

    fireNow
      .mutateAsync(trigger.id)
      // Go to the run just created.
      .then(() => scyllaNavigate.goToJobs(pipelineId, pipelineName))
      .catch(() => {
        // The global mutation handler toasts the error.
      })
      .finally(() => {
        firingIds.delete(trigger.id);
      });
  };

  const columns = $derived(
    triggerColumns({
      name: nameCell,
      source: sourceCell,
      status: statusCell,
      enabled: enabledCell,
      actions: actionsCell,
    }),
  );
</script>

{#snippet nameCell(trigger: TriggerEntity)}
  {@const Icon = SOURCE_ICON[trigger.source.kind]}
  <div class="flex w-full min-w-0 flex-row items-center gap-3">
    <div class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10">
      <Icon class="size-4 text-primary" />
    </div>
    <div class="flex min-w-0 flex-col text-start">
      <p class="truncate font-semibold text-foreground">{trigger.name}</p>
      <CopyableText
        class="text-xs text-muted-foreground/80"
        value={trigger.id}
        display={`ID: ${trigger.id}`}
      />
    </div>
  </div>
{/snippet}

{#snippet sourceCell(trigger: TriggerEntity)}
  <TriggerSourceCell {trigger} />
{/snippet}

{#snippet statusCell(trigger: TriggerEntity)}
  <TriggerStatusCell {trigger} />
{/snippet}

{#snippet enabledCell(trigger: TriggerEntity)}
  <!-- Toggling the switch must not select the row. -->
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="flex justify-center" onclick={event => event.stopPropagation()}>
    <Switch
      checked={trigger.enabled}
      onCheckedChange={checked => setEnabled.mutate({ triggerId: trigger.id, enabled: checked })}
      aria-label={t(triggersMessages.toggleEnabled(trigger.name))}
    />
  </div>
{/snippet}

{#snippet actionsCell(trigger: TriggerEntity)}
  <TriggerActions
    isFiring={firingIds.has(trigger.id)}
    onFire={event => {
      event.stopPropagation();
      handleFire(trigger);
    }}
    onEdit={event => {
      event.stopPropagation();
      editTarget = trigger;
    }}
    onDelete={event => {
      event.stopPropagation();
      deleteTargetId = trigger.id;
    }}
  />
{/snippet}

<DataTable
  {columns}
  data={triggers}
  onRowClick={row => selection.select(row.original.id)}
  getRowId={trigger => trigger.id}
  isRowSelected={trigger => selection.selectedIds.includes(trigger.id)}
  alignColumnsCenter
/>

{#if editTarget}
  <TriggerFormDialog
    open
    onOpenChange={open => {
      if (!open) editTarget = null;
    }}
    {pipelineId}
    trigger={editTarget}
  />
{/if}

<ConfirmOperationAlertDialog
  open={deleteTargetId !== null}
  onOpenChange={open => {
    if (!open) deleteTargetId = null;
  }}
  onContinue={() => {
    if (!deleteTargetId) return;
    deleteTrigger.mutate(deleteTargetId);
    deleteTargetId = null;
  }}
/>

// src/modules/features/triggers/presentation/ui/triggers-table/TriggersTable.tsx
import { useState } from 'react';
import { DataTable } from '@shared/presentation/ui/data-display/DataTable.tsx';
import { ConfirmOperationAlertDialog } from '@shared/presentation/ui/feedback/ConfirmOperationAlertDialog.tsx';
import { useSelection } from '@shared/presentation/hooks/use-selection.ts';
import { useScyllaNavigate } from '@platform/context';
import type { TriggerEntity } from '@/modules/features/triggers/domain/entities/trigger.entity.ts';
import { useDeleteTrigger } from '@/modules/features/triggers/presentation/hooks/use-delete-trigger.ts';
import { useSetTriggerEnabled } from '@/modules/features/triggers/presentation/hooks/use-set-trigger-enabled.ts';
import { useFireTriggerNow } from '@/modules/features/triggers/presentation/hooks/use-fire-trigger-now.ts';
import { TriggerFormDialog } from '@/modules/features/triggers/presentation/ui/dialogs/TriggerFormDialog.tsx';
import { createTriggerColumns } from './columns.tsx';

interface TriggersTableProps {
  triggers: TriggerEntity[];
  pipelineId: string;
  pipelineName: string;
}

export const TriggersTable = ({ triggers, pipelineId, pipelineName }: TriggersTableProps) => {
  const { selectedIds, select } = useSelection('triggers');
  const { goToJobs } = useScyllaNavigate();
  const deleteTrigger = useDeleteTrigger(pipelineId);
  const setEnabled = useSetTriggerEnabled(pipelineId);
  const fireNow = useFireTriggerNow(pipelineId);

  const [editTarget, setEditTarget] = useState<TriggerEntity | null>(null);
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null);
  const [firingIds, setFiringIds] = useState<Set<string>>(new Set());

  const handleFire = (trigger: TriggerEntity) => {
    setFiringIds(prev => new Set(prev).add(trigger.id));
    fireNow
      .mutateAsync(trigger.id)
      // Close the loop: land on the run we just created.
      .then(() => goToJobs(pipelineId, pipelineName))
      .catch(() => {
        // Toast shown by the global MutationCache onError handler.
      })
      .finally(() =>
        setFiringIds(prev => {
          const next = new Set(prev);
          next.delete(trigger.id);
          return next;
        }),
      );
  };

  const columns = createTriggerColumns({
    onFire: handleFire,
    onEdit: trigger => setEditTarget(trigger),
    onDelete: triggerId => setDeleteTargetId(triggerId),
    onToggleEnabled: (trigger, enabled) => setEnabled.mutate({ triggerId: trigger.id, enabled }),
    firingIds,
  });

  return (
    <>
      <DataTable
        columns={columns}
        data={triggers}
        onRowClick={row => select(row.original.id)}
        getRowId={row => row.id}
        isRowSelected={row => selectedIds.includes(row.id)}
        alignColumnsCenter
      />

      {editTarget && (
        <TriggerFormDialog
          open={editTarget !== null}
          onOpenChange={open => {
            if (!open) setEditTarget(null);
          }}
          pipelineId={pipelineId}
          trigger={editTarget}
        />
      )}

      <ConfirmOperationAlertDialog
        open={deleteTargetId !== null}
        onOpenChange={open => {
          if (!open) setDeleteTargetId(null);
        }}
        onContinue={() => {
          if (!deleteTargetId) return;
          deleteTrigger.mutate(deleteTargetId);
          setDeleteTargetId(null);
        }}
      />
    </>
  );
};
