// src/modules/features/roles/presentation/ui/components/role-detail/RoleDetailPermissions.tsx
import { Trans } from '@lingui/react/macro';
import { Badge } from '@shadcn';
import type { RoleEntity } from '@/modules/features/roles/domain/entities/role.entity.ts';
import { usePermissionLabels } from '@/modules/features/roles/presentation/hooks/use-permission-labels.ts';

interface RoleDetailPermissionsProps {
  role: RoleEntity;
}

export const RoleDetailPermissions = ({ role }: RoleDetailPermissionsProps) => {
  const { permissionLabel } = usePermissionLabels();

  return (
    <section className='flex flex-col gap-2'>
      <h3 className='text-xs font-semibold uppercase tracking-wider text-muted-foreground'>
        <Trans>Permissions</Trans>
      </h3>
      {role.access.kind === 'fullControl' ? (
        <p className='text-sm text-muted-foreground'>
          <Trans>Grants full control over its scope.</Trans>
        </p>
      ) : role.access.kind === 'restricted' ? (
        role.access.permissions.length === 0 ? (
          <p className='text-sm text-muted-foreground'>
            <Trans>No permissions.</Trans>
          </p>
        ) : (
          <div className='flex flex-wrap gap-1.5'>
            {role.access.permissions.map(permission => (
              <Badge key={permission} variant='outline' className='font-normal'>
                {permissionLabel(permission, role.scope)}
              </Badge>
            ))}
          </div>
        )
      ) : (
        <p className='text-sm text-muted-foreground'>
          <Trans>Unknown access.</Trans>
        </p>
      )}
    </section>
  );
};

export default RoleDetailPermissions;

// src/modules/features/roles/presentation/ui/components/role-detail/RoleDetailPermissions.svelte
<script lang="ts">
  import { Badge } from '@shadcn';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { RoleEntity } from '../../../../domain/entities/role.entity.ts';
  import { permissionLabelOf } from '../../../utils/permission-mapping.ts';
  import { rolesMessages } from '../../roles.messages.ts';

  interface Props {
    role: RoleEntity;
  }

  let { role }: Props = $props();
</script>

<section class="flex flex-col gap-2">
  <h3 class="text-xs font-semibold tracking-wider text-muted-foreground uppercase">
    {t(rolesMessages.permissions)}
  </h3>
  {#if role.access.kind === 'fullControl'}
    <p class="text-sm text-muted-foreground">{t(rolesMessages.grantsFullControl)}</p>
  {:else if role.access.kind === 'restricted'}
    {#if role.access.permissions.length === 0}
      <p class="text-sm text-muted-foreground">{t(rolesMessages.noPermissions)}</p>
    {:else}
      <div class="flex flex-wrap gap-1.5">
        {#each role.access.permissions as permission (permission)}
          <!-- Labelled against the role's scope: an organization role says "every project". -->
          <Badge variant="outline" class="font-normal">
            {permissionLabelOf(permission, role.scope)}
          </Badge>
        {/each}
      </div>
    {/if}
  {:else}
    <p class="text-sm text-muted-foreground">{t(rolesMessages.unknownAccess)}</p>
  {/if}
</section>
