// src/modules/features/secret/presentation/ui/Secret.page.svelte
<script lang="ts">
  import { createQuery } from '@platform/query';
  import { secretQueries } from '../secret.queries.ts';
  import CreateSecretDialog from './CreateSecretDialog/CreateSecretDialog.svelte';
  import SecretHeader from './components/SecretHeader.svelte';
  import SecretList from './components/SecretList/SecretList.svelte';

  interface Props {
    projectId?: string;
  }

  let { projectId }: Props = $props();

  // The children need a defined id, so the page still checks it.
  const secretsQuery = createQuery(() => secretQueries.byProject(projectId ?? ''));
  const secrets = $derived(secretsQuery.data ?? []);

  let isCreateDialogOpen = $state(false);
</script>

{#if projectId}
  <div class="flex min-h-full w-full flex-col gap-4">
    <SecretHeader
      {projectId}
      activeCount={secrets.length}
      secretIds={secrets.map(secret => secret.id)}
      onAddSecret={() => (isCreateDialogOpen = true)}
    />
    <div class="overflow-hidden">
      <SecretList {secrets} {projectId} />
      <CreateSecretDialog
        {projectId}
        isOpen={isCreateDialogOpen}
        setOpen={open => (isCreateDialogOpen = open)}
      />
    </div>
  </div>
{/if}

// src/modules/features/secret/presentation/ui/Secret.page.tsx
import { useSecrets } from '@/modules/features/secret/presentation/hooks/use-secrets.ts';
import {
  SecretHeader,
  SecretList,
} from '@/modules/features/secret/presentation/ui/components/index.ts';
import { useParams } from 'react-router-dom';
import { CreateSecretDialog } from '@/modules/features/secret/presentation/ui/CreateSecretDialog.tsx';
import { useState } from 'react';

export const SecretPage = () => {
  const { projectId } = useParams();

  const { secrets } = useSecrets(projectId!);

  const [isCreateDialogOpen, setCreateIsDialogOpen] = useState(false);

  if (projectId == undefined) return <></>;

  return (
    <div className='flex flex-col gap-4 w-full min-h-full'>
      <SecretHeader
        projectId={projectId}
        activeCount={secrets.length}
        secretIds={secrets.map(secret => secret.id)}
        onAddSecret={() => {
          setCreateIsDialogOpen(true);
        }}
      />
      <div className='overflow-hidden'>
        <SecretList secrets={secrets} projectId={projectId} />
        <CreateSecretDialog
          projectId={projectId}
          isOpen={isCreateDialogOpen}
          setOpen={setCreateIsDialogOpen}
        />
      </div>
    </div>
  );
};

export default SecretPage;
