// src/modules/features/pipeline-dashboard/presentation/ui/PipelineChart.tsx
import { cn } from '@shared/presentation/utils';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/modules/shared/presentation/ui/shadcn/tooltip';
import {
  mapJobStatusToChartStatus,
  type ChartDataPoint,
} from '@/modules/shared/utils/jobStatusMapper';
import {
  calculateDuration,
  formatDuration,
  getRelativeTime,
} from '@/modules/shared/utils/dateUtils';
import { Skeleton } from '@/modules/shared/presentation/ui/shadcn/skeleton';
import type { JobResponse } from '@/generated/job.ts';

type PipelineChartProps = {
  maxJobs?: number;
  jobs: JobResponse[];
  isLoading?: boolean;
  isError?: boolean;
};

export const PipelineChart = ({ jobs, isLoading, isError, maxJobs }: PipelineChartProps) => {
  // Transform jobs to chart data points

  const chartData: ChartDataPoint[] = jobs
    .slice(0, maxJobs)
    .map((job, index) => ({
      jobId: job.jobId,
      status: mapJobStatusToChartStatus(job.status),
      createdAt: job.createdAt,
      updatedAt: job.updatedAt,
      duration: calculateDuration(job.createdAt, job.updatedAt),
      runNumber: jobs.length - index,
    }))
    .reverse(); // Reverse to show oldest first (left) to newest (right)

  // Loading state
  if (isLoading) {
    return (
      <div className='w-full flex items-center gap-2 h-10 py-1 overflow-hidden rounded-md px-1'>
        {[...Array(maxJobs)].map((_, index) => (
          <Skeleton key={index} className='flex-1 min-w-[4px] h-full rounded-sm' />
        ))}
      </div>
    );
  }

  // Error state
  if (isError) {
    return (
      <div className='w-full flex items-center justify-center h-10 py-1'>
        <span className='text-xs text-slate-400 italic'>Error loading jobs</span>
      </div>
    );
  }

  // Empty state
  if (chartData.length === 0) {
    return (
      <div className='w-full flex items-center justify-center h-10 py-1'>
        <span className='text-xs text-slate-400 italic'>No jobs yet</span>
      </div>
    );
  }

  return (
    <TooltipProvider delayDuration={100}>
      <div className='w-full flex items-center gap-2 h-10 py-1 overflow-hidden rounded-md px-1'>
        {chartData.map(dataPoint => {
          const statusLabel =
            dataPoint.status === 1 ? 'Success' : dataPoint.status === 0 ? 'Failed' : 'Running...';

          return (
            <Tooltip key={dataPoint.jobId}>
              <TooltipTrigger asChild>
                <div
                  className={cn(
                    'flex-1 min-w-[4px] h-full rounded-sm transition-all duration-150 cursor-help',

                    // Success
                    dataPoint.status === 1 &&
                      'bg-emerald-400/80 hover:bg-emerald-500 hover:scale-y-110',

                    // Error
                    dataPoint.status === 0 && 'bg-red-400/80 hover:bg-red-500 hover:scale-y-110',

                    // running
                    dataPoint.status === 2 &&
                      'bg-blue-500 animate-[smooth-pulse_2s_infinite] ring-4 ring-blue-400/30 ring-inset hover:scale-y-110',
                  )}
                />
              </TooltipTrigger>
              <TooltipContent side='top' className='text-xs p-3 shadow-lg border-slate-200'>
                <div className='flex flex-col gap-1.5'>
                  <div className='flex items-center justify-between gap-4'>
                    <span className='font-bold text-slate-400'>Run #{dataPoint.runNumber}</span>
                    <span className='text-[10px] text-slate-400 font-mono'>
                      {dataPoint.jobId.slice(0, 8)}...
                    </span>
                  </div>

                  <div className='flex items-center gap-2'>
                    <div
                      className={cn(
                        'w-2 h-2 rounded-full',
                        dataPoint.status === 1 && 'bg-emerald-500',
                        dataPoint.status === 0 && 'bg-red-500',
                        dataPoint.status === 2 && 'bg-blue-500 animate-pulse',
                      )}
                    />
                    <span
                      className={cn(
                        'font-semibold',
                        dataPoint.status === 1 && 'text-emerald-600',
                        dataPoint.status === 0 && 'text-red-600',
                        dataPoint.status === 2 && 'text-blue-600',
                      )}
                    >
                      {statusLabel}
                    </span>
                  </div>

                  <span className='text-[10px] text-slate-500 italic border-t border-slate-100 pt-1 mt-1'>
                    {dataPoint.status === 2
                      ? `Started ${getRelativeTime(dataPoint.createdAt)}`
                      : `Finished ${getRelativeTime(dataPoint.updatedAt)}`}{' '}
                    • Duration: {formatDuration(dataPoint.duration)}
                  </span>
                </div>
              </TooltipContent>
            </Tooltip>
          );
        })}
      </div>
    </TooltipProvider>
  );
};

// src/modules/features/pipeline/presentation/ui/dashboard/PipelineChart.svelte
<script lang="ts">
  import type { JobEntity } from '@/modules/features/jobs';
  import { Skeleton } from '@shadcn';
  import { StatusBar, type StatusBarItem } from '@shared/presentation/ui';
  import { cn } from '@shared/presentation/utils';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { calculateDuration, formatDuration, getRelativeTime } from '@shared/utils/date-utils.ts';
  import { getStatusConfig } from '@shared/utils/status-config.ts';
  import { pipelineMessages } from '../../pipeline.messages.ts';

  interface Props {
    jobs: JobEntity[];
    maxJobs?: number;
    isLoading?: boolean;
    isError?: boolean;
    /** The history was not fetched: the user may not list this project's jobs. */
    isForbidden?: boolean;
    onSelectJob?: (jobId: string) => void;
  }

  let { jobs, maxJobs, isLoading = false, isError = false, isForbidden = false, onSelectJob }: Props =
    $props();

  type RunItem = StatusBarItem & { job: JobEntity; runNumber: number };

  const items = $derived.by((): RunItem[] =>
    jobs
      .slice(0, maxJobs)
      .map((job, index) => ({
        id: job.id,
        status: job.status,
        // Oldest on the left: run numbers count up.
        runNumber: jobs.length - index,
        job,
        label: t(pipelineMessages.runNumber(jobs.length - index)),
        onSelect: onSelectJob ? () => onSelectJob(job.id) : undefined,
      }))
      .reverse(),
  );
</script>

{#snippet runTooltip(item: RunItem)}
  {@const config = getStatusConfig(item.job.status)}
  {@const duration = calculateDuration(item.job.createdAt, item.job.updatedAt)}
  <div class="flex flex-col gap-1.5">
    <div class="flex items-center justify-between gap-4">
      <span class="font-bold text-muted-foreground">{t(pipelineMessages.runNumber(item.runNumber))}</span>
      <span class="font-mono text-[10px] text-muted-foreground">{item.job.id.slice(0, 8)}...</span>
    </div>
    <div class="flex items-center gap-2">
      <div class={cn('h-2 w-2 rounded-full', config.dotClassName)}></div>
      <span class={cn('font-semibold', config.textClassName)}>{t(config.label)}</span>
    </div>
    <span class="mt-1 border-t pt-1 text-[10px] text-muted-foreground italic">
      {item.job.status === 'running' || item.job.status === 'pending'
        ? t(pipelineMessages.startedAt(getRelativeTime(item.job.createdAt)))
        : t(pipelineMessages.finishedAt(getRelativeTime(item.job.updatedAt)))}
      • {t(pipelineMessages.durationOf(formatDuration(duration)))}
    </span>
  </div>
{/snippet}

{#if isLoading}
  <div class="flex h-10 w-full items-center gap-2 overflow-hidden rounded-md px-1 py-1">
    {#each { length: maxJobs ?? 0 } as _, index (index)}
      <Skeleton class="h-full min-w-[4px] flex-1 rounded-sm" />
    {/each}
  </div>
{:else if isForbidden}
  <!-- Before the error state: nothing was asked, so nothing failed. -->
  <div class="flex h-10 w-full items-center justify-center py-1">
    <span class="text-xs text-muted-foreground italic">{t(pipelineMessages.jobsForbidden)}</span>
  </div>
{:else if isError}
  <div class="flex h-10 w-full items-center justify-center py-1">
    <span class="text-xs text-muted-foreground italic">{t(pipelineMessages.jobsError)}</span>
  </div>
{:else}
  <StatusBar
    {items}
    tooltip={runTooltip}
    emptyLabel={t(pipelineMessages.noJobsYet)}
    height="h-10"
    class="px-1"
  />
{/if}
