// extensions/scylla-base/src/features/pipeline/presentation/ui/dashboard/PipelineDashboardHeader.svelte
<script lang="ts">
  import KeyIcon from '@lucide/svelte/icons/key';
  import UsersIcon from '@lucide/svelte/icons/users';
  import { Permission, can } from '@platform/authz';
  import { scyllaNavigate } from '@platform/context';
  import { createMutation } from '@scylla/core-sdk';
  import { Button } from '@scylla/ui/shadcn';
  import { FeatureHeader } from '@scylla/ui';
  import { createFeatureSelection } from '@scylla/ui/state';
  import { t } from '@scylla/ui/i18n';
  import { pipelineMutations } from '../../pipeline.queries.ts';
  import { pipelineMessages } from '../../pipeline.messages.ts';

  interface Props {
    numberOfPipelines: number;
    pipelineIds: string[];
  }

  let { numberOfPipelines, pipelineIds }: Props = $props();

  const deletePipeline = createMutation(() => pipelineMutations.remove());

  // A getter: the ids arrive later.
  const selection = createFeatureSelection('pipelines', () => pipelineIds, {
    deleteItem: id => deletePipeline.mutateAsync(id),
  });

  const canCreate = $derived(can(Permission.CREATE_PIPELINE));
  const canDelete = $derived(can(Permission.DELETE_PIPELINE));
  const canListMembers = $derived(can(Permission.LIST_PROJECT_MEMBERS));
  const canListSecrets = $derived(can(Permission.LIST_SECRETS));
</script>

{#snippet projectShortcuts()}
  {#if canListMembers}
    <Button variant="outline" onclick={() => scyllaNavigate.goToSubRoute('members')}>
      <UsersIcon class="text-primary" />
      {t(pipelineMessages.members)}
    </Button>
  {/if}
  {#if canListSecrets}
    <Button variant="outline" onclick={() => scyllaNavigate.goToSubRoute('secrets')}>
      <KeyIcon class="text-primary" />
      {t(pipelineMessages.secrets)}
    </Button>
  {/if}
{/snippet}

<div class="flex w-full items-center gap-4">
  <FeatureHeader
    count={numberOfPipelines}
    label={t(pipelineMessages.pipeline)}
    pluralLabel={t(pipelineMessages.pipelines)}
    onNew={() => scyllaNavigate.goToCreatePipeline()}
    newLabel={t(pipelineMessages.newPipeline)}
    canNew={canCreate}
    newDeniedReason={t(pipelineMessages.createDenied)}
    {canDelete}
    deleteDeniedReason={t(pipelineMessages.deleteDenied)}
    extraActions={projectShortcuts}
    {...selection.headerProps}
  />
</div>

// src/modules/features/pipeline/presentation/ui/dashboard/PipelineDashboardHeader.tsx
import { useScyllaNavigate } from '@platform/context';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { Trans } from '@lingui/react/macro';
import { FeatureHeader } from '@shared/presentation/ui';
import { useDeletePipeline } from '@/modules/features/pipeline/presentation/hooks/use-delete-pipeline.ts';
import { Button } from '@shadcn';
import { KeyIcon, Users } from 'lucide-react';
import { Permission } from '@platform/authz';
import { useCan } from '@platform/authz';
import { Can } from '@platform/authz';

interface PipelineDashboardHeaderProps {
  numberOfPipelines: number;
  pipelineIds: string[];
}

export const PipelineDashboardHeader = ({
  numberOfPipelines,
  pipelineIds,
}: PipelineDashboardHeaderProps) => {
  const { goToCreatePipeline, goToSubRoute } = useScyllaNavigate();
  const deletePipeline = useDeletePipeline();
  const { headerProps } = useFeatureSelection('pipelines', pipelineIds, {
    deleteItem: id => deletePipeline.mutateAsync(id),
  });

  const canCreate = useCan(Permission.CREATE_PIPELINE);
  const canDelete = useCan(Permission.DELETE_PIPELINE);

  return (
    <div className='flex items-center gap-4 w-full'>
      <FeatureHeader
        count={numberOfPipelines}
        label={<Trans>Pipeline</Trans>}
        pluralLabel={<Trans>Pipelines</Trans>}
        {...headerProps}
        onNew={goToCreatePipeline}
        newLabel={<Trans>New pipeline</Trans>}
        canNew={canCreate}
        newDeniedReason={<Trans>You don't have permission to create pipelines.</Trans>}
        canDelete={canDelete}
        deleteDeniedReason={<Trans>You don't have permission to delete pipelines.</Trans>}
        extraActions={
          <>
            {/* The project dashboard is where someone stands when they think
                about who works on the project, so its member page opens from
                here rather than from a separate administration screen. */}
            <Can permission={Permission.LIST_PROJECT_MEMBERS}>
              <Button variant={'outline'} onClick={() => goToSubRoute('members')}>
                <Users className={'text-primary'} />
                <Trans>Members</Trans>
              </Button>
            </Can>
            <Can permission={Permission.LIST_SECRETS}>
              <Button variant={'outline'} onClick={() => goToSubRoute('secrets')}>
                <KeyIcon className={'text-primary'} />
                <Trans>Secrets</Trans>
              </Button>
            </Can>
          </>
        }
      />
    </div>
  );
};
