// src/modules/features/secret/presentation/ui/CreateSecretDialog.tsx
import { FormDialog } from '@shared/presentation/ui';
import { createSecretsItems } from '@/modules/features/secret/presentation/utils/createSecretItems.ts';
import { useCreateSecret } from '@/modules/features/secret/presentation/hooks/use-secrets.ts';
import type { FormValues } from '@shared/presentation/structs/scylla-form.struct.ts';
import { Trans } from '@lingui/react/macro';

interface CreateSecretDialogProps {
  isOpen: boolean;
  setOpen: (open: boolean) => void;
  projectId: string;
  name?: string;
  description?: string;
}

export const CreateSecretDialog = ({ projectId, isOpen, setOpen }: CreateSecretDialogProps) => {
  const createSecret = useCreateSecret(projectId);

  const handleSubmit = ({
    name,
    description,
    value,
  }: FormValues<'name' | 'description' | 'value'>) => {
    if (!name.trim() || !value.trim()) return;

    createSecret.mutate({ name, description: description.trim(), value });
    setOpen(false);
  };
  return (
    <FormDialog
      open={isOpen}
      onOpenChange={setOpen}
      title={<Trans>Create secret</Trans>}
      items={createSecretsItems()}
      onSubmit={handleSubmit}
    />
  );
};

// extensions/scylla-base/src/features/secret/presentation/ui/CreateSecretDialog/CreateSecretDialog.svelte
<script lang="ts">
  import { createMutation } from '@scylla/core-sdk';
  import { FormDialog, type FormValues } from '@scylla/ui';
  import { t, activeLocale } from '@scylla/ui/i18n';
  import { secretMutations } from '../../secret.queries.ts';
  import { createSecretsItems } from '../../utils/createSecretItems.ts';
  import { secretMessages } from '../secret.messages.ts';

  interface Props {
    projectId: string;
    isOpen: boolean;
    setOpen: (open: boolean) => void;
  }

  let { projectId, isOpen, setOpen }: Props = $props();

  const createSecret = createMutation(() => secretMutations.create(projectId));

  // Reading the locale rebuilds the labels on a switch.
  const items = $derived((activeLocale(), createSecretsItems()));

  const handleSubmit = ({
    name,
    description,
    value,
  }: FormValues<'name' | 'description' | 'value'>) => {
    // Rejects whitespace-only input.
    if (!name.trim() || !value.trim()) return;

    createSecret.mutate({ name, description: description.trim(), value });
    setOpen(false);
  };
</script>

<FormDialog
  open={isOpen}
  onOpenChange={setOpen}
  title={t(secretMessages.createSecret)}
  {items}
  onSubmit={handleSubmit}
/>
