// src/modules/features/marketplace/presentation/ui/MarketItemList.tsx
//TODO: move that into domain
import MarketItemCard from '@/modules/features/marketplace/presentation/ui/MarketItemCard.tsx';
import type { MarketItem } from '@/modules/features/marketplace/domain/structs/market-item.struct.ts';

export type MarketItemListProps = {
  items: MarketItem[] | undefined;
  filter: string;
};

export const MarketItemList = ({ items, filter }: MarketItemListProps) => {
  return (
    <div className={'flex flex-row flex-wrap h-fit gap-4'}>
      {items?.map((item, index) => {
        if (
          item.title.toLowerCase().includes(filter.toLowerCase()) ||
          item.provider.toLowerCase().includes(filter.toLowerCase())
        )
          return (
            <MarketItemCard
              key={index}
              className='flex-1 min-w-[300px] max-w-[400px] h-50'
              provider={item.provider}
              title={item.title}
              descrption={item.descrption}
            />
          );
        else {
          return <></>;
        }
      })}
    </div>
  );
};

// extensions/scylla-base/src/features/marketplace/presentation/ui/MarketItemList/MarketItemList.svelte
<script lang="ts">
  import type { MarketItem } from '../../../domain/structs/market-item.struct.ts';
  import { matchesFilter } from '../../marketplace-filter.state.svelte.ts';
  import MarketItemCard from '../MarketItemCard.svelte';

  interface Props {
    items: MarketItem[] | undefined;
    filter: string;
  }

  let { items, filter }: Props = $props();

  // Keyed on the title, filtered before the loop.
  const visible = $derived((items ?? []).filter(item => matchesFilter(item, filter)));
</script>

<div class="flex h-fit flex-row flex-wrap gap-4">
  {#each visible as item (item.title)}
    <MarketItemCard
      class="h-50 max-w-[400px] min-w-[300px] flex-1"
      provider={item.provider}
      title={item.title}
      descrption={item.descrption}
    />
  {/each}
</div>
