// src/modules/features/pipeline/presentation/ui/dashboard/DashboardPipeline.page.tsx
import { useParams } from 'react-router-dom';
import { usePipelinesMetadata } from '../../hooks/use-pipelines-metadata.ts';
import { usePipelineJobs } from '../../hooks/use-pipeline-jobs.ts';
import { ErrorState } from '@shared/presentation/ui/feedback/ErrorState.tsx';
import { Trans } from '@lingui/react/macro';
import { Pagination } from '@shared/presentation/ui/data-display/Pagination.tsx';
import { PipelineDashboardHeader } from '@/modules/features/pipeline/presentation/ui/dashboard/PipelineDashboardHeader.tsx';
import { PipelineTable } from '@/modules/features/pipeline/presentation/ui/dashboard/pipeline-table/PipelineTable.tsx';

export const DashboardPipelinePage = () => {
  const { projectId } = useParams();
  const { isLoading, pipelines, isError, errorMessage, paginationInfo, setPage } =
    usePipelinesMetadata(projectId!);

  const pipelineIds = (pipelines?.items ?? []).map(p => p.id);
  const { jobsByPipelineId, isJobsError, isJobsLoading, canListJobs } =
    usePipelineJobs(pipelineIds);

  if (isLoading || !pipelines) {
    return <></>;
  }

  if (isError) {
    return <ErrorState message={String(errorMessage) || 'Unable to load pipelines'} />;
  }

  return (
    <div className='flex flex-col gap-4 w-full h-full'>
      <PipelineDashboardHeader
        numberOfPipelines={paginationInfo?.totalCount ?? pipelines.items.length}
        pipelineIds={pipelineIds}
      />
      <div className='flex-1 min-h-0 overflow-auto'>
        <div className='relative'>
          {pipelines.items.length > 0 ? (
            <PipelineTable
              pipelines={pipelines.items}
              jobsByPipelineId={jobsByPipelineId}
              isJobsError={isJobsError}
              isJobsLoading={isJobsLoading}
              canListJobs={canListJobs}
            />
          ) : (
            <div className='flex items-center justify-center h-full min-h-100'>
              <div className='text-center space-y-2'>
                <p className='text-muted-foreground'>
                  <Trans>No pipeline found</Trans>
                </p>
                <p className='text-sm text-muted-foreground'>
                  <Trans>Create your first pipeline to get started</Trans>
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
      {paginationInfo && paginationInfo.totalPages > 1 && (
        <div className='shrink-0 pt-2'>
          <Pagination paginationInfo={paginationInfo} onPageChange={setPage} />
        </div>
      )}
    </div>
  );
};

// extensions/scylla-base/src/features/pipeline/presentation/ui/dashboard/DashboardPipeline/DashboardPipeline.page.svelte
<script lang="ts">
  import { ErrorState, PaginationSlot } from '@scylla/ui';
  import { t } from '@scylla/ui/i18n';
  import { createPipelineDashboard } from '../../../pipeline-dashboard.state.svelte.ts';
  import { createRunPipeline } from '../../../run-pipeline.svelte.ts';
  import { pipelineMessages } from '../../../pipeline.messages.ts';
  import PipelineDashboardHeader from '../PipelineDashboardHeader.svelte';
  import PipelineTable from '../pipeline-table/PipelineTable.svelte';

  interface Props {
    projectId?: string;
  }

  let { projectId }: Props = $props();

  const dashboard = createPipelineDashboard(() => projectId ?? '');
  const runPipeline = createRunPipeline();
</script>

{#if dashboard.isError}
  <ErrorState message={dashboard.errorMessage} />
{:else}
  <!-- The frame renders first: the table area's height decides what to fetch. -->
  <div data-tour="pipelines" class="flex h-full min-h-0 w-full flex-col gap-4">
    <PipelineDashboardHeader
      numberOfPipelines={dashboard.totalCount}
      pipelineIds={dashboard.pipelineIds}
    />

    <div use:dashboard.pagination.measure class="min-h-0 flex-1 overflow-auto">
      <div class="relative">
        {#if dashboard.pipelines && dashboard.pipelines.length > 0}
          <PipelineTable
            pipelines={dashboard.pipelines}
            jobsByPipelineId={dashboard.jobsByPipelineId}
            isJobsLoading={dashboard.isJobsLoading}
            isJobsError={dashboard.isJobsError}
            canListJobs={dashboard.canListJobs}
            {runPipeline}
          />
        {:else if dashboard.pipelines}
          <div class="flex h-full min-h-100 items-center justify-center">
            <div class="space-y-2 text-center">
              <p class="text-muted-foreground">{t(pipelineMessages.noPipelines)}</p>
              <p class="text-sm text-muted-foreground">{t(pipelineMessages.noPipelinesBody)}</p>
            </div>
          </div>
        {/if}
      </div>
    </div>

    <PaginationSlot
      paginationInfo={dashboard.pagination.paginationInfo}
      onPageChange={page => dashboard.pagination.setPage(page)}
    />
  </div>
{/if}
