// src/modules/shared/presentation/ui/feedback/ConfirmOperationAlertDialog.tsx
import { Trans } from '@lingui/react/macro';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@shadcn';

type ConfirmOperationAlertDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onContinue: () => void;
  title?: React.ReactNode;
  description?: React.ReactNode;
  isLoading?: boolean; // Optionnel : pour désactiver les boutons pendant l'appel API
};

export function ConfirmOperationAlertDialog({
  open,
  onOpenChange,
  onContinue,
  title,
  description,
  isLoading,
}: ConfirmOperationAlertDialogProps) {
  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{title ?? <Trans>Are you absolutely sure?</Trans>}</AlertDialogTitle>
          <AlertDialogDescription>{description ?? <Trans>This action cannot be undone.</Trans>}</AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel onClick={() => onOpenChange(false)} disabled={isLoading}>
            <Trans>Cancel</Trans>
          </AlertDialogCancel>
          <AlertDialogAction onClick={onContinue} disabled={isLoading}>
            <Trans>Continue</Trans>
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}

// packages/ui/src/feedback/ConfirmOperationAlertDialog.svelte
<script lang="ts">
  import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
  } from '../shadcn/index.ts';
  import { t } from '../i18n/i18n-svelte.svelte.ts';
  import { confirmOperationMessages } from './confirm-operation.messages.ts';

  interface Props {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onContinue: () => void;
    title?: string;
    description?: string;
    isLoading?: boolean;
  }

  let { open, onOpenChange, onContinue, title, description, isLoading = false }: Props = $props();
</script>

<!-- The parent owns `open`: it keeps the dialog open and disabled until the mutation settles. -->
<AlertDialog {open} {onOpenChange}>
  <AlertDialogContent>
    <AlertDialogHeader>
      <AlertDialogTitle>{title ?? t(confirmOperationMessages.title)}</AlertDialogTitle>
      <AlertDialogDescription>
        {description ?? t(confirmOperationMessages.description)}
      </AlertDialogDescription>
    </AlertDialogHeader>
    <AlertDialogFooter>
      <AlertDialogCancel onclick={() => onOpenChange(false)} disabled={isLoading}>
        {t(confirmOperationMessages.cancel)}
      </AlertDialogCancel>
      <AlertDialogAction onclick={onContinue} disabled={isLoading}>
        {t(confirmOperationMessages.continue)}
      </AlertDialogAction>
    </AlertDialogFooter>
  </AlertDialogContent>
</AlertDialog>
