// src/modules/features/agents/presentation/ui/components/AgentIdLink.tsx
import { Copy } from 'lucide-react';
import { toast } from 'sonner';
import { useLingui } from '@lingui/react/macro';
import { ToastMessages } from '@shared/utils/toast-messages.ts';
import { cn } from '@shared/presentation/utils';

interface AgentIdLinkProps {
  id: string;
  /** Truncate to N chars with an ellipsis (full id when omitted). */
  truncate?: number;
  /** Chip variant: paperWarm background + faint border at rest. */
  chip?: boolean;
  className?: string;
}

/**
 * The agent id, click-to-copy: one click puts the full id in the clipboard
 * and confirms with a toast. Shown truncated in tight spots (cards), full in
 * the detail strip — the copy always carries the complete id.
 */
export const AgentIdLink = ({ id, truncate, chip = false, className }: AgentIdLinkProps) => {
  const label = truncate && id.length > truncate ? `${id.slice(0, truncate)}…` : id;
  const { i18n, t } = useLingui();

  const copyId = async (e: React.MouseEvent) => {
    // Cards navigate on click — copying must not also open the agent.
    e.stopPropagation();
    try {
      await navigator.clipboard.writeText(id);
      toast.success(i18n._(ToastMessages.AGENT_ID_COPIED));
    } catch {
      // Clipboard can be denied (permissions, non-secure context) — say so
      // instead of failing silently.
      toast.error(i18n._(ToastMessages.AGENT_ID_COPY_ERROR));
    }
  };

  return (
    <button
      type='button'
      onClick={e => void copyId(e)}
      title={t`Copy agent id`}
      aria-label={t`Copy agent id`}
      className={cn(
        'group inline-flex cursor-pointer items-center gap-1 font-mono text-xs text-foreground transition-colors duration-100',
        'hover:text-success hover:underline hover:decoration-success hover:underline-offset-[3px]',
        chip &&
          'rounded border border-border bg-muted/60 px-1.5 py-0.5 hover:border-success/60 hover:bg-success/10',
        className,
      )}
    >
      <span className='truncate'>{label}</span>
      <Copy className='h-2.5 w-2.5 shrink-0 opacity-55 transition-colors group-hover:text-success group-hover:opacity-100' />
    </button>
  );
};

// extensions/scylla-base/src/features/agents/presentation/ui/components/AgentIdLink/AgentIdLink.svelte
<script lang="ts">
  import { i18n } from '@lingui/core';
  import CopyIcon from '@lucide/svelte/icons/copy';
  import { cn, toast } from '@scylla/ui/utils';
  import { ToastMessages } from '@shared/utils/toast-messages.ts';
  import { t } from '@scylla/ui/i18n';
  import { agentsMessages } from '../../agents.messages.ts';

  interface Props {
    id: string;
    truncate?: number;
    chip?: boolean;
    class?: string;
  }

  let { id, truncate, chip = false, class: className }: Props = $props();

  const label = $derived(truncate && id.length > truncate ? `${id.slice(0, truncate)}…` : id);

  const copyId = async (event: MouseEvent) => {
    // The card opens on click: copying must not.
    event.stopPropagation();
    try {
      await navigator.clipboard.writeText(id);
      toast.success(i18n._(ToastMessages.AGENT_ID_COPIED));
    } catch {
      // The clipboard can be denied: say so.
      toast.error(i18n._(ToastMessages.AGENT_ID_COPY_ERROR));
    }
  };
</script>

<!-- Click to copy the full id, even when it shows truncated. -->
<button
  type="button"
  onclick={event => void copyId(event)}
  title={t(agentsMessages.copyAgentId)}
  aria-label={t(agentsMessages.copyAgentId)}
  class={cn(
    'group inline-flex cursor-pointer items-center gap-1 font-mono text-xs text-foreground transition-colors duration-100',
    'hover:text-success hover:underline hover:decoration-success hover:underline-offset-[3px]',
    chip &&
      'rounded border border-border bg-muted/60 px-1.5 py-0.5 hover:border-success/60 hover:bg-success/10',
    className,
  )}
>
  <span class="truncate">{label}</span>
  <CopyIcon
    class="h-2.5 w-2.5 shrink-0 opacity-55 transition-colors group-hover:text-success group-hover:opacity-100"
  />
</button>
