// src/modules/features/pipeline/presentation/ui/editor/blueprint/StartNodeFormDialog.tsx
import { FormDialog } from '@shared/presentation/ui';
import {
  type FormItem,
  FormItemType,
  type FormValues,
} from '@shared/presentation/structs/scylla-form.struct.ts';
import { Trans, useLingui } from '@lingui/react/macro';

interface StartNodeFormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  currentName: string;
  onSave: (name: string) => void;
}

export function StartNodeFormDialog({
  open,
  onOpenChange,
  currentName,
  onSave,
}: StartNodeFormDialogProps) {
  const { t } = useLingui();

  const items: readonly FormItem<'name'>[] = [
    {
      id: 'name',
      label: t`Name`,
      placeholder: t`e.g., my-pipeline`,
      type: FormItemType.Input,
      inputType: 'text',
      defaultValue: currentName,
      pattern: '^\\S+$',
    },
  ];

  const handleSubmit = ({ name }: FormValues<'name'>) => {
    if (!name.trim()) return;
    onSave(name.trim());
    onOpenChange(false);
  };

  return (
    <FormDialog
      open={open}
      onOpenChange={onOpenChange}
      title={<Trans>Pipeline name</Trans>}
      description={<Trans>Set the name of the pipeline.</Trans>}
      items={items}
      isPending={false}
      submitLabel={<Trans>Save</Trans>}
      onSubmit={handleSubmit}
    />
  );
}

// extensions/scylla-base/src/features/pipeline/presentation/ui/editor/blueprint/StartNodeFormDialog.svelte
<script lang="ts">
  import { FormDialog, FormItemType, type FormItem, type FormValues } from '@scylla/ui';
  import { t } from '@scylla/ui/i18n';
  import { pipelineMessages } from '../../../pipeline.messages.ts';

  interface Props {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    currentName: string;
    onSave: (name: string) => void;
  }

  let { open, onOpenChange, currentName, onSave }: Props = $props();

  // No whitespace: the name goes into a URL and the breadcrumb.
  const items = $derived<readonly FormItem<'name'>[]>([
    {
      id: 'name',
      label: t(pipelineMessages.name),
      placeholder: t(pipelineMessages.namePlaceholder),
      type: FormItemType.Input,
      inputType: 'text',
      defaultValue: currentName,
      pattern: '^\\S+$',
    },
  ]);

  const handleSubmit = ({ name }: FormValues<'name'>) => {
    if (!name.trim()) return;
    onSave(name.trim());
    onOpenChange(false);
  };
</script>

<FormDialog
  {open}
  {onOpenChange}
  title={t(pipelineMessages.pipelineName)}
  description={t(pipelineMessages.pipelineNameDescription)}
  {items}
  submitLabel={t(pipelineMessages.save)}
  onSubmit={handleSubmit}
/>
