// src/modules/features/dashboard/presentation/ui/RunActivityCard.tsx
import type { ReactNode } from 'react';
import { Activity, CheckCircle2, XCircle, Ban, Unplug, Loader2 } from 'lucide-react';
import { Trans } from '@lingui/react/macro';
import { Card, CardContent, CardHeader, CardTitle } from '@shadcn';
import { Skeleton } from '@shadcn/skeleton.tsx';
import { getRelativeTime } from '@shared/utils/date-utils.ts';
import type { JobsSummary } from '@/modules/features/jobs';

interface OutcomeProps {
  icon: ReactNode;
  label: ReactNode;
  value: number;
}

const Outcome = ({ icon, label, value }: OutcomeProps) => (
  <div className='flex items-center gap-2'>
    <div className='shrink-0'>{icon}</div>
    <div className='min-w-0'>
      <p className='text-lg font-semibold leading-none tabular-nums'>{value}</p>
      <p className='truncate text-xs text-muted-foreground mt-0.5'>{label}</p>
    </div>
  </div>
);

interface RunActivityCardProps {
  summary: JobsSummary;
  /** Runs the organization has in total, which may exceed the summarized window. */
  totalRuns: number;
  /** True when `summary` covers only the most recent page of runs. */
  truncated: boolean;
  loading: boolean;
}

/**
 * Organization-wide run activity, from `ListOrganizationJobs`.
 *
 * The backend exposes no organization-level aggregate — only a paginated job
 * listing — so every figure here is computed over the most recent window. When
 * that window does not cover the whole history the card says so rather than
 * presenting a partial success rate as if it were the all-time one.
 */
export const RunActivityCard = ({
  summary,
  totalRuns,
  truncated,
  loading,
}: RunActivityCardProps) => {
  const inFlight = summary.pending + summary.running;

  return (
    <Card className='py-5'>
      <CardHeader className='px-5 pb-0'>
        <CardTitle className='flex items-center justify-between text-base font-semibold'>
          <span className='flex items-center gap-2'>
            <Activity className='h-4 w-4 text-primary' />
            <Trans>Run activity</Trans>
          </span>
          {!loading && inFlight > 0 && (
            <span className='flex items-center gap-1.5 text-xs font-normal text-muted-foreground'>
              <Loader2 className='h-3 w-3 animate-spin text-primary' />
              <Trans>{inFlight} in progress</Trans>
            </span>
          )}
        </CardTitle>
      </CardHeader>

      <CardContent className='px-5 pb-0 pt-4'>
        {loading ? (
          <div className='grid grid-cols-2 gap-4 sm:grid-cols-4'>
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className='h-10 w-full' />
            ))}
          </div>
        ) : summary.total === 0 ? (
          <p className='text-sm text-muted-foreground'>
            <Trans>No pipeline has run yet.</Trans>
          </p>
        ) : (
          <>
            <div className='grid grid-cols-2 gap-4 sm:grid-cols-4'>
              <Outcome
                icon={<CheckCircle2 className='h-4 w-4 text-[var(--success)]' />}
                label={<Trans>Completed</Trans>}
                value={summary.completed}
              />
              <Outcome
                icon={<XCircle className='h-4 w-4 text-destructive' />}
                label={<Trans>Failed</Trans>}
                value={summary.failed}
              />
              <Outcome
                icon={<Ban className='h-4 w-4 text-muted-foreground' />}
                label={<Trans>Cancelled</Trans>}
                value={summary.cancelled}
              />
              <Outcome
                icon={<Unplug className='h-4 w-4 text-amber-500' />}
                label={<Trans>Orphaned</Trans>}
                value={summary.orphaned}
              />
            </div>

            <p className='mt-4 text-xs text-muted-foreground'>
              {summary.lastRunAt && (
                <>
                  <Trans>Last run {getRelativeTime(summary.lastRunAt)}</Trans>
                  {' · '}
                </>
              )}
              {truncated ? (
                <Trans>
                  over the last {summary.total} of {totalRuns} runs
                </Trans>
              ) : (
                <Trans>over all {summary.total} runs</Trans>
              )}
            </p>
          </>
        )}
      </CardContent>
    </Card>
  );
};

// extensions/scylla-base/src/features/dashboard/presentation/ui/RunActivityCard/RunActivityCard.svelte
<script lang="ts">
  import ActivityIcon from '@lucide/svelte/icons/activity';
  import BanIcon from '@lucide/svelte/icons/ban';
  import CheckCircle2Icon from '@lucide/svelte/icons/check-circle-2';
  import Loader2Icon from '@lucide/svelte/icons/loader-2';
  import UnplugIcon from '@lucide/svelte/icons/unplug';
  import XCircleIcon from '@lucide/svelte/icons/x-circle';
  import { Card, CardContent, CardHeader, CardTitle, Skeleton } from '@scylla/ui/shadcn';
  import { t } from '@scylla/ui/i18n';
  import { getRelativeTime } from '@shared/utils/date-utils.ts';
  import type { JobsSummary } from '@base/features/jobs';
  import { dashboardMessages } from '../dashboard.messages.ts';

  interface Props {
    summary: JobsSummary;
    /** Can exceed the summarized window. */
    totalRuns: number;
    /** The summary covers only the latest page of runs. */
    truncated: boolean;
    loading: boolean;
  }

  let { summary, totalRuns, truncated, loading }: Props = $props();

  const inFlight = $derived(summary.pending + summary.running);

  const outcomes = $derived([
    { key: 'completed', icon: CheckCircle2Icon, class: 'text-[var(--success)]', label: t(dashboardMessages.completed), value: summary.completed },
    { key: 'failed', icon: XCircleIcon, class: 'text-destructive', label: t(dashboardMessages.failed), value: summary.failed },
    { key: 'cancelled', icon: BanIcon, class: 'text-muted-foreground', label: t(dashboardMessages.cancelled), value: summary.cancelled },
    { key: 'orphaned', icon: UnplugIcon, class: 'text-amber-500', label: t(dashboardMessages.orphaned), value: summary.orphaned },
  ]);
</script>

<!-- Computed over the latest window (no backend aggregate): the card says when it is partial. -->
<Card class="py-5">
  <CardHeader class="px-5 pb-0">
    <CardTitle class="flex items-center justify-between text-base font-semibold">
      <span class="flex items-center gap-2">
        <ActivityIcon class="h-4 w-4 text-primary" />
        {t(dashboardMessages.runActivity)}
      </span>
      {#if !loading && inFlight > 0}
        <span class="flex items-center gap-1.5 text-xs font-normal text-muted-foreground">
          <Loader2Icon class="h-3 w-3 animate-spin text-primary" />
          {t(dashboardMessages.inProgress(inFlight))}
        </span>
      {/if}
    </CardTitle>
  </CardHeader>

  <CardContent class="px-5 pb-0 pt-4">
    {#if loading}
      <div class="grid grid-cols-2 gap-4 sm:grid-cols-4">
        {#each { length: 4 } as _, index (index)}
          <Skeleton class="h-10 w-full" />
        {/each}
      </div>
    {:else if summary.total === 0}
      <p class="text-sm text-muted-foreground">{t(dashboardMessages.noRunYet)}</p>
    {:else}
      <div class="grid grid-cols-2 gap-4 sm:grid-cols-4">
        {#each outcomes as outcome (outcome.key)}
          {@const Icon = outcome.icon}
          <div class="flex items-center gap-2">
            <div class="shrink-0"><Icon class="h-4 w-4 {outcome.class}" /></div>
            <div class="min-w-0">
              <p class="text-lg font-semibold leading-none tabular-nums">{outcome.value}</p>
              <p class="truncate text-xs text-muted-foreground mt-0.5">{outcome.label}</p>
            </div>
          </div>
        {/each}
      </div>

      <p class="mt-4 text-xs text-muted-foreground">
        {#if summary.lastRunAt}
          {t(dashboardMessages.lastRun(getRelativeTime(summary.lastRunAt)))} ·
        {/if}
        {truncated
          ? t(dashboardMessages.overWindow(summary.total, totalRuns))
          : t(dashboardMessages.overAll(summary.total))}
      </p>
    {/if}
  </CardContent>
</Card>
