// src/modules/core/presentation/ui/ScyllaForm.tsx
import {
  Button,
  Input,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@shadcn';
import {
  type FormChange,
  type FormItem,
  FormItemType,
} from '@core/presentation/models/ScyllaForm.ts';
import { Field, FieldGroup, FieldLabel } from '@shadcn/field.tsx';
import { useState } from 'react';

export type ScyllaFormProps = {
  items: FormItem[];
  className?: string;
  onSubmit: (values: FormChange[]) => void;
  buttonLabel: string;
};

export const ScyllaForm = ({ items, className, buttonLabel, onSubmit }: ScyllaFormProps) => {
  const [values, setValues] = useState<FormChange[]>(
    items.map(item => ({ id: item.id, value: '' })),
  );

  const handleChange = (id: string, value: string) => {
    setValues(prev => prev.map(field => (field.id === id ? { ...field, value } : field)));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(values);
  };

  return (
    <form onSubmit={handleSubmit}>
      <FieldGroup className={className}>
        {items.map(item => (
          <Field key={item.id} className='gap-1'>
            <FieldLabel htmlFor={item.id}>{item.label}</FieldLabel>

            {item.type === FormItemType.Input && (
              <Input
                placeholder={item.placeholder}
                className={item.className}
                id={item.id}
                type={item.inputType}
                value={values.find(v => v.id === item.id)?.value}
                onChange={e => handleChange(item.id, e.target.value)}
              />
            )}

            {item.type === FormItemType.Select && (
              <Select
                value={values.find(v => v.id === item.id)?.value}
                onValueChange={val => handleChange(item.id, val)}
              >
                <SelectTrigger className={item.className || 'w-full'} id={item.id}>
                  <SelectValue placeholder={item.placeholder} />
                </SelectTrigger>
                <SelectContent>
                  {item.options.map(option => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          </Field>
        ))}
      </FieldGroup>

      <div className='flex justify-end mt-4'>
        <Button type='submit'>{buttonLabel}</Button>
      </div>
    </form>
  );
};

// packages/ui/src/forms/ScyllaForm/ScyllaForm.svelte
<script lang="ts" generics="TId extends string">
  import type { Snippet } from 'svelte';
  import {
    Button,
    Field,
    FieldGroup,
    FieldLabel,
    Input,
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
  } from '../../shadcn/index.ts';
  import { createFormState } from '../form-state.svelte.ts';
  import { FormItemType, type FormItem, type FormValues } from '../scylla-form.struct.ts';

  interface Props {
    items: readonly FormItem<TId>[];
    class?: string;
    onSubmit: (values: FormValues<TId>) => void;
    isPending?: boolean;
    footer?: Snippet<[{ isValid: boolean; isPending: boolean }]>;
    buttonLabel?: string;
  }

  let { items, class: className, onSubmit, isPending = false, footer, buttonLabel }: Props =
    $props();

  const form = createFormState(() => items);

  const handleSubmit = (event: SubmitEvent) => {
    event.preventDefault();
    onSubmit(form.values);
  };
</script>

<form onsubmit={handleSubmit} class="space-y-4">
  <FieldGroup class={className}>
    {#each items as item, index (item.id)}
      <Field class="gap-1">
        <FieldLabel for={item.id}>{item.label}</FieldLabel>

        {#if item.type === FormItemType.Input}
          <Input
            id={item.id}
            type={item.inputType}
            disabled={isPending || item.disabled}
            placeholder={item.placeholder}
            class={item.class}
            autofocus={index === 0}
            value={form.values[item.id]}
            oninput={event => form.handleChange(item.id, event.currentTarget.value)}
          />
        {:else}
          <!-- Not `bind:value`: the form state owns the value, reset and validity. -->
          <Select
            type="single"
            value={form.values[item.id]}
            onValueChange={value => form.handleChange(item.id, value)}
            disabled={isPending || item.disabled}
          >
            <SelectTrigger id={item.id} class={item.class ?? 'w-full'}>
              <SelectValue placeholder={item.placeholder} />
            </SelectTrigger>
            <SelectContent>
              {#each item.options as option (option.value)}
                <SelectItem value={option.value} label={option.label}>{option.label}</SelectItem>
              {/each}
            </SelectContent>
          </Select>
        {/if}
      </Field>
    {/each}
  </FieldGroup>

  {#if footer}
    {@render footer({ isValid: form.isValid, isPending })}
  {:else}
    <div class="mt-8 flex justify-end">
      <Button type="submit" disabled={!form.isValid || isPending}>{buttonLabel}</Button>
    </div>
  {/if}
</form>
