// src/modules/features/jobs/presentation/ui/jobs-table/JobTimeline/JobTimeline.svelte
<script lang="ts">
  import { Tooltip, TooltipContent, TooltipTrigger } from '@shadcn';
  import { StatusBar, type StatusBarItem } from '@shared/presentation/ui';
  import { cn } from '@shared/presentation/utils';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import {
    calculateExecutionDuration,
    formatDuration,
    formatTime,
  } from '@shared/utils/date-utils.ts';
  import { getStatusConfig } from '@shared/utils/status-config.ts';
  import type { JobNodeExecution } from '../../../../domain/structs/job.struct.ts';
  import { jobsMessages } from '../../jobs.messages.ts';
  import { groupByStatus, nodeIdOf, shouldCollapse } from '../job-timeline.calculator.ts';

  interface Props {
    nodeExecutions: JobNodeExecution[];
    /** A grouped segment names no node: the caller falls back to the job. */
    onSelectNode?: (nodeId?: string) => void;
  }

  let { nodeExecutions, onSelectNode }: Props = $props();

  interface NodeItem extends StatusBarItem {
    node: JobNodeExecution;
  }

  const collapsed = $derived(shouldCollapse(nodeExecutions.length));

  const items = $derived.by((): NodeItem[] =>
    collapsed
      ? []
      : nodeExecutions.map((node, index) => {
          const nodeId = nodeIdOf(node, index);
          return {
            id: nodeId,
            status: node.state,
            node,
            label: t(jobsMessages.nodeLabel(nodeId)),
            onSelect: onSelectNode ? () => onSelectNode(nodeId) : undefined,
          };
        }),
  );

  const groups = $derived(collapsed ? groupByStatus(nodeExecutions) : []);
  const total = $derived(nodeExecutions.length);
</script>

<!-- One segment per node, or one per status past the threshold. -->
{#snippet nodeTooltip(item: NodeItem)}
  {@const duration = calculateExecutionDuration(item.node.startedAt, item.node.finishedAt)}
  <div class="text-xs">
    <p class="font-semibold">{item.node.id}</p>
    <p>{t(jobsMessages.nodeState(t(getStatusConfig(item.node.state).label)))}</p>
    {#if item.node.startedAt}
      <p>{t(jobsMessages.nodeStarted(formatTime(item.node.startedAt)))}</p>
    {/if}
    {#if item.node.finishedAt}
      <p>{t(jobsMessages.nodeFinished(formatTime(item.node.finishedAt)))}</p>
    {/if}
    {#if duration !== null}
      <p>{t(jobsMessages.nodeDuration(formatDuration(duration)))}</p>
    {/if}
  </div>
{/snippet}

{#if !collapsed}
  <StatusBar {items} tooltip={nodeTooltip} emptyLabel={t(jobsMessages.noNodes)} />
{:else}
  <div class="w-full flex items-center gap-0.5 py-1 h-6 overflow-hidden rounded-md">
    {#each groups as group (group.status)}
      {@const config = getStatusConfig(group.status)}
      {@const groupClass = cn(
        'h-full rounded-sm transition-all duration-150 relative flex items-center justify-center',
        config.barClassName,
        config.barHoverClassName,
        onSelectNode && 'cursor-pointer',
      )}
      <Tooltip delayDuration={100}>
        <TooltipTrigger>
          {#snippet child({ props })}
            {#if onSelectNode}
              <button
                type="button"
                aria-label={t(jobsMessages.groupLabel(group.count, t(config.label)))}
                {...props}
                onclick={event => {
                  (props.onclick as ((e: MouseEvent) => void) | undefined)?.(event);
                  event.stopPropagation();
                  onSelectNode();
                }}
                class={groupClass}
                style="width: {group.percent}%; min-width: 18px"
              >
                {#if group.percent > 8}
                  <span
                    class="text-[10px] font-semibold text-primary-foreground drop-shadow-sm select-none"
                  >
                    {group.count}
                  </span>
                {/if}
              </button>
            {:else}
              <div
                {...props}
                class={groupClass}
                style="width: {group.percent}%; min-width: 18px"
              >
                {#if group.percent > 8}
                  <span
                    class="text-[10px] font-semibold text-primary-foreground drop-shadow-sm select-none"
                  >
                    {group.count}
                  </span>
                {/if}
              </div>
            {/if}
          {/snippet}
        </TooltipTrigger>
        <TooltipContent side="top" class="text-xs p-3 shadow-lg">
          <div class="space-y-1">
            <p class="font-semibold capitalize">{t(config.label)}</p>
            <p>
              {t(jobsMessages.groupShare(group.count, total, Math.round(group.percent)))}
            </p>
            {#if group.count <= 8}
              <ul class="mt-1 space-y-0.5 text-muted-foreground">
                {#each group.nodes as node (node.id)}
                  <li>• {node.id}</li>
                {/each}
              </ul>
            {/if}
          </div>
        </TooltipContent>
      </Tooltip>
    {/each}
  </div>
{/if}

// src/modules/features/jobs/presentation/ui/jobs-table/JobTimeline.tsx
import type { JobNodeExecution } from '@/modules/features/jobs/domain/structs/job.struct.ts';
import { StatusBar, type StatusBarItem } from '@shared/presentation/ui/data-display/StatusBar.tsx';
import { useMemo } from 'react';
import { getStatusConfig } from '@shared/utils/status-config.ts';
import { useLingui } from '@lingui/react';
import { cn } from '@shared/presentation/utils';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@shadcn/tooltip.tsx';
import { Trans } from '@lingui/react/macro';
import { formatTime } from '@shared/utils/date-utils.ts';

type JobTimelineProps = {
  nodeExecutions: JobNodeExecution[];
};

/** Threshold above which nodes are grouped by status */
const COLLAPSE_THRESHOLD = 10;

interface StatusGroup {
  status: string;
  count: number;
  nodes: JobNodeExecution[];
}

/**
 * Display a timeline bar showing the execution state of each node.
 * When there are many nodes, they are grouped by status into proportional segments.
 */
export const JobTimeline = ({ nodeExecutions }: JobTimelineProps) => {
  const { _ } = useLingui();
  const shouldCollapse = nodeExecutions.length > COLLAPSE_THRESHOLD;

  // Grouped view for large pipelines
  const groups = useMemo<StatusGroup[]>(() => {
    if (!shouldCollapse) return [];
    const map = new Map<string, JobNodeExecution[]>();
    for (const node of nodeExecutions) {
      const key = node.state;
      if (!map.has(key)) map.set(key, []);
      map.get(key)!.push(node);
    }
    return Array.from(map.entries()).map(([status, nodes]) => ({
      status,
      count: nodes.length,
      nodes,
    }));
  }, [nodeExecutions, shouldCollapse]);

  if (nodeExecutions.length === 0) {
    return <StatusBar items={[]} emptyLabel={<Trans>No nodes</Trans>} />;
  }

  // Detailed view for small pipelines
  if (!shouldCollapse) {
    const items: StatusBarItem[] = nodeExecutions.map((node, index) => ({
      id: node.id || String(index),
      status: node.state,
      tooltip: (
        <div className='text-xs'>
          <p className='font-semibold'>{node.id}</p>
          <p>
            <Trans>State: {_(getStatusConfig(node.state).label)}</Trans>
          </p>
          {node.startedAt && (
            <p>
              <Trans>Started: {formatTime(node.startedAt)}</Trans>
            </p>
          )}
          {node.finishedAt && (
            <p>
              <Trans>Finished: {formatTime(node.finishedAt)}</Trans>
            </p>
          )}
        </div>
      ),
    }));
    return <StatusBar items={items} emptyLabel={<Trans>No nodes</Trans>} />;
  }

  // Collapsed proportional view
  const total = nodeExecutions.length;

  return (
    <TooltipProvider delayDuration={100}>
      <div className='w-full flex items-center gap-0.5 py-1 h-6 overflow-hidden rounded-md'>
        {groups.map(group => {
          const config = getStatusConfig(group.status);
          const pct = (group.count / total) * 100;

          return (
            <Tooltip key={group.status}>
              <TooltipTrigger asChild>
                <div
                  className={cn(
                    'h-full rounded-sm transition-all duration-150 relative flex items-center justify-center',
                    config.barClassName,
                    config.barHoverClassName,
                  )}
                  style={{ width: `${pct}%`, minWidth: 18 }}
                >
                  {pct > 8 && (
                    <span className='text-[10px] font-semibold text-primary-foreground drop-shadow-sm select-none'>
                      {group.count}
                    </span>
                  )}
                </div>
              </TooltipTrigger>
              <TooltipContent side='top' className='text-xs p-3 shadow-lg'>
                <div className='space-y-1'>
                  <p className='font-semibold capitalize'>{_(config.label)}</p>
                  <p>
                    <Trans>
                      {group.count} / {total} nodes ({Math.round(pct)}%)
                    </Trans>
                  </p>
                  {group.count <= 8 && (
                    <ul className='mt-1 space-y-0.5 text-muted-foreground'>
                      {group.nodes.map(n => (
                        <li key={n.id}>• {n.id}</li>
                      ))}
                    </ul>
                  )}
                </div>
              </TooltipContent>
            </Tooltip>
          );
        })}
      </div>
    </TooltipProvider>
  );
};
