// src/modules/features/apps/presentation/ui/components/AppSecretsCard.tsx
import { useState } from 'react';
import { Trans, useLingui } from '@lingui/react/macro';
import { KeyRound, Plus, Trash } from 'lucide-react';
import { Badge, Button, Card, CardContent } from '@shadcn';
import { Skeleton } from '@shadcn/skeleton.tsx';
import { Switch } from '@shadcn/switch.tsx';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@shadcn/alert-dialog.tsx';
import { FormDialog, SecretRevealDialog } from '@shared/presentation/ui';
import type { FormValues } from '@shared/presentation/structs/scylla-form.struct.ts';
import { formatDate } from '@shared/utils/date-utils.ts';
import { useAppSecrets } from '@/modules/features/apps/presentation/hooks/use-apps.ts';
import { createAppSecretItems } from '@/modules/features/apps/presentation/utils/create-app-secret-form-items.ts';
import type { AppEntity } from '@/modules/features/apps/domain/entities/app.entity.ts';
import type { CreatedAppSecret } from '@/modules/features/apps/domain/structs/app.struct.ts';

interface AppSecretsCardProps {
  app: AppEntity;
}

export const AppSecretsCard = ({ app }: AppSecretsCardProps) => {
  const { t } = useLingui();
  const { secrets, isLoading, createSecret, revokeSecret, setSecretEnabled } = useAppSecrets(
    app.id,
  );
  const [createOpen, setCreateOpen] = useState(false);
  const [created, setCreated] = useState<CreatedAppSecret | null>(null);
  const [toRevoke, setToRevoke] = useState<string | null>(null);

  const handleCreate = ({ label }: FormValues<'label'>) => {
    if (!label.trim()) return;
    createSecret.mutate(label.trim(), {
      onSuccess: data => {
        setCreateOpen(false);
        setCreated(data);
      },
    });
  };

  return (
    <Card>
      <CardContent className='p-5'>
        <div className='flex items-start justify-between gap-2'>
          <div>
            <h2 className='text-lg font-semibold'>
              <Trans>Secrets</Trans>
            </h2>
            <p className='text-sm text-muted-foreground'>
              <Trans>
                Credentials to authenticate this app. Disable cuts active sessions instantly; revoke
                deletes the secret.
              </Trans>
            </p>
          </div>
          <Button size='sm' onClick={() => setCreateOpen(true)}>
            <Plus className='mr-1 h-4 w-4' />
            <Trans>New secret</Trans>
          </Button>
        </div>

        <div className='mt-4 space-y-2'>
          {isLoading ? (
            Array.from({ length: 2 }).map((_, i) => (
              <Skeleton key={i} className='h-14 w-full rounded-md' />
            ))
          ) : secrets.length === 0 ? (
            <p className='rounded-md border border-dashed p-4 text-center text-sm text-muted-foreground'>
              <Trans>No secrets. Create one so this app can authenticate.</Trans>
            </p>
          ) : (
            secrets.map(secret => (
              <div
                key={secret.id}
                className='flex items-center justify-between gap-3 rounded-md border p-3'
              >
                <div className='flex min-w-0 items-center gap-3'>
                  <span className='flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-success/30 bg-success/10'>
                    <KeyRound className='h-4 w-4 text-success' />
                  </span>
                  <div className='min-w-0'>
                    <div className='flex items-center gap-2'>
                      <span className='truncate font-medium'>{secret.label}</span>
                      {secret.enabled ? (
                        <Badge className='bg-success/15 text-success hover:bg-success/15'>
                          <Trans>active</Trans>
                        </Badge>
                      ) : (
                        <Badge variant='secondary'>
                          <Trans>disabled</Trans>
                        </Badge>
                      )}
                    </div>
                    <p className='truncate font-mono text-xs text-muted-foreground'>
                      <Trans>created</Trans> {formatDate(secret.createdAt)}
                    </p>
                  </div>
                </div>
                <div className='flex shrink-0 items-center gap-3'>
                  <Switch
                    checked={secret.enabled}
                    disabled={setSecretEnabled.isPending}
                    onCheckedChange={enabled =>
                      setSecretEnabled.mutate({ secretId: secret.id, enabled })
                    }
                    aria-label={t`Toggle secret enabled`}
                  />
                  <Button
                    variant='ghost'
                    size='icon'
                    className='h-8 w-8 text-muted-foreground hover:text-destructive'
                    onClick={() => setToRevoke(secret.id)}
                  >
                    <Trash className='h-4 w-4' />
                  </Button>
                </div>
              </div>
            ))
          )}
        </div>
      </CardContent>

      <FormDialog
        open={createOpen}
        onOpenChange={setCreateOpen}
        title={<Trans>New secret</Trans>}
        description={<Trans>Add a credential for this app.</Trans>}
        items={createAppSecretItems()}
        isPending={createSecret.isPending}
        submitLabel={<Trans>Create &amp; reveal secret →</Trans>}
        onSubmit={handleCreate}
      />

      {created && (
        <SecretRevealDialog
          open={!!created}
          title={
            <Trans>
              {app.name} · {created.credential.label} credentials
            </Trans>
          }
          description={<Trans>Copy the secret below — it is shown only once.</Trans>}
          secret={created.secret}
          secretLabel={<Trans>Secret</Trans>}
          revealedNote={
            <Trans>
              Use these credentials (id + secret) to authenticate an automation against the Scylla
              API.
            </Trans>
          }
          onClose={() => setCreated(null)}
        />
      )}

      <AlertDialog open={!!toRevoke} onOpenChange={o => !o && setToRevoke(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              <Trans>Revoke secret?</Trans>
            </AlertDialogTitle>
            <AlertDialogDescription>
              <Trans>
                This permanently deletes the secret and immediately cuts any session using it.
                Cannot be undone.
              </Trans>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>
              <Trans>Cancel</Trans>
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (toRevoke) revokeSecret.mutate(toRevoke);
                setToRevoke(null);
              }}
            >
              <Trans>Revoke</Trans>
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Card>
  );
};

// src/modules/features/apps/presentation/ui/components/AppSecretsCard.svelte
<script lang="ts">
  import KeyRoundIcon from '@lucide/svelte/icons/key-round';
  import PlusIcon from '@lucide/svelte/icons/plus';
  import TrashIcon from '@lucide/svelte/icons/trash';
  import { createMutation, createQuery } from '@platform/query';
  import { Badge, Button, Card, CardContent, Skeleton, Switch } from '@shadcn';
  import {
    ConfirmOperationAlertDialog,
    FormDialog,
    SecretRevealDialog,
    type FormValues,
  } from '@shared/presentation/ui';
  import { formatDate } from '@shared/utils/date-utils.ts';
  import { activeLocale, t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { AppEntity } from '../../../domain/entities/app.entity.ts';
  import type { CreatedAppSecret } from '../../../domain/structs/app.struct.ts';
  import { appMutations, appQueries } from '../../apps.queries.ts';
  import { createAppSecretItems } from '../../utils/create-app-secret-form-items.ts';
  import { appsMessages } from '../apps.messages.ts';

  interface Props {
    app: AppEntity;
  }

  let { app }: Props = $props();

  const secretsQuery = createQuery(() => appQueries.secretsOf(app.id));
  const createSecret = createMutation(() => appMutations.createSecret(app.id));
  const revokeSecret = createMutation(() => appMutations.revokeSecret(app.id));
  const setSecretEnabled = createMutation(() => appMutations.setSecretEnabled(app.id));

  const secrets = $derived(secretsQuery.data ?? []);

  let createOpen = $state(false);
  let created = $state<CreatedAppSecret | null>(null);
  let pendingRevocation = $state<string | null>(null);

  // Reading the locale rebuilds the labels on a switch.
  const items = $derived((activeLocale(), createAppSecretItems()));

  const handleCreate = ({ label }: FormValues<'label'>) => {
    if (!label.trim()) return;

    createSecret.mutate(label.trim(), {
      onSuccess: data => {
        createOpen = false;
        created = data;
      },
    });
  };

  const confirmRevoke = () => {
    if (pendingRevocation) revokeSecret.mutate(pendingRevocation);
    pendingRevocation = null;
  };
</script>

<Card>
  <CardContent class="p-5">
    <div class="flex items-start justify-between gap-2">
      <div>
        <h2 class="text-lg font-semibold">{t(appsMessages.secrets)}</h2>
        <p class="text-sm text-muted-foreground">{t(appsMessages.secretsBody)}</p>
      </div>
      <Button size="sm" onclick={() => (createOpen = true)}>
        <PlusIcon class="mr-1 h-4 w-4" />
        {t(appsMessages.newSecret)}
      </Button>
    </div>

    <div class="mt-4 space-y-2">
      {#if secretsQuery.isLoading}
        {#each { length: 2 } as _, index (index)}
          <Skeleton class="h-14 w-full rounded-md" />
        {/each}
      {:else if secrets.length === 0}
        <p
          class="rounded-md border border-dashed p-4 text-center text-sm text-muted-foreground"
        >
          {t(appsMessages.noSecrets)}
        </p>
      {:else}
        {#each secrets as secret (secret.id)}
          <div class="flex items-center justify-between gap-3 rounded-md border p-3">
            <div class="flex min-w-0 items-center gap-3">
              <span
                class="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-success/30 bg-success/10"
              >
                <KeyRoundIcon class="h-4 w-4 text-success" />
              </span>
              <div class="min-w-0">
                <div class="flex items-center gap-2">
                  <span class="truncate font-medium">{secret.label}</span>
                  {#if secret.enabled}
                    <Badge class="bg-success/15 text-success hover:bg-success/15">
                      {t(appsMessages.active)}
                    </Badge>
                  {:else}
                    <Badge variant="secondary">{t(appsMessages.disabled)}</Badge>
                  {/if}
                </div>
                <p class="truncate font-mono text-xs text-muted-foreground">
                  {t(appsMessages.created)}
                  {formatDate(secret.createdAt)}
                </p>
              </div>
            </div>
            <div class="flex shrink-0 items-center gap-3">
              <Switch
                checked={secret.enabled}
                disabled={setSecretEnabled.isPending}
                onCheckedChange={enabled =>
                  setSecretEnabled.mutate({ secretId: secret.id, enabled })}
                aria-label={t(appsMessages.toggleSecretEnabled)}
              />
              <Button
                variant="ghost"
                size="icon"
                class="h-8 w-8 text-muted-foreground hover:text-destructive"
                onclick={() => (pendingRevocation = secret.id)}
              >
                <TrashIcon class="h-4 w-4" />
                <span class="sr-only">{t(appsMessages.revokeSecretAction)}</span>
              </Button>
            </div>
          </div>
        {/each}
      {/if}
    </div>
  </CardContent>
</Card>

<FormDialog
  open={createOpen}
  onOpenChange={open => (createOpen = open)}
  title={t(appsMessages.newSecret)}
  description={t(appsMessages.addCredential)}
  {items}
  isPending={createSecret.isPending}
  submitLabel={t(appsMessages.createAndReveal)}
  onSubmit={handleCreate}
/>

{#if created}
  <SecretRevealDialog
    open
    title={t(appsMessages.secretCredentialsOf(app.name, created.credential.label))}
    description={t(appsMessages.copySecretOnce)}
    secret={created.secret}
    secretLabel={t(appsMessages.secret)}
    revealedNote={t(appsMessages.useTheseCredentials)}
    onClose={() => (created = null)}
  />
{/if}

<ConfirmOperationAlertDialog
  open={pendingRevocation !== null}
  onOpenChange={open => {
    if (!open) pendingRevocation = null;
  }}
  onContinue={confirmRevoke}
  title={t(appsMessages.revokeSecretTitle)}
  description={t(appsMessages.revokeSecretBody)}
/>
