// src/modules/features/triggers/presentation/ui/components/TriggersHeader.tsx
import { Trans } from '@lingui/react/macro';
import { FeatureHeader } from '@shared/presentation/ui';
import { useFeatureSelection } from '@shared/presentation/hooks/use-feature-selection.ts';
import { useDeleteTrigger } from '@/modules/features/triggers/presentation/hooks/use-delete-trigger.ts';
import { Permission } from '@platform/authz';
import { useCan } from '@platform/authz';
import { CopyableText } from '@shared/presentation/ui/data-display/CopyableText.tsx';

interface TriggersHeaderProps {
  count: number;
  triggerIds: string[];
  pipelineId: string;
  onNew: () => void;
}

export const TriggersHeader = ({
  count,
  triggerIds,
  pipelineId,
  onNew,
}: TriggersHeaderProps) => {
  const deleteTrigger = useDeleteTrigger(pipelineId);
  const { headerProps } = useFeatureSelection('triggers', triggerIds, {
    deleteItem: id => deleteTrigger.mutateAsync(id),
  });

  // Triggers are all-or-nothing in V1: one permission covers create and delete.
  const canManage = useCan(Permission.MANAGE_TRIGGERS);

  return (
    <FeatureHeader
      count={count}
      label={<Trans>Trigger</Trans>}
      pluralLabel={<Trans>Triggers</Trans>}
      newLabel={<Trans>New trigger</Trans>}
      onNew={onNew}
      canNew={canManage}
      newDeniedReason={<Trans>You don't have permission to manage triggers.</Trans>}
      canDelete={canManage}
      deleteDeniedReason={<Trans>You don't have permission to manage triggers.</Trans>}
      {...headerProps}
      underLabel={
        <div className='flex items-center gap-2'>
          <span className='text-sm text-muted-foreground font-medium'>
            <Trans>Pipeline ID:</Trans>
          </span>
          <CopyableText value={pipelineId} className='text-sm text-muted-foreground font-medium' />
        </div>
      }
    />
  );
};

// extensions/scylla-base/src/features/triggers/presentation/ui/components/TriggersHeader/TriggersHeader.svelte
<script lang="ts">
  import { can, Permission } from '@platform/authz';
  import { createMutation } from '@scylla/core-sdk';
  import { CopyableText, FeatureHeader } from '@scylla/ui';
  import { createFeatureSelection } from '@scylla/ui/state';
  import { t } from '@scylla/ui/i18n';
  import { triggerMutations } from '../../../triggers.queries.ts';
  import { triggersMessages } from '../../triggers.messages.ts';

  interface Props {
    count: number;
    triggerIds: string[];
    pipelineId: string;
    onNew: () => void;
  }

  let { count, triggerIds, pipelineId, onNew }: Props = $props();

  const deleteTrigger = createMutation(() => triggerMutations.remove(pipelineId));

  // A getter: the ids arrive later.
  const selection = createFeatureSelection('triggers', () => triggerIds, {
    deleteItem: id => deleteTrigger.mutateAsync(id),
  });

  // One permission covers every write.
  const canManage = $derived(can(Permission.MANAGE_TRIGGERS));
</script>

{#snippet pipelineIdLine()}
  <div class="flex items-center gap-2">
    <span class="text-sm text-muted-foreground font-medium">
      {t(triggersMessages.pipelineIdLabel)}
    </span>
    <CopyableText value={pipelineId} class="text-sm text-muted-foreground font-medium" />
  </div>
{/snippet}

<FeatureHeader
  {count}
  label={t(triggersMessages.trigger)}
  pluralLabel={t(triggersMessages.triggers)}
  newLabel={t(triggersMessages.newTrigger)}
  {onNew}
  canNew={canManage}
  newDeniedReason={t(triggersMessages.manageDenied)}
  canDelete={canManage}
  deleteDeniedReason={t(triggersMessages.manageDenied)}
  underLabel={pipelineIdLine}
  {...selection.headerProps}
/>
