// extensions/scylla-base/src/features/pipeline/presentation/ui/editor/blueprint/BlueprintCanvas.svelte
<script lang="ts">
  import {
    Background,
    BackgroundVariant,
    Controls,
    SvelteFlow,
    type EdgeTypes,
    type NodeTypes,
  } from '@xyflow/svelte';
  import '@xyflow/svelte/dist/style.css';
  import type { PipelineStep } from '../../../../domain/structs/pipeline.struct.ts';
  import { DEFAULT_EDGE_STYLE, START_NODE_ID, stepOf } from '../../../utils/blueprint-converter.ts';
  import type { BlueprintState } from '../../../blueprint.state.svelte.ts';
  import DeletableEdge from './DeletableEdge.svelte';
  import PipelineStepNode from './PipelineStepNode.svelte';
  import StartNode from './StartNode.svelte';

  interface Props {
    blueprint: BlueprintState;
    onStartNodeDoubleClick: () => void;
    onStepNodeDoubleClick: (step: PipelineStep) => void;
  }

  let { blueprint, onStartNodeDoubleClick, onStepNodeDoubleClick }: Props = $props();

  const nodeTypes: NodeTypes = { pipelineStep: PipelineStepNode, startNode: StartNode };
  const edgeTypes: EdgeTypes = { deletable: DeletableEdge };
</script>

<!-- `nodes` and `edges` are bound: the library drags, selects and deletes; the callbacks report the changes. -->
<SvelteFlow
  bind:nodes={blueprint.nodes}
  bind:edges={blueprint.edges}
  {nodeTypes}
  {edgeTypes}
  fitView
  fitViewOptions={{ padding: 0.2 }}
  deleteKey={['Backspace', 'Delete']}
  edgesFocusable
  defaultEdgeOptions={DEFAULT_EDGE_STYLE}
  class="rounded-lg"
  onbeforeconnect={connection => (blueprint.canConnect(connection) ? connection : false)}
  onconnect={() => blueprint.sync()}
  ondelete={() => blueprint.sync()}
  onnodeclick={({ node, event }) => {
    // No double-click event: the click's `detail` counts.
    if ((event as MouseEvent).detail < 2) return;
    if (node.id === START_NODE_ID) {
      onStartNodeDoubleClick();
      return;
    }
    const step = stepOf(node);
    if (step) onStepNodeDoubleClick(step);
  }}
>
  <Background variant={BackgroundVariant.Dots} gap={16} size={1} class="bg-background!" />
  <Controls class="border-border! bg-background! shadow-sm!" />
</SvelteFlow>

<style>
  :global(.svelte-flow__controls-button) {
    --xy-controls-button-background-color: var(--background);
    --xy-controls-button-background-color-hover: var(--muted);
    --xy-controls-button-color: var(--foreground);
    --xy-controls-button-color-hover: var(--foreground);
    --xy-controls-button-border-color: var(--border);
  }
</style>

// src/modules/features/pipeline/presentation/ui/editor/blueprint/BlueprintCanvas.tsx
import ReactFlow, { Background, BackgroundVariant, Controls, MarkerType } from 'reactflow';
import 'reactflow/dist/style.css';
import { forwardRef, useCallback, useImperativeHandle } from 'react';
import type { Node } from 'reactflow';
import { PipelineStepNode } from './PipelineStepNode.tsx';
import { StartNode } from './StartNode.tsx';
import { DeletableEdge } from './DeletableEdge.tsx';
import {
  EDGE_COLOR,
  DEFAULT_EDGE_STYLE,
  type PipelineNodeData,
  START_NODE_ID,
} from '@/modules/features/pipeline/presentation/utils/blueprint-converter.ts';
import type { PipelineStep } from '@/modules/features/pipeline/domain/structs/pipeline.struct.ts';
import { useBlueprintState } from '@/modules/features/pipeline/presentation/hooks/use-blueprint-state.ts';
import type { NodeFormValue } from './StepNodeFormDialog.tsx';

const nodeTypes = { pipelineStep: PipelineStepNode, startNode: StartNode };
const edgeTypes = { deletable: DeletableEdge };

const defaultEdgeOptions = {
  ...DEFAULT_EDGE_STYLE,
  markerEnd: { type: MarkerType.ArrowClosed, color: EDGE_COLOR },
};

export interface BlueprintCanvasHandle {
  addNode: (nodeId: string, value: NodeFormValue) => void;
  editNode: (originalId: string, newNodeId: string, value: NodeFormValue) => void;
}

interface BlueprintCanvasProps {
  steps: PipelineStep[];
  pipelineName: string;
  onStepsChange: (steps: PipelineStep[]) => void;
  onStartNodeDoubleClick: () => void;
  onStepNodeDoubleClick: (data: PipelineNodeData) => void;
}

export const BlueprintCanvas = forwardRef<BlueprintCanvasHandle, BlueprintCanvasProps>(
  ({ steps, pipelineName, onStepsChange, onStartNodeDoubleClick, onStepNodeDoubleClick }, ref) => {
    const {
      nodes,
      edges,
      onNodesChange,
      onEdgesChange,
      handleConnect,
      handleEdgesDelete,
      handleNodesDelete,
      handleAddNode,
      handleEditNode,
    } = useBlueprintState({ steps, pipelineName, onStepsChange });

    useImperativeHandle(
      ref,
      () => ({
        addNode: handleAddNode,
        editNode: handleEditNode,
      }),
      [handleAddNode, handleEditNode],
    );

    const handleNodeDoubleClick = useCallback(
      (_event: React.MouseEvent, node: Node) => {
        if (node.id === START_NODE_ID) {
          onStartNodeDoubleClick();
          return;
        }
        onStepNodeDoubleClick(node.data as PipelineNodeData);
      },
      [onStartNodeDoubleClick, onStepNodeDoubleClick],
    );

    return (
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={handleConnect}
        onEdgesDelete={handleEdgesDelete}
        onNodesDelete={handleNodesDelete}
        onNodeDoubleClick={handleNodeDoubleClick}
        nodeTypes={nodeTypes}
        edgeTypes={edgeTypes}
        fitView
        fitViewOptions={{ padding: 0.2 }}
        deleteKeyCode={['Backspace', 'Delete']}
        edgesFocusable
        edgesUpdatable
        className='rounded-lg'
        defaultEdgeOptions={defaultEdgeOptions}
      >
        <Background variant={BackgroundVariant.Dots} gap={16} size={1} className='bg-background!' />
        <Controls className='bg-background! border-border! shadow-sm!' />
      </ReactFlow>
    );
  },
);

BlueprintCanvas.displayName = 'BlueprintCanvas';
