// src/modules/features/pipeline/presentation/ui/editor/blueprint/DeletableEdge.svelte
<script lang="ts">
  import Trash2Icon from '@lucide/svelte/icons/trash-2';
  import {
    BaseEdge,
    EdgeLabel,
    getSmoothStepPath,
    useSvelteFlow,
    type EdgeProps,
  } from '@xyflow/svelte';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { EDGE_COLOR } from '../../../utils/blueprint-converter.ts';
  import { pipelineMessages } from '../../../pipeline.messages.ts';

  const SELECTED_COLOR = 'oklch(70% 0.3 30)';

  let {
    id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    selected,
    markerEnd,
  }: EdgeProps = $props();

  const { deleteElements } = useSvelteFlow();

  const path = $derived(
    getSmoothStepPath({ sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition }),
  );
  const color = $derived(selected ? SELECTED_COLOR : EDGE_COLOR);
</script>

<!-- A dependency, with a delete button once selected. -->
<BaseEdge
  {id}
  path={path[0]}
  {markerEnd}
  style="stroke: {color}; stroke-width: {selected ? 3 : 2};{selected
    ? ` filter: drop-shadow(0 0 4px ${SELECTED_COLOR});`
    : ''}"
/>

{#if selected}
  <EdgeLabel x={path[1]} y={path[2]} transparent class="nodrag nopan" style="pointer-events: all; z-index: 1000;">
    <button
      type="button"
      aria-label={t(pipelineMessages.deleteEdge)}
      class="flex h-full w-full cursor-pointer items-center justify-center rounded-full border-2 border-background bg-destructive p-1 text-white shadow-lg transition-transform hover:scale-125"
      onclick={event => {
        event.stopPropagation();
        event.preventDefault();
        void deleteElements({ edges: [{ id }] });
      }}
      onmousedown={event => event.stopPropagation()}
    >
      <Trash2Icon class="h-6.5 w-6.5" />
    </button>
  </EdgeLabel>
{/if}

// src/modules/features/pipeline/presentation/ui/editor/blueprint/DeletableEdge.tsx
import {
  BaseEdge,
  EdgeLabelRenderer,
  getSmoothStepPath,
  useReactFlow,
  type EdgeProps,
} from 'reactflow';
import { Trash2 } from 'lucide-react';
import { EDGE_COLOR } from '@/modules/features/pipeline/presentation/utils/blueprint-converter.ts';
const SELECTED_COLOR = 'oklch(70% 0.3 30)';

export function DeletableEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  selected,
  markerEnd,
}: EdgeProps) {
  const { deleteElements } = useReactFlow();
  const [edgePath, labelX, labelY] = getSmoothStepPath({
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
  });

  const color = selected ? SELECTED_COLOR : EDGE_COLOR;

  return (
    <>
      <BaseEdge
        id={id}
        path={edgePath}
        markerEnd={markerEnd}
        style={{
          stroke: color,
          strokeWidth: selected ? 3 : 2,
          filter: selected ? `drop-shadow(0 0 4px ${SELECTED_COLOR})` : undefined,
        }}
      />
      {selected && (
        <EdgeLabelRenderer>
          <div
            style={{
              position: 'absolute',
              left: labelX,
              top: labelY,
              transform: 'translate(-50%, -50%)',
              pointerEvents: 'all',
              zIndex: 1000,
            }}
            className='nodrag nopan'
          >
            <button
              className='flex w-full h-full p-1 items-center justify-center rounded-full bg-destructive text-white shadow-lg cursor-pointer hover:scale-125 transition-transform border-2 border-background'
              onClick={e => {
                e.stopPropagation();
                e.preventDefault();
                deleteElements({ edges: [{ id }] });
              }}
              onMouseDown={e => {
                e.stopPropagation();
              }}
              title='Delete edge'
            >
              <Trash2 className='w-6.5 h-6.5' />
            </button>
          </div>
        </EdgeLabelRenderer>
      )}
    </>
  );
}
