// src/modules/features/pipeline/presentation/ui/editor/blueprint/PipelineBlueprint.tsx
import { useCallback, useRef } from 'react';
import { BlueprintToolbar } from './BlueprintToolbar.tsx';
import { BlueprintCanvas, type BlueprintCanvasHandle } from './BlueprintCanvas.tsx';
import { StepNodeFormDialog, type NodeFormValue } from './StepNodeFormDialog.tsx';
import { StartNodeFormDialog } from './StartNodeFormDialog.tsx';
import { type PipelineNodeData } from '@/modules/features/pipeline/presentation/utils/blueprint-converter.ts';
import type { PipelineStep } from '@/modules/features/pipeline/domain/structs/pipeline.struct.ts';
import { useDialog } from '@shared/presentation/hooks/use-dialog.ts';

interface PipelineBlueprintProps {
  steps: PipelineStep[];
  pipelineName: string;
  onStepsChange: (steps: PipelineStep[]) => void;
  onNameChange: (name: string) => void;
}

export const PipelineBlueprint = ({
  steps,
  pipelineName,
  onStepsChange,
  onNameChange,
}: PipelineBlueprintProps) => {
  const canvasRef = useRef<BlueprintCanvasHandle>(null);

  const addStepDialog = useDialog();
  const editStepDialog = useDialog<PipelineNodeData>();
  const editStartDialog = useDialog();

  const handleAddNode = useCallback(
    (nodeId: string, value: NodeFormValue) => canvasRef.current?.addNode(nodeId, value),
    [],
  );

  const handleEditNode = useCallback(
    (originalId: string, nodeId: string, value: NodeFormValue) =>
      canvasRef.current?.editNode(originalId, nodeId, value),
    [],
  );

  return (
    <div className='h-full w-full relative'>
      <BlueprintToolbar onAddNode={addStepDialog.open} />

      <BlueprintCanvas
        ref={canvasRef}
        steps={steps}
        pipelineName={pipelineName}
        onStepsChange={onStepsChange}
        onStartNodeDoubleClick={editStartDialog.open}
        onStepNodeDoubleClick={editStepDialog.open}
      />

      <StepNodeFormDialog
        open={addStepDialog.isOpen}
        onOpenChange={() => addStepDialog.close()}
        onAdd={handleAddNode}
        onEdit={handleEditNode}
      />

      <StepNodeFormDialog
        open={editStepDialog.isOpen}
        onOpenChange={() => editStepDialog.close()}
        editingNode={editStepDialog.data}
        onAdd={handleAddNode}
        onEdit={handleEditNode}
      />

      <StartNodeFormDialog
        open={editStartDialog.isOpen}
        onOpenChange={() => editStartDialog.close()}
        currentName={pipelineName}
        onSave={onNameChange}
      />
    </div>
  );
};

// src/modules/features/pipeline/presentation/ui/editor/blueprint/PipelineBlueprint.svelte
<script lang="ts">
  import PlusIcon from '@lucide/svelte/icons/plus';
  import { Button } from '@shadcn';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { PipelineStep } from '../../../../domain/structs/pipeline.struct.ts';
  import { createBlueprintState } from '../../../blueprint.state.svelte.ts';
  import BlueprintCanvas from './BlueprintCanvas.svelte';
  import StartNodeFormDialog from './StartNodeFormDialog.svelte';
  import StepNodeFormDialog from './StepNodeFormDialog.svelte';
  import { pipelineMessages } from '../../../pipeline.messages.ts';

  interface Props {
    steps: PipelineStep[];
    pipelineName: string;
    projectId?: string;
    onStepsChange: (steps: PipelineStep[]) => void;
    onNameChange: (name: string) => void;
  }

  let { steps, pipelineName, projectId, onStepsChange, onNameChange }: Props = $props();

  const blueprint = createBlueprintState({
    steps: () => steps,
    pipelineName: () => pipelineName,
    // Read at call time, so a swapped callback is the one called.
    onStepsChange: next => onStepsChange(next),
  });

  let editingStep = $state<PipelineStep | undefined>(undefined);
  let stepDialogOpen = $state(false);
  let nameDialogOpen = $state(false);
</script>

<div class="relative h-full w-full">
  <div class="absolute top-3 right-3 z-10 flex gap-2">
    <Button
      size="sm"
      variant="outline"
      onclick={() => {
        editingStep = undefined;
        stepDialogOpen = true;
      }}
    >
      <PlusIcon class="mr-1 h-4 w-4" />
      {t(pipelineMessages.addNode)}
    </Button>
  </div>

  <BlueprintCanvas
    {blueprint}
    onStartNodeDoubleClick={() => (nameDialogOpen = true)}
    onStepNodeDoubleClick={step => {
      editingStep = step;
      stepDialogOpen = true;
    }}
  />

  <!-- One dialog for adding and editing: `editingStep` tells them apart. -->
  <StepNodeFormDialog
    open={stepDialogOpen}
    onOpenChange={open => (stepDialogOpen = open)}
    {editingStep}
    {projectId}
    onAdd={(nodeId, value) => blueprint.addNode(nodeId, value)}
    onEdit={(originalId, nodeId, value) => blueprint.editNode(originalId, nodeId, value)}
  />

  <StartNodeFormDialog
    open={nameDialogOpen}
    onOpenChange={open => (nameDialogOpen = open)}
    currentName={pipelineName}
    onSave={onNameChange}
  />
</div>
