// src/modules/features/pipeline/presentation/ui/editor/blueprint/PipelineStepNode.svelte
<script lang="ts">
  import TerminalIcon from '@lucide/svelte/icons/terminal';
  import XIcon from '@lucide/svelte/icons/x';
  import { Handle, Position, useSvelteFlow, type NodeProps } from '@xyflow/svelte';
  import { Card } from '@shadcn';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import type { BlueprintStepNode } from '../../../utils/blueprint-converter.ts';
  import { pipelineMessages } from '../../../pipeline.messages.ts';

  let { id, data, selected }: NodeProps<BlueprintStepNode> = $props();

  const { deleteElements } = useSvelteFlow();

  const step = $derived(data.step);
  const scriptPreview = $derived(
    step.kind === 'script' ? (step.script.split('\n').find(line => line.trim() !== '') ?? '') : '',
  );
</script>

<Card
  class="w-[260px] cursor-pointer overflow-hidden p-0 transition-all duration-200 hover:scale-105 hover:border-primary hover:shadow-lg {selected
    ? 'scale-105 shadow-lg ring-2 ring-primary'
    : 'shadow-sm'}"
>
  <Handle
    type="target"
    position={Position.Left}
    class="h-3! w-3! border-2! border-background! bg-primary!"
  />

  <div class="flex items-center justify-between border-b bg-primary/10 px-3 py-2">
    <div class="flex items-center gap-2">
      <TerminalIcon class="h-4 w-4 text-primary" />
      <span class="truncate text-sm font-semibold">{step.id}</span>
    </div>
    <button
      type="button"
      aria-label={t(pipelineMessages.deleteNode)}
      onclick={event => {
        event.stopPropagation();
        void deleteElements({ nodes: [{ id }] });
      }}
      class="rounded p-0.5 text-muted-foreground transition-colors hover:bg-destructive/20 hover:text-destructive"
    >
      <XIcon class="h-3.5 w-3.5" />
    </button>
  </div>

  <div class="space-y-1 px-3 py-2">
    {#if step.kind === 'exec'}
      <div class="flex items-center gap-1.5">
        <span class="text-xs text-muted-foreground">cmd:</span>
        <code class="rounded bg-muted px-1.5 py-0.5 font-mono text-xs">{step.command}</code>
      </div>
      {#if step.args.length > 0}
        <div class="flex items-center gap-1.5">
          <span class="text-xs text-muted-foreground">args:</span>
          <code class="max-w-[180px] truncate rounded bg-muted px-1.5 py-0.5 font-mono text-xs">
            {step.args.join(' ')}
          </code>
        </div>
      {/if}
    {:else}
      <div class="flex items-center gap-1.5">
        <span
          class="rounded bg-primary/15 px-1.5 py-0.5 text-[10px] font-semibold tracking-wide text-primary uppercase"
        >
          {step.shell}
        </span>
        <code class="max-w-[180px] truncate rounded bg-muted px-1.5 py-0.5 font-mono text-xs">
          {scriptPreview}
        </code>
      </div>
    {/if}
  </div>

  <Handle
    type="source"
    position={Position.Right}
    class="h-3! w-3! border-2! border-background! bg-primary!"
  />
</Card>

// src/modules/features/pipeline/presentation/ui/editor/blueprint/PipelineStepNode.tsx
import { Handle, Position, useReactFlow } from 'reactflow';
import type { NodeProps } from 'reactflow';
import { Card } from '@shadcn';
import type { PipelineNodeData } from '@/modules/features/pipeline/presentation/utils/blueprint-converter.ts';
import { Terminal, X } from 'lucide-react';

export const PipelineStepNode = ({ id, data, selected }: NodeProps<PipelineNodeData>) => {
  const { deleteElements } = useReactFlow();

  const handleDelete = (e: React.MouseEvent) => {
    e.stopPropagation();
    deleteElements({ nodes: [{ id }] });
  };

  const scriptPreview =
    data.kind === 'script'
      ? (data.script.split('\n').find(line => line.trim() !== '') ?? '')
      : '';

  return (
    <Card
      className={`w-[260px] p-0 overflow-hidden cursor-pointer transition-all duration-200 hover:scale-105 hover:border-primary hover:shadow-lg ${selected ? 'ring-2 ring-primary shadow-lg scale-105' : 'shadow-sm'}`}
    >
      <Handle
        type='target'
        position={Position.Left}
        className='w-3! h-3! bg-primary! border-2! border-background!'
      />

      <div className='bg-primary/10 px-3 py-2 flex items-center justify-between border-b'>
        <div className='flex items-center gap-2'>
          <Terminal className='w-4 h-4 text-primary' />
          <span className='font-semibold text-sm truncate'>{data.id}</span>
        </div>
        <button
          onClick={handleDelete}
          className='p-0.5 rounded hover:bg-destructive/20 text-muted-foreground hover:text-destructive transition-colors'
          title='Delete node'
        >
          <X className='w-3.5 h-3.5' />
        </button>
      </div>

      <div className='px-3 py-2 space-y-1'>
        {data.kind === 'exec' ? (
          <>
            <div className='flex items-center gap-1.5'>
              <span className='text-xs text-muted-foreground'>cmd:</span>
              <code className='text-xs font-mono bg-muted px-1.5 py-0.5 rounded'>{data.command}</code>
            </div>
            {data.args.length > 0 && (
              <div className='flex items-center gap-1.5'>
                <span className='text-xs text-muted-foreground'>args:</span>
                <code className='text-xs font-mono bg-muted px-1.5 py-0.5 rounded truncate max-w-[180px]'>
                  {data.args.join(' ')}
                </code>
              </div>
            )}
          </>
        ) : (
          <div className='flex items-center gap-1.5'>
            <span className='text-[10px] font-semibold uppercase tracking-wide bg-primary/15 text-primary px-1.5 py-0.5 rounded'>
              {data.shell}
            </span>
            <code className='text-xs font-mono bg-muted px-1.5 py-0.5 rounded truncate max-w-[180px]'>
              {scriptPreview}
            </code>
          </div>
        )}
      </div>

      <Handle
        type='source'
        position={Position.Right}
        className='w-3! h-3! bg-primary! border-2! border-background!'
      />
    </Card>
  );
};
