// src/modules/layout/presentation/ui/NavMain.tsx
import { useScyllaNavigate } from '@shared/presentation/hooks/use-scylla-navigate.ts';
import type {
  NavItem,
  NavSection,
} from '@/modules/layout/presentation/structs/nav-section.struct.ts';
import {
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
} from '@shadcn/sidebar.tsx';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@shadcn/collapsible.tsx';
import { ChevronRight } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { Trans } from '@lingui/react/macro';

interface NavMainProps {
  sections: NavSection[];
}

export function NavMain({ sections }: NavMainProps) {
  const navigate = useScyllaNavigate().navigate;
  const { pathname } = useLocation();

  const isActive = (url?: string) => !!url && pathname.startsWith(url);

  const renderLeaf = (item: NavItem) => (
    <SidebarMenuItem className={'transition-all duration-200 hover:scale-105'}>
      <SidebarMenuButton
        tooltip={item.title}
        isActive={isActive(item.url)}
        onClick={() => item.url && navigate(item.url)}
      >
        {item.icon && <item.icon />}
        <span>{item.title}</span>
      </SidebarMenuButton>
    </SidebarMenuItem>
  );

  const renderParent = (item: NavItem) => {
    const childActive = item.items?.some(sub => isActive(sub.url));

    return (
      <Collapsible asChild defaultOpen={childActive} className='group/collapsible'>
        <SidebarMenuItem>
          <CollapsibleTrigger asChild>
            <SidebarMenuButton tooltip={item.title}>
              {item.icon && <item.icon />}
              <span>{item.title}</span>
              <ChevronRight className='ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90' />
            </SidebarMenuButton>
          </CollapsibleTrigger>
          <CollapsibleContent>
            <SidebarMenuSub>
              {item.items?.map((sub, subIndex) => (
                <SidebarMenuSubItem key={subIndex}>
                  <SidebarMenuSubButton
                    isActive={isActive(sub.url)}
                    onClick={() => sub.url && navigate(sub.url)}
                    className='cursor-pointer'
                  >
                    {sub.icon && <sub.icon />}
                    <span>{sub.title}</span>
                  </SidebarMenuSubButton>
                </SidebarMenuSubItem>
              ))}
            </SidebarMenuSub>
          </CollapsibleContent>
        </SidebarMenuItem>
      </Collapsible>
    );
  };

  return (
    <>
      {sections.map((section, index) => (
        <SidebarGroup key={index}>
          <SidebarGroupLabel>
            <Trans>{section.title}</Trans>
          </SidebarGroupLabel>
          <SidebarMenu>
            {section.items.map((item, itemIndex) => (
              <div key={itemIndex}>
                {item.items?.length ? renderParent(item) : renderLeaf(item)}
              </div>
            ))}
          </SidebarMenu>
        </SidebarGroup>
      ))}
    </>
  );
}

// src/modules/layout/presentation/ui/NavMain.svelte
<script lang="ts">
  import { navigateTo } from '@platform/context';
  import { routePathname } from '@platform/routing';
  import {
    SidebarGroup,
    SidebarGroupLabel,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
  } from '@shadcn';
  import type { NavItem, NavSection } from '../structs/nav-section.struct.ts';
  import { markSeen } from '../whats-new.svelte.ts';
  import { NAV_SECTION_CARD_CLASS, NAV_SECTION_DIVIDER_CLASS } from './nav-classes.ts';
  import NewBadge from './NewBadge.svelte';

  let { sections }: { sections: NavSection[] } = $props();

  const pathname = $derived(routePathname());

  const open = (item: NavItem) => {
    if (item.highlightId) markSeen(item.highlightId);
    navigateTo(item.url);
  };
</script>

{#each sections as section (section.title)}
  <SidebarGroup class={NAV_SECTION_CARD_CLASS}>
    {#if section.header}
      {@render section.header()}
      <div class={NAV_SECTION_DIVIDER_CLASS}></div>
    {:else}
      <SidebarGroupLabel class="group-data-[collapsible=icon]:hidden">
        {section.title}
      </SidebarGroupLabel>
    {/if}
    <SidebarMenu>
      {#each section.items as item (item.url)}
        <SidebarMenuItem
          class="transition-all duration-200 hover:scale-105 group-data-[collapsible=icon]:hover:scale-100"
        >
          <SidebarMenuButton
            tooltip={item.title}
            isActive={pathname.startsWith(item.url)}
            onclick={() => open(item)}
          >
            {#if item.icon}
              <item.icon />
            {/if}
            <span>{item.title}</span>
            {#if item.highlightId}
              <NewBadge highlightId={item.highlightId} />
            {/if}
          </SidebarMenuButton>
        </SidebarMenuItem>
      {/each}
    </SidebarMenu>
  </SidebarGroup>
{/each}
