// src/modules/layout/presentation/ui/ScyllaBreadcrumbs.tsx
import { useMatches, Link, useParams } from 'react-router-dom';
import type { BreadcrumbParams, RouteHandle, } from '@platform/routing';
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@shadcn/breadcrumb.tsx';
import { ChevronRight } from 'lucide-react';
import React from 'react';
import { useLingui } from '@lingui/react/macro';
import { useContextStore } from '@platform/context';

export const ScyllaBreadcrumbs = () => {
  const matches = useMatches();
  const { i18n } = useLingui();

  const org = useContextStore(state => state.organization?.name);
  const proj = useContextStore(state => state.project?.name);
  const pipelineName = useContextStore(state => state.pipeline?.name);

  const { userId } = useParams();

  const params: BreadcrumbParams = {
    projectName: proj || undefined,
    organizationName: org || undefined,
    pipelineName: pipelineName || undefined,
    userId: userId || undefined,
  };

  const crumbs = matches
    .filter(match => (match.handle as RouteHandle | undefined)?.breadcrumb)
    .map(match => ({
      ...(match.handle as Required<RouteHandle>).breadcrumb(params),
      path: match.pathname,
    }));

  if (crumbs.length === 0) return null;

  return (
    <Breadcrumb>
      <BreadcrumbList className='gap-2'>
        {crumbs.map((crumb, index) => {
          const isLast = index === crumbs.length - 1;

          const content = (
            <>
              <span className='whitespace-nowrap'>{i18n._(crumb.label)}</span>
              {crumb.highlight && <span className='text-primary'>#{crumb.highlight}</span>}
              {crumb.detail && <span className='whitespace-nowrap'>- {i18n._(crumb.detail)}</span>}
            </>
          );

          return (
            <React.Fragment key={crumb.path}>
              <BreadcrumbItem>
                {isLast ? (
                  <BreadcrumbPage className='font-semibold text-sm px-2 py-1 rounded-md bg-muted text-foreground flex gap-1 items-center'>
                    {content}
                  </BreadcrumbPage>
                ) : (
                  <BreadcrumbLink
                    asChild
                    className='text-muted-foreground hover:text-primary font-medium text-sm px-2 py-1 rounded-md hover:bg-primary/10 transition-all duration-200'
                  >
                    <Link to={crumb.path} className='flex gap-1 items-center'>
                      {content}
                    </Link>
                  </BreadcrumbLink>
                )}
              </BreadcrumbItem>
              {!isLast && (
                <BreadcrumbSeparator>
                  <ChevronRight className='w-4 h-4 text-muted-foreground' />
                </BreadcrumbSeparator>
              )}
            </React.Fragment>
          );
        })}
      </BreadcrumbList>
    </Breadcrumb>
  );
};

// src/modules/layout/presentation/ui/ScyllaBreadcrumbs.svelte
<script lang="ts">
  import ChevronRightIcon from '@lucide/svelte/icons/chevron-right';
  import { contextStore } from '@platform/context';
  import { routeParams, routeTrail } from '@platform/routing';
  import { toRune } from '@shared/presentation/stores/to-rune.svelte.ts';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { breadcrumbsFor, type BreadcrumbItem } from '../breadcrumbs.ts';

  const context = toRune(contextStore);

  const crumbs = $derived.by(() => {
    const { organization, project, pipeline } = context();
    const { userId, jobId, pipelineId } = routeParams();
    const pipelineName = pipeline.id === pipelineId ? pipeline.name : null;

    return breadcrumbsFor(
      routeTrail(),
      {
        organizationName: organization.name || undefined,
        projectName: project.name || undefined,
        pipelineName: pipelineName || pipelineId || undefined,
        userId: userId || undefined,
        jobId: jobId || undefined,
      },
      t,
    );
  });
</script>

{#snippet content(crumb: BreadcrumbItem)}
  <span class="whitespace-nowrap">{crumb.label}</span>{#if crumb.highlight}<span
      class="text-primary">#{crumb.highlight}</span
    >{/if}{#if crumb.detail}<span class="whitespace-nowrap">- {crumb.detail}</span>{/if}
{/snippet}

{#if crumbs.length > 0}
  <nav aria-label="breadcrumb" data-slot="breadcrumb">
    <ol
      data-slot="breadcrumb-list"
      class="flex flex-wrap items-center gap-2 text-sm break-words text-muted-foreground sm:gap-2.5"
    >
      {#each crumbs as crumb, index (index)}
        <li data-slot="breadcrumb-item" class="inline-flex items-center gap-1.5">
          {#if index === crumbs.length - 1}
            <span
              data-slot="breadcrumb-page"
              role="link"
              aria-disabled="true"
              aria-current="page"
              class="flex items-center gap-1 rounded-md bg-muted px-2 py-1 text-sm font-semibold text-foreground"
            >
              {@render content(crumb)}
            </span>
          {:else}
            <a
              data-slot="breadcrumb-link"
              href={crumb.pathname}
              class="flex items-center gap-1 rounded-md px-2 py-1 text-sm font-medium text-muted-foreground transition-all duration-200 hover:bg-primary/10 hover:text-primary"
            >
              {@render content(crumb)}
            </a>
          {/if}
        </li>
        {#if index < crumbs.length - 1}
          <li data-slot="breadcrumb-separator" role="presentation" aria-hidden="true">
            <ChevronRightIcon class="h-4 w-4 text-muted-foreground" />
          </li>
        {/if}
      {/each}
    </ol>
  </nav>
{/if}
