// src/modules/layout/presentation/ui/WhatsNewDialog.tsx
import { Trans, useLingui } from '@lingui/react/macro';
import { Button } from '@shadcn';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@shadcn/dialog.tsx';
import { useUnseenRelease } from '@/modules/layout/presentation/hooks/use-whats-new.ts';

/**
 * Announces the current release once, from the `whats-new.ts` declaration.
 * Nothing to write here when a feature ships — only a highlight to add there.
 */
export const WhatsNewDialog = () => {
  const { release, dismiss } = useUnseenRelease();
  const { i18n } = useLingui();

  if (!release) return null;

  return (
    <Dialog open onOpenChange={open => !open && dismiss()}>
      <DialogContent className='sm:max-w-lg'>
        <DialogHeader>
          <DialogTitle>
            <Trans>What's new in Scylla {release.version}</Trans>
          </DialogTitle>
          <DialogDescription>
            <Trans>Here is what landed in this version.</Trans>
          </DialogDescription>
        </DialogHeader>

        <ul className='flex flex-col gap-4 py-2'>
          {release.highlights.map(highlight => (
            <li key={highlight.id} className='flex items-start gap-3'>
              <span className='flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10'>
                <highlight.icon className='size-4 text-primary' />
              </span>
              <div className='min-w-0'>
                <p className='text-sm font-semibold text-foreground'>{i18n._(highlight.title)}</p>
                <p className='text-sm text-muted-foreground'>{i18n._(highlight.description)}</p>
              </div>
            </li>
          ))}
        </ul>

        <DialogFooter>
          <Button onClick={dismiss}>
            <Trans>Got it</Trans>
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

// src/modules/layout/presentation/ui/WhatsNewDialog.svelte
<script lang="ts">
  import { Button, DialogFooter } from '@shadcn';
  import { ScyllaDialog } from '@shared/presentation/ui';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { dismissRelease, unseenRelease } from '../whats-new.svelte.ts';
  import { layoutMessages } from './layout.messages.ts';

  const release = $derived(unseenRelease());
</script>

{#if release}
  <ScyllaDialog
    open
    onOpenChange={open => {
      if (!open) dismissRelease();
    }}
    class="sm:max-w-lg"
    title={t(layoutMessages.whatsNew(release.version))}
    description={t(layoutMessages.whatsNewDescription)}
  >
    <ul class="flex flex-col gap-4 py-2">
      {#each release.highlights as highlight (highlight.id)}
        <li class="flex items-start gap-3">
          <span class="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10">
            <highlight.icon class="size-4 text-primary" />
          </span>
          <div class="min-w-0">
            <p class="text-sm font-semibold text-foreground">{t(highlight.title)}</p>
            <p class="text-sm text-muted-foreground">{t(highlight.description)}</p>
          </div>
        </li>
      {/each}
    </ul>

    <DialogFooter>
      <Button onclick={dismissRelease}>{t(layoutMessages.gotIt)}</Button>
    </DialogFooter>
  </ScyllaDialog>
{/if}
