// extensions/scylla-base/src/features/secret/presentation/ui/components/SecretPagination.svelte
<script lang="ts">
  import ChevronLeftIcon from '@lucide/svelte/icons/chevron-left';
  import ChevronRightIcon from '@lucide/svelte/icons/chevron-right';
  import { Button } from '@scylla/ui/shadcn';
  import { t } from '@scylla/ui/i18n';
  import { secretMessages } from '../secret.messages.ts';

  interface Props {
    page: number;
    totalPages: number;
    totalItems: number;
    itemsPerPage: number;
    onPageChange: (page: number) => void;
  }

  let { page, totalPages, totalItems, itemsPerPage, onPageChange }: Props = $props();

  const firstItem = $derived(totalItems === 0 ? 0 : (page - 1) * itemsPerPage + 1);
  const lastItem = $derived(Math.min(page * itemsPerPage, totalItems));
</script>

<!-- Not mounted. Hand-rolled, not the shared `Pagination`: see AGENTS.md. -->
<div
  class="flex items-center justify-between gap-4 rounded-xl border border-border/60 bg-card px-4 py-3"
>
  <p class="text-sm text-muted-foreground">
    {t(secretMessages.showingRange(firstItem, lastItem, totalItems))}
  </p>
  <div class="flex items-center gap-2">
    <Button
      variant="outline"
      size="sm"
      disabled={page <= 1}
      onclick={() => onPageChange(page - 1)}
      class="h-8 gap-1"
    >
      <ChevronLeftIcon class="size-4" />
      <span class="hidden sm:inline">{t(secretMessages.previousPage)}</span>
    </Button>
    <span class="min-w-fit text-sm text-muted-foreground">{page} / {totalPages}</span>
    <Button
      variant="outline"
      size="sm"
      disabled={page >= totalPages}
      onclick={() => onPageChange(page + 1)}
      class="h-8 gap-1"
    >
      <span class="hidden sm:inline">{t(secretMessages.nextPage)}</span>
      <ChevronRightIcon class="size-4" />
    </Button>
  </div>
</div>

// src/modules/features/secret/presentation/ui/components/SecretPagination.tsx
import { Button } from '@shadcn';
import { ChevronLeft, ChevronRight } from 'lucide-react';

interface CredentialsPaginationProps {
  page: number;
  totalPages: number;
  totalItems: number;
  itemsPerPage: number;
  onPageChange: (page: number) => void;
}

export const SecretPagination = ({
  page,
  totalPages,
  totalItems,
  itemsPerPage,
  onPageChange,
}: CredentialsPaginationProps) => {
  const firstItem = totalItems === 0 ? 0 : (page - 1) * itemsPerPage + 1;
  const lastItem = Math.min(page * itemsPerPage, totalItems);

  return (
    <div className='rounded-xl border border-border/60 bg-card px-4 py-3 flex items-center justify-between gap-4'>
      <p className='text-sm text-muted-foreground'>
        Showing <span className='font-semibold'>{firstItem}</span>-
        <span className='font-semibold'>{lastItem}</span> of{' '}
        <span className='font-semibold'>{totalItems}</span> credentials
      </p>
      <div className='flex items-center gap-2'>
        <Button
          variant='outline'
          size='sm'
          disabled={page <= 1}
          onClick={() => onPageChange(page - 1)}
          className='h-8 gap-1'
        >
          <ChevronLeft className='size-4' />
          <span className='hidden sm:inline'>Prev</span>
        </Button>
        <span className='text-sm text-muted-foreground min-w-fit'>
          {page} / {totalPages}
        </span>
        <Button
          variant='outline'
          size='sm'
          disabled={page >= totalPages}
          onClick={() => onPageChange(page + 1)}
          className='h-8 gap-1'
        >
          <span className='hidden sm:inline'>Next</span>
          <ChevronRight className='size-4' />
        </Button>
      </div>
    </div>
  );
};
