// extensions/scylla-base/src/features/user/presentation/ui/settings/UserSettings/UserSettings.page.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { Card, CardContent, CardHeader, CardTitle } from '@scylla/ui/shadcn';
  import { t } from '@scylla/ui/i18n';
  import { userMessages } from '../../user.messages.ts';
  import UserInformation from '../UserInformation.svelte';

  interface Props {
    userId?: string;
    /** Filled by the route's owner (`organization`), which already depends on `user`. */
    organizations?: Snippet;
  }

  let { userId, organizations }: Props = $props();

  // `me`, or no id in the route: your own settings.
  const shownUserId = $derived(
    userId && userId !== 'me' ? userId : (localStorage.getItem('userId') ?? undefined),
  );
</script>

<!-- TODO: list only the organizations the user is in. -->
<div class="flex w-full flex-col gap-4">
  <div class="flex items-center gap-4">
    <h1 class="text-3xl font-bold">{t(userMessages.userSettings)}</h1>
  </div>

  <div class="flex space-x-6 bg-background">
    <div class="w-1/2">
      <UserInformation userId={shownUserId} />
    </div>

    {#if organizations}
      <div class="w-1/2">
        <Card class="w-full">
          <CardHeader>
            <CardTitle>{t(userMessages.organizations)}</CardTitle>
          </CardHeader>
          <CardContent class="space-y-4">{@render organizations()}</CardContent>
        </Card>
      </div>
    {/if}
  </div>
</div>

// src/modules/features/user/presentation/ui/settings/UserSettings.page.tsx
import { OrganizationList } from '@/modules/features/organization/presentation/ui/OrganizationList.tsx';
import { div } from 'framer-motion/m';
import { Card, CardContent, CardHeader, CardTitle } from '@shadcn';
import { UserInformation } from '@/modules/features/user/presentation/ui/settings/UserInformation.tsx';
import { useParams } from 'react-router-dom';
import { Trans } from '@lingui/react/macro';

//TODO: change and list only organization that the user is in
// (pass it as a props from Organization module)
export const UserSettingsPage = () => {
  const { userId } = useParams();

  return (
    <div className='flex flex-col gap-4 w-full'>
      <div className='flex items-center gap-4'>
        <h1 className='text-3xl font-bold'>
          <Trans>User settings</Trans>
        </h1>
      </div>

      <div className='flex space-x-6 bg-background'>
        <div className='w-1/2'>
          <UserInformation userId={userId ?? localStorage.getItem('userId') ?? undefined} />
        </div>

        <div className='w-1/2'>
          <Card className='w-full'>
            <CardHeader>
              <CardTitle>Organizations: </CardTitle>
            </CardHeader>
            <CardContent className='space-y-4'>
              <OrganizationList Wrapper={div} />
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default UserSettingsPage;
