// src/modules/user_settings/presentation/ui/UserInformation.tsx
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@shadcn';
import { ScyllaForm } from '@core/presentation/ui/utils/ScyllaForm.tsx';
import { type FormItem, FormItemType } from '@core/presentation/models/ScyllaForm.ts';

const FormItems: FormItem[] = [
  {
    label: 'First name',
    placeholder: 'John',
    id: 'first-name',
    type: FormItemType.Input,
    inputType: 'text',
  },
  {
    label: 'Last name',
    placeholder: 'Doe',
    id: 'last-name',
    type: FormItemType.Input,
    inputType: 'text',
  },
  {
    label: 'Email',
    placeholder: 'example@gmail.com',
    id: 'email',
    type: FormItemType.Input,
    inputType: 'email',
  },
  {
    label: 'Password',
    placeholder: '******',
    id: 'password',
    type: FormItemType.Input,
    inputType: 'password',
  },
  {
    label: 'Telephone',
    placeholder: '+33 1 22 33 44 55',
    id: 'tel',
    type: FormItemType.Input,
    inputType: 'tel',
  },
  {
    label: 'Language',
    id: 'language',
    type: FormItemType.Select,
    placeholder: 'Select a language',
    options: [
      {
        label: 'English',
        value: 'english',
      },
      {
        label: 'French',
        value: 'french',
      },
    ],
  },
];

export const UserInformation = () => {
  return (
    <Card className='w-full bg-white'>
      <CardHeader>
        <CardTitle>User information</CardTitle>
        <CardDescription>Manage your account details.</CardDescription>
      </CardHeader>

      <CardContent className='space-y-4'>
        <div className='flex items-center space-x-4'>
          <Avatar>
            <AvatarImage src='https://github.com/YohannMgt.png' />
            <AvatarFallback>YM</AvatarFallback>
          </Avatar>
          <div>
            <div className='text-base font-medium'>Yohann Mangenot</div>
            <div className='text-sm text-gray-500'>Cloud plan</div>
          </div>
        </div>

        <ScyllaForm
          onSubmit={v => console.log(v)}
          items={FormItems}
          buttonLabel={'Save'}
          className={'gap-2'}
        />
      </CardContent>
    </Card>
  );
};

// src/modules/features/user/presentation/ui/settings/UserInformation.svelte
<script lang="ts">
  import { createMutation, createQuery } from '@platform/query';
  import {
    Avatar,
    AvatarFallback,
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
  } from '@shadcn';
  import {
    FormItemType,
    ScyllaForm,
    type FormItem,
    type FormValues,
  } from '@shared/presentation/ui';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { userMutations, userQueries } from '../../user.queries.ts';
  import { userMessages } from '../user.messages.ts';

  interface Props {
    userId?: string;
  }

  let { userId }: Props = $props();

  const userQuery = createQuery(() => userQueries.byId(userId || undefined));
  const updateUser = createMutation(() => userMutations.update());

  const user = $derived(userQuery.data);

  const items: readonly FormItem<'username' | 'user-id'>[] = $derived([
    {
      label: t(userMessages.username),
      placeholder: user?.username ?? '',
      id: 'username',
      type: FormItemType.Input,
      inputType: 'text',
      disabled: false,
      defaultValue: user?.username ?? '',
    },
    {
      label: t(userMessages.userId),
      placeholder: user?.userId ?? '',
      id: 'user-id',
      type: FormItemType.Input,
      inputType: 'text',
      disabled: true,
      defaultValue: user?.userId ?? '',
    },
  ]);

  const handleSubmit = ({ username }: FormValues<'username' | 'user-id'>) => {
    if (userId) updateUser.mutate({ userId, username });
  };

  const initials = (username: string) =>
    username
      .split(' ')
      .map(part => part[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
</script>

<Card class="w-full bg-card">
  <CardHeader>
    <CardTitle>{t(userMessages.userInformation)}</CardTitle>
    <CardDescription>{t(userMessages.manageAccount)}</CardDescription>
  </CardHeader>

  {#if !userId}
    <CardContent>
      <div class="text-center text-muted-foreground">
        {t(userMessages.informationUnavailable)}
      </div>
    </CardContent>
  {:else if userQuery.isLoading}
    <CardContent>
      <div class="text-center text-muted-foreground">{t(userMessages.loadingInformation)}</div>
    </CardContent>
  {:else if userQuery.isError || !user}
    <CardContent>
      <div class="text-center text-destructive">{t(userMessages.informationError)}</div>
    </CardContent>
  {:else}
    <CardContent class="space-y-4">
      <div class="flex items-center space-x-4">
        <Avatar>
          <AvatarFallback>{initials(user.username)}</AvatarFallback>
        </Avatar>
        <div>
          <div class="text-base font-medium">{user.username}</div>
          <div class="text-sm text-muted-foreground">{t(userMessages.activeAccount)}</div>
        </div>
      </div>

      <!-- Keyed on the user: the form seeds its values once. -->
      {#key user.userId}
        <ScyllaForm
          onSubmit={handleSubmit}
          {items}
          buttonLabel={t(userMessages.save)}
          class="gap-2"
          isPending={updateUser.isPending}
        />
      {/key}
    </CardContent>
  {/if}
</Card>
