// src/modules/features/user_settings/presentation/ui/UserInformation.tsx
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@shadcn';

import { type FormItem, FormItemType } from '@core/presentation/models/ScyllaForm.ts';
import { ScyllaForm } from '@shared/presentation/ui/ScyllaForm.tsx';
import { useUser } from '@/modules/features/user_settings/presentation/hooks/useUserSettings.ts';
import { Trans } from '@lingui/react/macro';

export const UserInformation = () => {
  const userId = localStorage.getItem('userId');
  const { user, isLoading, isError } = useUser(userId || undefined);

  if (!userId) {
    return (
      <Card className='w-full bg-white'>
        <CardHeader>
          <CardTitle>
            <Trans>User information</Trans>
          </CardTitle>
          <CardDescription>
            <Trans>Manage your account details.</Trans>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className='text-center text-gray-500'>
            <Trans>User information not available</Trans>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (isLoading) {
    return (
      <Card className='w-full bg-white'>
        <CardHeader>
          <CardTitle>
            <Trans>User information</Trans>
          </CardTitle>
          <CardDescription>
            <Trans>Manage your account details.</Trans>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className='text-center text-gray-500'>
            <Trans>Loading user information...</Trans>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (isError || !user) {
    return (
      <Card className='w-full bg-white'>
        <CardHeader>
          <CardTitle>
            <Trans>User information</Trans>
          </CardTitle>
          <CardDescription>
            <Trans>Manage your account details.</Trans>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className='text-center text-red-500'>
            <Trans>Error loading user information</Trans>
          </div>
        </CardContent>
      </Card>
    );
  }

  const FormItems: FormItem[] = [
    {
      label: 'Username',
      placeholder: user.username,
      id: 'username',
      type: FormItemType.Input,
      inputType: 'text',
    },
    {
      label: 'User ID',
      placeholder: user.user_id,
      id: 'user-id',
      type: FormItemType.Input,
      inputType: 'text',
      disabled: true,
    },
  ];

  const getInitials = (username: string) => {
    return username
      .split(' ')
      .map(n => n[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
  };

  return (
    <Card className='w-full bg-white'>
      <CardHeader>
        <CardTitle>
          <Trans>User information</Trans>
        </CardTitle>
        <CardDescription>
          <Trans>Manage your account details.</Trans>
        </CardDescription>
      </CardHeader>

      <CardContent className='space-y-4'>
        <div className='flex items-center space-x-4'>
          <Avatar>
            <AvatarImage src={`https://github.com/${user.username}.png`} />
            <AvatarFallback>{getInitials(user.username)}</AvatarFallback>
          </Avatar>
          <div>
            <div className='text-base font-medium'>{user.username}</div>
            <div className='text-sm text-gray-500'>
              <Trans>Active account</Trans>
            </div>
          </div>
        </div>

        <ScyllaForm
          onSubmit={v => console.log(v)}
          items={FormItems}
          buttonLabel={'Save'}
          className={'gap-2'}
        />
      </CardContent>
    </Card>
  );
};

// src/modules/features/user/presentation/ui/settings/UserInformation.svelte
<script lang="ts">
  import { createMutation, createQuery } from '@platform/query';
  import {
    Avatar,
    AvatarFallback,
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
  } from '@shadcn';
  import {
    FormItemType,
    ScyllaForm,
    type FormItem,
    type FormValues,
  } from '@shared/presentation/ui';
  import { t } from '@shared/presentation/utils/i18n-svelte.svelte.ts';
  import { userMutations, userQueries } from '../../user.queries.ts';
  import { userMessages } from '../user.messages.ts';

  interface Props {
    userId?: string;
  }

  let { userId }: Props = $props();

  const userQuery = createQuery(() => userQueries.byId(userId || undefined));
  const updateUser = createMutation(() => userMutations.update());

  const user = $derived(userQuery.data);

  const items: readonly FormItem<'username' | 'user-id'>[] = $derived([
    {
      label: t(userMessages.username),
      placeholder: user?.username ?? '',
      id: 'username',
      type: FormItemType.Input,
      inputType: 'text',
      disabled: false,
      defaultValue: user?.username ?? '',
    },
    {
      label: t(userMessages.userId),
      placeholder: user?.userId ?? '',
      id: 'user-id',
      type: FormItemType.Input,
      inputType: 'text',
      disabled: true,
      defaultValue: user?.userId ?? '',
    },
  ]);

  const handleSubmit = ({ username }: FormValues<'username' | 'user-id'>) => {
    if (userId) updateUser.mutate({ userId, username });
  };

  const initials = (username: string) =>
    username
      .split(' ')
      .map(part => part[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
</script>

<Card class="w-full bg-card">
  <CardHeader>
    <CardTitle>{t(userMessages.userInformation)}</CardTitle>
    <CardDescription>{t(userMessages.manageAccount)}</CardDescription>
  </CardHeader>

  {#if !userId}
    <CardContent>
      <div class="text-center text-muted-foreground">
        {t(userMessages.informationUnavailable)}
      </div>
    </CardContent>
  {:else if userQuery.isLoading}
    <CardContent>
      <div class="text-center text-muted-foreground">{t(userMessages.loadingInformation)}</div>
    </CardContent>
  {:else if userQuery.isError || !user}
    <CardContent>
      <div class="text-center text-destructive">{t(userMessages.informationError)}</div>
    </CardContent>
  {:else}
    <CardContent class="space-y-4">
      <div class="flex items-center space-x-4">
        <Avatar>
          <AvatarFallback>{initials(user.username)}</AvatarFallback>
        </Avatar>
        <div>
          <div class="text-base font-medium">{user.username}</div>
          <div class="text-sm text-muted-foreground">{t(userMessages.activeAccount)}</div>
        </div>
      </div>

      <!-- Keyed on the user: the form seeds its values once. -->
      {#key user.userId}
        <ScyllaForm
          onSubmit={handleSubmit}
          {items}
          buttonLabel={t(userMessages.save)}
          class="gap-2"
          isPending={updateUser.isPending}
        />
      {/key}
    </CardContent>
  {/if}
</Card>
