// src/modules/features/pipeline/presentation/ui/editor/PipelineUpdate.page.tsx
import { useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { usePipeline } from '@/modules/features/pipeline/presentation/hooks/use-pipeline.ts';
import { useUpdatePipeline } from '@/modules/features/pipeline/presentation/hooks/use-update-pipeline.ts';
import { ErrorState } from '@shared/presentation/ui/feedback/ErrorState.tsx';
import { PipelineEditor } from '@/modules/features/pipeline/presentation/ui/editor/PipelineEditor.tsx';

export const PipelineUpdatePage = () => {
  const { pipelineId } = useParams();
  const { pipeline, isLoading, isError } = usePipeline(pipelineId ?? '');
  const updatePipeline = useUpdatePipeline();

  const initialScript = useMemo(
    () =>
      pipeline
        ? JSON.stringify(
            { name: pipeline.name, projectId: pipeline.projectId, nodes: pipeline.nodes },
            null,
            2,
          )
        : undefined,
    [pipeline],
  );

  if (isLoading) return <>Loading...</>;
  if (isError) return <ErrorState message='Failed to load pipeline' />;

  return (
    <div className='flex h-full flex-col gap-4'>
      <PipelineEditor
        mode='edit'
        submitLabel='Save'
        projectId={pipeline?.projectId}
        initialScript={initialScript}
        onSubmit={({ name, steps }) =>
          pipelineId && updatePipeline.mutate({ id: pipelineId, name, nodes: steps })
        }
        isSubmitPending={updatePipeline.isPending}
      />
    </div>
  );
};

// extensions/scylla-base/src/features/pipeline/presentation/ui/editor/PipelineUpdate.page.svelte
<script lang="ts">
  import { createMutation, createQuery } from '@scylla/core-sdk';
  import { ErrorState } from '@scylla/ui';
  import { t } from '@scylla/ui/i18n';
  import { pipelineMutations, pipelineQueries } from '../../pipeline.queries.ts';
  import PipelineEditor from './PipelineEditor.svelte';
  import { pipelineMessages } from '../../pipeline.messages.ts';

  interface Props {
    pipelineId?: string;
  }

  let { pipelineId }: Props = $props();

  const pipelineQuery = createQuery(() => pipelineQueries.byId(pipelineId ?? ''));
  const updatePipeline = createMutation(() => pipelineMutations.update());

  const pipeline = $derived(pipelineQuery.data);

  /** Only the fields the editor owns: an id or timestamps would travel back on save. */
  const initialScript = $derived(
    pipeline
      ? JSON.stringify(
          { name: pipeline.name, projectId: pipeline.projectId, nodes: pipeline.nodes },
          null,
          2,
        )
      : undefined,
  );
</script>

{#if pipelineQuery.isLoading}
  <p>{t(pipelineMessages.loading)}</p>
{:else if pipelineQuery.isError}
  <ErrorState message={t(pipelineMessages.loadPipelineError)} />
{:else}
  <div class="flex h-full flex-col gap-4">
    <PipelineEditor
      mode="edit"
      submitLabel={t(pipelineMessages.save)}
      projectId={pipeline?.projectId}
      {initialScript}
      onSubmit={({ name, steps }) => {
        if (pipelineId) updatePipeline.mutate({ id: pipelineId, name, nodes: steps });
      }}
      isSubmitPending={updatePipeline.isPending}
    />
  </div>
{/if}
