// src/modules/features/secret/presentation/ui/components/SecretHealthOverview.tsx
import { Activity, ClipboardList, ShieldCheck } from 'lucide-react';
import { Button, Card, CardContent, CardHeader, CardTitle } from '@shadcn';

interface CredentialsHealthOverviewProps {
  warningCount: number;
}

export const SecretHealthOverview = ({ warningCount }: CredentialsHealthOverviewProps) => {
  return (
    <div className='grid gap-4 md:grid-cols-3'>
      <Card className='rounded-2xl border-blue-200/40 bg-blue-500/5 py-3 gap-2'>
        <CardHeader className='pb-1'>
          <CardTitle className='flex items-center gap-2 text-sm md:text-base'>
            <ShieldCheck className='size-4 text-primary' />
            Rotation Policy
          </CardTitle>
        </CardHeader>
        <CardContent className='space-y-1'>
          <p className='text-xs text-muted-foreground'>
            {warningCount} credential{warningCount > 1 ? 's' : ''} overdue for rotation based on
            your enterprise policy (90 days).
          </p>
          <Button variant='outline' className='rounded-xl w-full h-8 text-xs'>
            Review Policy
          </Button>
        </CardContent>
      </Card>

      <Card className='rounded-2xl border-emerald-200/40 bg-emerald-500/5 py-3 gap-2'>
        <CardHeader className='pb-1'>
          <CardTitle className='flex items-center gap-2 text-sm md:text-base'>
            <Activity className='size-4 text-emerald-500' />
            Vault Health
          </CardTitle>
        </CardHeader>
        <CardContent className='space-y-1'>
          <div>
            <p className='text-2xl font-semibold tracking-tight'>99.9%</p>
            <p className='text-xs text-muted-foreground'>Uptime status</p>
          </div>
          <p className='text-xs text-muted-foreground'>Last sync: 2 min ago</p>
        </CardContent>
      </Card>

      <Card className='rounded-2xl border-primary/20 bg-primary/10 py-3 gap-2'>
        <CardHeader className='pb-1'>
          <CardTitle className='flex items-center gap-2 text-sm md:text-base'>
            <ClipboardList className='size-4 text-primary' />
            Audit Logging
          </CardTitle>
        </CardHeader>
        <CardContent className='space-y-1'>
          <div className='space-y-1 text-xs'>
            <div className='flex items-center justify-between'>
              <span className='text-muted-foreground'>Access attempts (24h)</span>
              <span className='font-semibold text-foreground'>1,402</span>
            </div>
            <div className='flex items-center justify-between'>
              <span className='text-muted-foreground'>Unauthorized attempts</span>
              <span className='font-semibold text-destructive'>0</span>
            </div>
          </div>
          <Button className='w-full rounded-xl h-8 text-xs'>View Audit Logs</Button>
        </CardContent>
      </Card>
    </div>
  );
};

// extensions/scylla-base/src/features/secret/presentation/ui/components/SecretHealthOverview.svelte
<script lang="ts">
  import ActivityIcon from '@lucide/svelte/icons/activity';
  import ClipboardListIcon from '@lucide/svelte/icons/clipboard-list';
  import ShieldCheckIcon from '@lucide/svelte/icons/shield-check';
  import { Button, Card, CardContent, CardHeader, CardTitle } from '@scylla/ui/shadcn';
  import { t } from '@scylla/ui/i18n';
  import { secretMessages } from '../secret.messages.ts';

  interface Props {
    warningCount: number;
  }

  let { warningCount }: Props = $props();
</script>

<!-- Not mounted: placeholder figures. See AGENTS.md. -->
<div class="grid gap-4 md:grid-cols-3">
  <Card class="gap-2 rounded-2xl border-blue-200/40 bg-blue-500/5 py-3">
    <CardHeader class="pb-1">
      <CardTitle class="flex items-center gap-2 text-sm md:text-base">
        <ShieldCheckIcon class="size-4 text-primary" />
        {t(secretMessages.rotationPolicy)}
      </CardTitle>
    </CardHeader>
    <CardContent class="space-y-1">
      <p class="text-xs text-muted-foreground">
        {t(secretMessages.rotationOverdue(warningCount))}
      </p>
      <Button variant="outline" class="h-8 w-full rounded-xl text-xs">
        {t(secretMessages.reviewPolicy)}
      </Button>
    </CardContent>
  </Card>

  <Card class="gap-2 rounded-2xl border-emerald-200/40 bg-emerald-500/5 py-3">
    <CardHeader class="pb-1">
      <CardTitle class="flex items-center gap-2 text-sm md:text-base">
        <ActivityIcon class="size-4 text-emerald-500" />
        {t(secretMessages.vaultHealth)}
      </CardTitle>
    </CardHeader>
    <CardContent class="space-y-1">
      <div>
        <p class="text-2xl font-semibold tracking-tight">99.9%</p>
        <p class="text-xs text-muted-foreground">{t(secretMessages.uptimeStatus)}</p>
      </div>
      <p class="text-xs text-muted-foreground">{t(secretMessages.lastSync)}</p>
    </CardContent>
  </Card>

  <Card class="gap-2 rounded-2xl border-primary/20 bg-primary/10 py-3">
    <CardHeader class="pb-1">
      <CardTitle class="flex items-center gap-2 text-sm md:text-base">
        <ClipboardListIcon class="size-4 text-primary" />
        {t(secretMessages.auditLogging)}
      </CardTitle>
    </CardHeader>
    <CardContent class="space-y-1">
      <div class="space-y-1 text-xs">
        <div class="flex items-center justify-between">
          <span class="text-muted-foreground">{t(secretMessages.accessAttempts)}</span>
          <span class="font-semibold text-foreground">1,402</span>
        </div>
        <div class="flex items-center justify-between">
          <span class="text-muted-foreground">{t(secretMessages.unauthorizedAttempts)}</span>
          <span class="font-semibold text-destructive">0</span>
        </div>
      </div>
      <Button class="h-8 w-full rounded-xl text-xs">{t(secretMessages.viewAuditLogs)}</Button>
    </CardContent>
  </Card>
</div>
